import{test,expect}from"@playwright/test";import{assertOwnerPage}from"./support.mjs";

test("NEXT Home explains today's work with truthful durable summaries",async({page})=>{await assertOwnerPage(page,"/home");for(const text of["今日やること","コンテンツ","案件","収益"])await expect(page.getByText(text,{exact:true}).first()).toBeVisible();await expect(page.getByText(/実データから確認/)).toBeVisible()});

test("Japanese grouped navigation exposes the seven primary user intents",async({page})=>{await assertOwnerPage(page,"/home");for(const text of["AI秘書","SNS運用","コンテンツ制作","仕事を探す","収益管理","チーム","接続・API"])await expect(page.getByText(text,{exact:true}).first()).toBeAttached()});

test("AI Secretary routes Threads intent with authorized context and zero provider calls",async({page})=>{const calls=[];page.on("request",request=>{if(/openai|anthropic|perplexity|generativelanguage|\/api\/ai/.test(request.url()))calls.push(request.url())});await assertOwnerPage(page,"/assistant");await page.getByLabel("日本語で相談").fill("Threadsの投稿を作りたい");await page.getByRole("button",{name:"整理する"}).click();await expect(page.getByText(/保存済みのThreads下書き/)).toBeVisible();await page.getByRole("button",{name:"Threads下書きを作る"}).click();await expect(page).toHaveURL(/\/content$/);expect(calls).toEqual([])});

test("Threads draft saves privately and survives reload",async({page})=>{await assertOwnerPage(page,"/content");const text=`Playwright下書き ${Date.now()}`;await page.getByLabel("投稿内容").fill(text);await page.getByRole("button",{name:"非公開で保存"}).click();await expect(page.getByText("Threadsの下書きを保存しました。",{exact:true})).toBeVisible();await page.reload({waitUntil:"domcontentloaded"});await expect(page.getByText(text,{exact:true})).toBeVisible({timeout:30_000});await expect(page.getByText(/Threads \/ 下書き/).first()).toBeVisible()});

test("CrowdWorks manual opportunity persists and exposes valid next status",async({page})=>{await assertOwnerPage(page,"/opportunities");const title=`記事制作案件 ${Date.now()}`;await page.getByLabel("案件名").fill(title);await page.getByLabel("仕事内容").fill("AI活用記事を作成する案件");await page.getByRole("button",{name:"非公開で保存"}).click();await expect(page.getByText(title,{exact:true})).toBeVisible();await page.reload({waitUntil:"domcontentloaded"});await expect(page.getByText(title,{exact:true})).toBeVisible({timeout:30_000});await expect(page.getByRole("button",{name:"検討中"}).last()).toBeVisible()});

test("Revenue Center separates truth classes and never fabricates zero",async({page})=>{await assertOwnerPage(page,"/revenue");await expect(page.getByRole("option",{name:"見込み"})).toBeAttached();await expect(page.getByRole("option",{name:"まだ確認できていない"})).toBeAttached();await expect(page.getByText(/Actual Revenueは証拠確認済み/)).toBeVisible();await expect(page.getByText(/空欄は未確認です。0円には置き換えません/)).toBeVisible()});

test("Feedback is private, durable, and explicit about support visibility",async({page})=>{await assertOwnerPage(page,"/feedback");await page.getByLabel("内容").fill("操作が分かりにくい");await page.getByRole("button",{name:"非公開で保存"}).click();await expect(page.getByText(/非公開で保存しました/)).toBeVisible();await expect(page.getByText(/Ownerを含む他ユーザーには自動共有されません/)).toBeVisible()});

test("Connector Health exposes capability cost and no credentials",async({page})=>{await assertOwnerPage(page,"/integrations");for(const connector of["OpenAI","Canva","Instagram / Threads","Google","A8.net"])await expect(page.getByRole("cell",{name:connector,exact:true})).toBeVisible();await expect(page.getByText(/認証情報、トークン、接続URLは表示しません/)).toBeVisible()});

test("legal page loads current mandatory versions with unchecked affirmative consent",async({page})=>{await assertOwnerPage(page,"/legal");await expect(page.getByText("DRAFT — LEGAL REVIEW REQUIRED",{exact:true})).toBeVisible();const boxes=page.locator('input[type="checkbox"]');await expect(boxes).toHaveCount(4);for(let index=0;index<4;index++)await expect(boxes.nth(index)).not.toBeChecked();await expect(page.getByRole("button",{name:"同意を記録して利用開始"})).toBeDisabled()});

for(const width of[320,360,375,390,430,768,820,1024,1180,1280,1440])test(`NEXT responsive ${width}px has no document overflow`,async({page})=>{await page.setViewportSize({width,height:Math.max(800,Math.round(width*.75))});await assertOwnerPage(page,"/content");const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);expect(overflow).toBeLessThanOrEqual(1)});
