import {expect} from "@playwright/test";
export const AUTH_FILE="playwright/.auth/owner.json";
export const ROUTES=[["home","/home"],["employees","/employees"],["approvals","/approvals"],["operations","/operations"],["revenue","/revenue"],["insights","/insights"],["integrations","/integrations"],["inbox","/inbox"],["audit","/audit"],["settings","/settings"],["affiliate-intelligence","/affiliate-intelligence"]];
export const VIEWPORTS=[["desktop",1440,900],["laptop",1280,800],["ipad-landscape",1180,820],["ipad-portrait",820,1180],["mobile",390,844],["small-mobile",360,800]];
const MOJIBAKE=/[\u7e3a\u7e67\u8b41\u8700\u9089\u9b25\u9a5f]|\ufffd/u;
const UUID=/\b[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\b/i;
const SECRET=/(?:bearer\s+[a-z0-9._~+\/-]{12,}|(?:access|refresh)[_-]?token\s*[:=]|client[_-]?secret\s*[:=]|sk-[a-z0-9_-]{12,})/i;
const RAW_ENUM=/\b(?:awaiting_approval|dry_run_ready|evidence_waiting|manual_package_ready|owner_artifact_approval|global_execution_enabled|provider_execution_enabled)\b/i;
export function observeRuntime(page){const consoleErrors=[],pageErrors=[],failedRequests=[];page.on("console",m=>{if(m.type()==="error")consoleErrors.push(m.text().replace(/[A-Za-z0-9_-]{24,}/g,"[redacted]"));});page.on("pageerror",e=>pageErrors.push(String(e.message||e).replace(/[A-Za-z0-9_-]{24,}/g,"[redacted]")));page.on("requestfailed",r=>{const url=new URL(r.url());failedRequests.push(`${r.method()} ${url.origin}${url.pathname} ${r.failure()?.errorText||"failed"}`);});return {consoleErrors,pageErrors,failedRequests};}
export async function assertOwnerPage(page,path){await page.goto(path,{waitUntil:"domcontentloaded"});await expect(page.locator("main")).toBeVisible();await expect(page.locator("h1").first()).toBeVisible();await expect(page.locator("body")).not.toContainText("Ownerログイン");await expect(page.locator('[aria-busy="true"]')).toHaveCount(0,{timeout:20_000});const value=await page.locator("body").innerText();expect(MOJIBAKE.test(value),`mojibake found at ${path}`).toBeFalsy();expect(UUID.test(value),`raw UUID found at ${path}`).toBeFalsy();expect(SECRET.test(value),`credential-like text found at ${path}`).toBeFalsy();expect(RAW_ENUM.test(value),`raw enum found at ${path}`).toBeFalsy();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);expect(overflow,`horizontal overflow at ${path}`).toBeLessThanOrEqual(1);}
export async function screenshotSafe(page,name){await page.screenshot({path:`playwright-artifacts/screenshots/${name}.png`,fullPage:true,animations:"disabled",mask:[page.locator('input[type="password"]'),page.locator('input[type="email"]')]});}
