import { AffiliateV2Error, mapRepositoryError } from "../domain/affiliateV2Contracts.js";
import { aggregateAffiliateKpis, buildIntelligenceGraph } from "../domain/affiliateIntelligenceV2.js";
import { createAffiliateV2ProductRepository } from "../repositories/affiliateV2ProductRepository.js";
import { createAffiliateV2IntelligenceRepository } from "../repositories/affiliateV2IntelligenceRepository.js";
import { createAffiliateV2RiskRepository } from "../repositories/affiliateV2RiskRepository.js";
import { createAffiliateV2BriefRepository } from "../repositories/affiliateV2BriefRepository.js";
import { createAffiliateProgramMasterRepository } from "../repositories/affiliateProgramMasterRepository.js";

const CANONICAL_COLUMNS=Object.freeze({affiliate_programs:"id,workspace_id,offer_id,program_name,status,risk_level,truth_class,updated_at",affiliate_offers:"id,workspace_id,title,advertiser,status,currency,updated_at",affiliate_publications:"id,workspace_id,affiliate_program_id,content_asset_id,execution_package_id,evidence_candidate_id,channel,publication_url,published_at,status,owner_confirmed,external_execution_allowed,created_at,updated_at",affiliate_performance_records:"id,workspace_id,affiliate_program_id,publication_id,evidence_candidate_id,period_start,period_end,clicks,conversions,pending_revenue_minor,approved_revenue_minor,rejected_revenue_minor,cost_minor,currency,source_reference,truth_class,created_at",revenue_records:"id,workspace_id,gross_amount_minor,cost_amount_minor,net_amount_minor,campaign_id,recognized_at",operating_cost_records:"id,workspace_id,campaign_id,amount_minor,value_type,occurred_at",executive_decisions:"id,workspace_id,source_entity,source_id,status,urgency,owner_action,deadline",evidence_candidates:"id,workspace_id,campaign_id,status,source_reference,created_at",content_assets:"id,workspace_id,asset_type,status,content_reference,created_at"});
const limit=100;
const CANONICAL_ORDER=Object.freeze({affiliate_programs:"updated_at",affiliate_offers:"updated_at",affiliate_publications:"updated_at",affiliate_performance_records:"period_end",revenue_records:"recognized_at",operating_cost_records:"occurred_at",executive_decisions:"deadline",evidence_candidates:"created_at",content_assets:"created_at"});
function createCanonicalReader(client){return async(table,workspaceId,filters={})=>{if(!client?.from||!workspaceId)throw new AffiliateV2Error("VALIDATION_FAILED",{operation:"canonical_read",object:table});try{let q=client.from(table).select(CANONICAL_COLUMNS[table]).eq("workspace_id",workspaceId);for(const [key,value]of Object.entries(filters))if(value!=null)q=q.eq(key,value);const {data,error}=await q.order(CANONICAL_ORDER[table],{ascending:false}).limit(limit);if(error)throw error;return data||[];}catch(error){throw mapRepositoryError(error,{operation:"canonical_read",object:table});}};}

export function createAffiliateV2CommandCenterService(client){
  const products=createAffiliateV2ProductRepository(client), intelligence=createAffiliateV2IntelligenceRepository(client), risks=createAffiliateV2RiskRepository(client), briefs=createAffiliateV2BriefRepository(client), programMaster=createAffiliateProgramMasterRepository(client), read=createCanonicalReader(client);
  return {
    listProgramMaster:(workspaceId)=>programMaster.listPrograms(workspaceId),
    getProgramMaster:(workspaceId,programId)=>programMaster.getProgram(workspaceId,programId),
    saveProgramMasterAffiliateLink:(workspaceId,programId,input)=>programMaster.saveAffiliateLink(workspaceId,programId,input),
    registerProgramMaster:(input)=>programMaster.registerProgram(input),
    updateProgramMaster:(programId,input)=>programMaster.updateProgram(programId,input),
    updateProgramMasterPractical:(programId,input)=>programMaster.updatePractical(programId,input),
    deleteProgramMasterIfSafe:(programId,input)=>programMaster.deleteIfSafe(programId,input),
    getProgramMasterDraft:(programId)=>programMaster.getDraft(programId),
    saveProgramMasterDraft:(programId,input)=>programMaster.saveDraft(programId,input),
    updateProgramMasterOperational:(programId,input)=>programMaster.updateOperational(programId,input),
    async getAffiliateCommandCenter(workspaceId){const results=await Promise.allSettled([read("affiliate_programs",workspaceId),programMaster.listPrograms(workspaceId),read("affiliate_publications",workspaceId),read("affiliate_performance_records",workspaceId),risks.listAlerts(workspaceId,{status:"open"}),briefs.getLatestDailyBrief(workspaceId),read("revenue_records",workspaceId),read("operating_cost_records",workspaceId)]),value=(index,fallback)=>results[index].status==="fulfilled"?results[index].value:fallback,[programs,programMasterRows,publications,performance,alerts,brief,revenue,costs]=[value(0,[]),value(1,[]),value(2,[]),value(3,[]),value(4,[]),value(5,null),value(6,[]),value(7,[])],available=(index)=>results[index].status==="fulfilled",kpis=aggregateAffiliateKpis({performance,revenue,costs}),actualRevenue=available(6)&&revenue.length?kpis.actualRevenue:"Unknown",actualCost=available(7)&&costs.some((row)=>row.value_type==="actual")?kpis.actualCost:"Unknown",netProfit=typeof actualRevenue==="number"&&typeof actualCost==="number"?actualRevenue-actualCost:"Unknown",roi=typeof netProfit==="number"&&actualCost>0?netProfit/actualCost:"Unknown";return Object.freeze({programs:Object.freeze(programs.map((p)=>Object.freeze({id:p.id,offerId:p.offer_id,name:p.program_name,status:p.status,risk:p.risk_level,truthClass:p.truth_class,updatedAt:p.updated_at}))),programMaster:programMasterRows,publications:Object.freeze(publications),performance:Object.freeze(performance),kpis:Object.freeze(kpis),actualFinancials:Object.freeze({actualRevenue,actualCost,netProfit,roi,truthClass:typeof netProfit==="number"?"Actual":"Unknown"}),availability:Object.freeze({programs:available(0),programMaster:available(1),publications:available(2),performance:available(3),alerts:available(4),brief:available(5),revenue:available(6),cost:available(7)}),alerts:Object.freeze(alerts),dailyBrief:brief,actualSource:Object.freeze({revenue:"revenue_records",cost:"operating_cost_records"}),externalExecution:"LOCKED"});},
    async getProgramWorkspaceSummary(workspaceId,programId){const [programs,productRows,research,experiments,snapshots,riskRows,alerts,publications,performance]=await Promise.all([read("affiliate_programs",workspaceId,{id:programId}),products.listProducts(workspaceId,{programId}),intelligence.listResearchEntities(workspaceId,programId),intelligence.listExperiments(workspaceId,programId),intelligence.listSnapshots(workspaceId,programId),risks.listRiskFindings(workspaceId,programId),risks.listAlerts(workspaceId,{programId}),read("affiliate_publications",workspaceId,{affiliate_program_id:programId}),read("affiliate_performance_records",workspaceId,{affiliate_program_id:programId})]);if(!programs[0])throw new AffiliateV2Error("NOT_FOUND",{operation:"program_summary",object:"affiliate_programs"});return Object.freeze({program:Object.freeze({id:programs[0].id,offerId:programs[0].offer_id,name:programs[0].program_name,status:programs[0].status,truthClass:programs[0].truth_class}),products:Object.freeze(productRows),research:Object.freeze(research),experiments:Object.freeze(experiments),snapshots:Object.freeze(snapshots),risks:Object.freeze(riskRows),alerts:Object.freeze(alerts),publications:Object.freeze(publications),performance:Object.freeze(performance),externalExecution:"LOCKED"});},
    async getOwnerDailyBriefContext(workspaceId){const [brief,decisions,criticalAlerts,programs]=await Promise.all([briefs.getLatestDailyBrief(workspaceId),read("executive_decisions",workspaceId,{status:"pending"}),risks.getCriticalAlerts(workspaceId),read("affiliate_programs",workspaceId)]);return Object.freeze({brief,pendingDecisions:Object.freeze(decisions.map((d)=>Object.freeze({id:d.id,sourceEntity:d.source_entity,sourceId:d.source_id,urgency:d.urgency,ownerAction:d.owner_action,deadline:d.deadline}))),criticalAlerts:Object.freeze(criticalAlerts),programCount:programs.length,externalExecution:"LOCKED"});},
    async getIntelligenceGraphProjection(workspaceId,offerId){const offers=await read("affiliate_offers",workspaceId,{id:offerId});if(!offers[0])throw new AffiliateV2Error("NOT_FOUND",{operation:"graph",object:"affiliate_offers"});const programs=await read("affiliate_programs",workspaceId,{offer_id:offerId});if(!programs[0])return buildIntelligenceGraph({id:offers[0].id,title:offers[0].title,truthClass:"Unknown"},{});const programId=programs[0].id;const [productRows,research,snapshots,riskRows]=await Promise.all([products.listProducts(workspaceId,{programId}),intelligence.listResearchEntities(workspaceId,programId),intelligence.listSnapshots(workspaceId,programId),risks.listRiskFindings(workspaceId,programId)]);return buildIntelligenceGraph({id:offers[0].id,title:offers[0].title,truthClass:"Unknown"},{Product:productRows.map((x)=>({...x,title:x.name})),Audience:research.filter((x)=>x.entityType==="audience").map((x)=>({...x,title:x.name})),Competitor:research.filter((x)=>x.entityType==="competitor").map((x)=>({...x,title:x.name})),Keyword:research.filter((x)=>x.entityType==="keyword").map((x)=>({...x,title:x.name})),Intelligence:snapshots.map((x)=>({...x,title:x.snapshotType})),Risk:riskRows.map((x)=>({...x,title:x.title}))});},
  };
}
