export const AI_EMPLOYEE_PLATFORM_VERSION="1.0.0";
export const TASK_STATES=Object.freeze(["draft","validated","dry_run_ready","awaiting_connection","awaiting_scope","awaiting_approval","ready","reserved","running","partial","completed","failed","cancelled","expired"]);
export const TERMINAL_STATES=new Set(["completed","failed","cancelled","expired"]);
const TRANSITIONS=Object.freeze({draft:["validated","cancelled"],validated:["dry_run_ready","awaiting_connection","awaiting_scope","awaiting_approval","cancelled"],dry_run_ready:["awaiting_connection","awaiting_scope","awaiting_approval","ready","cancelled","expired"],awaiting_connection:["dry_run_ready","cancelled","expired"],awaiting_scope:["dry_run_ready","cancelled","expired"],awaiting_approval:["ready","cancelled","expired"],ready:["reserved","cancelled","expired"],reserved:["running","failed","cancelled"],running:["partial","completed","failed","cancelled"],partial:["completed","failed"],completed:[],failed:[],cancelled:[],expired:[]});
export const EMPLOYEE_REGISTRY=Object.freeze({google_operations:Object.freeze({id:"google_operations",name:"Google Operations AI Employee",role:"Google系サービスを横断するOperations担当",version:"1.0.0",maturity:"Conditional",provider:"google",externalExecution:false})});
const REQUIRED=["workspaceId","ownerId","aiEmployeeId","workflowId","taskId","correlationId","requestClass","capability","purpose","requestedAt","requestedBy","parameters","scopeRequirements","dataClassification","approvalRequirements","idempotencyKey","dryRun","maxApiCalls","maxRecords","maxDurationMs","costCeilingJpy","expectedOutputType"];
export function validateEmployeeTask(input={}){const errors=[];for(const key of REQUIRED)if(input[key]===undefined||input[key]===null||input[key]==="")errors.push(`${key}_required`);if(input.aiEmployeeId&&!EMPLOYEE_REGISTRY[input.aiEmployeeId])errors.push("employee_unknown");if(!["public","internal","confidential","restricted"].includes(input.dataClassification))errors.push("classification_invalid");if(input.dryRun!==true)errors.push("external_execution_locked");for(const key of ["maxApiCalls","maxRecords","maxDurationMs","costCeilingJpy"])if(!Number.isFinite(input[key])||input[key]<0)errors.push(`${key}_invalid`);return {valid:errors.length===0,errors,externalExecution:false};}
export function createEmployeeTask(input,now=input?.requestedAt){const v=validateEmployeeTask(input);if(!v.valid)return {ok:false,status:"blocked",errors:v.errors,externalExecution:false};return {ok:true,task:{...input,status:"validated",createdAt:now,updatedAt:now,retryCount:0,apiCalls:0,aiCalls:0,actualCostJpy:0,recordsProcessed:0,mock:true,externalExecution:false}};}
export function transitionEmployeeTask(task,next,at){if(!TASK_STATES.includes(next)||!TRANSITIONS[task?.status]?.includes(next))return {ok:false,reasonCode:"TASK_TRANSITION_FORBIDDEN"};return {ok:true,task:{...task,status:next,updatedAt:at}};}
export function evaluateQuota(task,usage={}){if(task.maxApiCalls>50||task.maxRecords>1000||task.maxDurationMs>30000)return {allowed:false,reasonCode:"TASK_CEILING_EXCEEDED"};if(Number(usage.apiCalls||0)+task.maxApiCalls>Number(usage.dailyCallLimit||100))return {allowed:false,reasonCode:"GOOGLE_QUOTA_BLOCKED"};if(Number(usage.retryCount||0)>1)return {allowed:false,reasonCode:"RETRY_LIMIT_REACHED"};return {allowed:true,reasonCode:"QUOTA_AVAILABLE",estimatedCalls:task.maxApiCalls,externalExecution:false};}
export function createHandoff({task,targetEmployeeId,fields,classification}){if(!task?.workspaceId||!EMPLOYEE_REGISTRY[task.aiEmployeeId]||!targetEmployeeId||!Array.isArray(fields)||!classification)return {ok:false,reasonCode:"HANDOFF_INVALID"};if(["confidential","restricted"].includes(classification))return {ok:false,reasonCode:"HANDOFF_APPROVAL_REQUIRED"};return {ok:true,handoff:{workspaceId:task.workspaceId,sourceEmployeeId:task.aiEmployeeId,targetEmployeeId,taskId:task.taskId,fields:[...fields],classification,status:"proposed",rawContentIncluded:false,externalExecution:false}};}
export function aggregatePartialResults(results=[]){const succeeded=results.filter(x=>x.status==="success"),failed=results.filter(x=>x.status!=="success");return {status:failed.length?(succeeded.length?"partial":"failed"):"completed",services:results,partial:failed.length>0,warnings:failed.map(x=>`${x.service}:${x.errorClass||"unavailable"}`),mock:true,externalExecution:false};}
export function buildEmployeeOutput(task,input={}){return {status:input.status||"dry_run_ready",maturity:EMPLOYEE_REGISTRY[task.aiEmployeeId]?.maturity||"Locked",sourceProvider:EMPLOYEE_REGISTRY[task.aiEmployeeId]?.provider||null,capability:task.capability,workspaceId:task.workspaceId,taskId:task.taskId,workflowId:task.workflowId,correlationId:task.correlationId,dataFreshness:input.dataFreshness||"not_fetched",sourceIdentifiers:[...(input.sourceIdentifiers||[])],resultSummary:input.resultSummary||"Dry Runのみ。外部データは取得していません。",structuredData:input.structuredData||{},warnings:[...(input.warnings||[])],missingPermissions:[...(input.missingPermissions||[])],missingScopes:[...(input.missingScopes||[])],ownerActionRequired:input.ownerActionRequired||null,approvalRequired:Boolean(input.approvalRequired),estimatedCostJpy:task.costCeilingJpy,actualCostJpy:0,apiQuotaImpact:Number(input.apiQuotaImpact||0),recordsProcessed:0,partial:false,mock:true,errorClassification:null,retryable:false,completedAt:null,externalExecution:false};}
export function validateEmployeeApproval(approval,task,now=Date.now()){const s=approval?.snapshot;return Boolean(approval?.status==="approved"&&approval.oneTimeUse===true&&approval.used!==true&&Date.parse(approval.expiresAt)>now&&s?.workspaceId===task.workspaceId&&s?.aiEmployeeId===task.aiEmployeeId&&s?.workflowId===task.workflowId&&s?.capability===task.capability&&s?.idempotencyKey===task.idempotencyKey&&s?.requestHash===approval.requestHash);}
