import {evaluateQuota,aggregatePartialResults} from "./aiEmployeePlatform.js";
export const GOOGLE_CAPABILITIES=Object.freeze({gmail_read:{service:"gmail",permission:"read",scope:"gmail.readonly",maturity:"Conditional",quota:5},gmail_draft:{service:"gmail",permission:"draft",scope:"gmail.compose",maturity:"Locked",quota:10},gmail_send:{service:"gmail",permission:"send",scope:"gmail.send",maturity:"Locked",approval:true,quota:100},drive_read:{service:"drive",permission:"read",scope:"drive.metadata.readonly",maturity:"Conditional",quota:10},drive_create:{service:"drive",permission:"create",scope:"drive.file",maturity:"Locked",approval:true,quota:20},calendar_read:{service:"calendar",permission:"read",scope:"calendar.readonly",maturity:"Conditional",quota:5},calendar_create:{service:"calendar",permission:"create",scope:"calendar.events",maturity:"Locked",approval:true,quota:20},analytics_read:{service:"analytics",permission:"read",scope:"analytics.readonly",maturity:"Conditional",quota:10},search_console_read:{service:"search_console",permission:"read",scope:"webmasters.readonly",maturity:"Conditional",quota:10},youtube_read:{service:"youtube",permission:"read",scope:"youtube.readonly",maturity:"Conditional",quota:5},youtube_publish:{service:"youtube",permission:"publish",scope:"youtube.upload",maturity:"Locked",approval:true,quota:1600}});
export const GOOGLE_WORKFLOWS=Object.freeze({daily_operations_brief:["gmail_read","calendar_read","drive_read","analytics_read","search_console_read","youtube_read"],meeting_preparation:["calendar_read","gmail_read","drive_read"],inbox_to_task:["gmail_read","drive_read","calendar_read"],content_performance:["analytics_read","search_console_read","youtube_read"],content_operations_preparation:["gmail_read","drive_read","analytics_read","search_console_read","youtube_read"],owner_request:[]});
export function evaluateGoogleCapability({capability,grantedScopes=[],connected=false,approval=null}){const c=GOOGLE_CAPABILITIES[capability];if(!c)return {ready:false,reasonCode:"CAPABILITY_UNKNOWN"};if(!connected)return {ready:false,reasonCode:"GOOGLE_CONNECTION_REQUIRED",maturity:c.maturity};if(!grantedScopes.includes(c.scope))return {ready:false,reasonCode:"GOOGLE_SCOPE_MISSING",missingScope:c.scope,maturity:c.maturity};if(c.maturity==="Locked")return {ready:false,reasonCode:"EXTERNAL_EXECUTION_LOCKED",approvalRequired:Boolean(c.approval),maturity:c.maturity};return {ready:true,reasonCode:"CAPABILITY_READY",maturity:c.maturity,externalExecution:false};}
export function buildGoogleDryRun(task,{workflow,grantedScopes=[],connected=false,usage={}}={}){const capabilities=GOOGLE_WORKFLOWS[workflow]||[task.capability],checks=capabilities.map(capability=>({capability,...evaluateGoogleCapability({capability,grantedScopes,connected})})),quota=evaluateQuota(task,usage);return {status:"dry_run_ready",intent:task.purpose,selectedWorkflow:workflow,selectedCapabilities:capabilities,requiredGoogleServices:[...new Set(capabilities.map(x=>GOOGLE_CAPABILITIES[x]?.service).filter(Boolean))],requiredScopes:[...new Set(capabilities.map(x=>GOOGLE_CAPABILITIES[x]?.scope).filter(Boolean))],grantedScopes:[...grantedScopes],missingScopes:[...new Set(checks.map(x=>x.missingScope).filter(Boolean))],requiredApprovals:capabilities.filter(x=>GOOGLE_CAPABILITIES[x]?.approval),estimatedGoogleApiCalls:task.maxApiCalls,estimatedGoogleQuota:capabilities.reduce((n,x)=>n+(GOOGLE_CAPABILITIES[x]?.quota||0),0),estimatedMaximumCostJpy:task.costCeilingJpy,dataClassification:task.dataClassification,expectedAuditEvents:["task_created","validation_result","dry_run","scope_check","permission_check","budget_check"],quota,blockReason:!connected?"GOOGLE_CONNECTION_REQUIRED":checks.find(x=>!x.ready)?.reasonCode||(!quota.allowed?quota.reasonCode:"EXTERNAL_EXECUTION_LOCKED"),ownerActions:!connected?["Google OAuth接続が必要です"]:[],mock:true,externalNetworkRequests:0,googleApiRequests:0,aiProviderRequests:0,tokenRefreshes:0,writes:0,sends:0,publishes:0,externalExecution:false};}
export const normalizeGmailMessage=(x={})=>({id:x.id||null,threadId:x.threadId||null,sender:String(x.sender||""),subject:String(x.subject||""),date:x.date||null,unread:Boolean(x.unread),attachmentMetadata:(x.attachments||[]).map(a=>({name:a.name,mimeType:a.mimeType,size:Number(a.size||0),sensitivity:"unknown"})),bodyStored:false,promptInjectionUntrusted:true});
export const normalizeDriveFile=(x={})=>({id:x.id||null,name:String(x.name||""),mimeType:x.mimeType||"application/octet-stream",modifiedTime:x.modifiedTime||null,revisionId:x.revisionId||null,size:Number(x.size||0),largeFile:Number(x.size||0)>10_000_000,bodyStored:false});
export function validateCalendarEvent(x={}){const errors=[];if(!x.timeZone)errors.push("timezone_required");if(!x.start||!x.end||Date.parse(x.end)<=Date.parse(x.start))errors.push("time_range_invalid");if(x.recurring&&!x.recurrenceScope)errors.push("recurrence_scope_required");return {valid:errors.length===0,errors,externalExecution:false};}
const ANALYTICS_DIMENSIONS=new Set(["date","country","deviceCategory","sessionSource"]),ANALYTICS_METRICS=new Set(["sessions","activeUsers","conversions","totalRevenue"]);
export function validateAnalyticsQuery(q={},binding={}){const errors=[];if(q.propertyId!==binding.propertyId)errors.push("property_mismatch");if((q.dimensions||[]).some(x=>!ANALYTICS_DIMENSIONS.has(x)))errors.push("dimension_not_allowed");if((q.metrics||[]).some(x=>!ANALYTICS_METRICS.has(x)))errors.push("metric_not_allowed");if(!Number.isInteger(q.limit)||q.limit<1||q.limit>1000)errors.push("row_limit_invalid");return {valid:errors.length===0,errors};}
export function validateSearchConsoleQuery(q={},binding={}){const allowed=new Set(["query","page","country","device","date"]),errors=[];if(q.siteUrl!==binding.siteUrl)errors.push("property_mismatch");if((q.dimensions||[]).some(x=>!allowed.has(x)))errors.push("dimension_not_allowed");if(!Number.isInteger(q.rowLimit)||q.rowLimit<1||q.rowLimit>1000)errors.push("row_limit_invalid");if(!q.startDate||!q.endDate||Date.parse(q.endDate)-Date.parse(q.startDate)>90*86400000)errors.push("date_range_invalid");return {valid:errors.length===0,errors};}
export function buildGoogleWorkflowResult(results){return {...aggregatePartialResults(results),sourceProvider:"google",employeeId:"google_operations",actualCostJpy:0,googleApiCalls:0};}
export function validateGmailSend(input={}){const recipients=[...(input.to||[]),...(input.cc||[]),...(input.bcc||[])],errors=[];if(recipients.length!==1)errors.push("mass_or_hidden_recipient_forbidden");if((input.bcc||[]).length)errors.push("bcc_forbidden");if(!input.approvalValid)errors.push("owner_approval_required");if(!input.recipientDomain||input.recipientDomain!==input.ownerDomain)errors.push("external_recipient_warning");return {allowed:false,errors,reasonCode:"EXTERNAL_EXECUTION_LOCKED",spoofCheckRequired:true,externalExecution:false};}
export function validateDriveMutation(input={}){const errors=[];if(!input.approvalValid)errors.push("owner_approval_required");if(input.size>10000000)errors.push("large_file_blocked");if(input.operation==="update"&&(!input.expectedRevisionId||input.expectedRevisionId!==input.currentRevisionId))errors.push("revision_mismatch");if(input.operation==="share")errors.push("sharing_locked");if(["confidential","restricted","unknown"].includes(input.classification))errors.push("data_transfer_blocked");return {allowed:false,errors,reasonCode:"EXTERNAL_EXECUTION_LOCKED",externalExecution:false};}
export function validateYouTubeMutation(input={}){const errors=[];if(input.channelId!==input.boundChannelId)errors.push("channel_mismatch");if(!input.approvalValid)errors.push("owner_approval_required");if(!input.visibility||!input.madeForKidsDecision)errors.push("publishing_metadata_required");if(input.duplicateFingerprint)errors.push("duplicate_upload_blocked");return {allowed:false,errors,quotaUnits:1600,reasonCode:"EXTERNAL_EXECUTION_LOCKED",externalExecution:false};}
