import { resolveMinorMoneyDisplay } from "../../../design-system/moneySemantics.js";

export const truthLabel=(value)=>({Actual:"実績",Forecast:"予測",Inference:"AI推論",Unknown:"未取得",Mock:"Mock",Test:"Test"}[value]||"未取得");
export const maturityLabel=(value)=>({Production:"Production",Conditional:"条件付き",Mock:"Mock",Locked:"ロック中"}[value]||"条件付き");
export const moneyLabel=(value,currency="JPY",kind="unknown",evidenceVerified=false)=>resolveMinorMoneyDisplay({value,currency,locale:"ja-JP",kind,evidenceVerified,unknownLabel:"Unknown"}).text;
const actualMetric=(value)=>({value:moneyLabel(value,"JPY","actual",Number.isFinite(value)),truth:Number.isFinite(value)?"Actual":"Unknown"});
export function commandCenterViewModel(data){const actual=data?.actualFinancials||{},availability=data?.availability||{},revenue=actualMetric(actual.actualRevenue),cost=actualMetric(actual.actualCost),profit=actualMetric(actual.netProfit),conversions=availability.performance?(data.performance||[]).reduce((sum,row)=>sum+Number(row.conversions||0),0):null;return Object.freeze({maturity:"Conditional",externalExecution:"LOCKED",programs:data?.programs||[],programsAvailable:availability.programs===true,alerts:(data?.alerts||[]).slice(0,5),brief:data?.dailyBrief||null,kpis:[{label:"Actual Revenue",...revenue},{label:"Actual Cost",...cost},{label:"Net Profit",...profit},{label:"Programs",value:availability.programs?(data?.programs?.length??0):null,truth:availability.programs?"Actual":"Unknown"},{label:"Publications",value:availability.publications?(data?.publications?.length??0):null,truth:availability.publications?"Actual":"Unknown"},{label:"Conversions",value:conversions,truth:Number.isFinite(conversions)?"Actual":"Unknown"}]});}
export function ownerDecisionViewModel(summary){const blocked=(summary?.risks||[]).find((x)=>x.classification==="BLOCKED");return Object.freeze({title:blocked?"リスク対応を確認":"次の施策を確認",reason:blocked?.rationale||"利用可能な情報を確認し、次の手動作業を決定してください。",evidenceStatus:blocked?"不足":"確認待ち",confidence:summary?.snapshots?.[0]?.confidence??null,risk:blocked?.classification||"Unknown",minutes:10,blockingItem:blocked?.title||null,canApprove:false,disabledReason:"Migration 015は未適用またはEvidenceが確認できないため、承認操作は利用できません。"});}
export const paletteCommands=(programId)=>[{id:"home",label:"Affiliate Command Center",path:"/affiliate-intelligence"},{id:"product",label:"商品インテリジェンス",path:`/affiliate-intelligence/${programId}/product`},{id:"strategy",label:"戦略と機会",path:`/affiliate-intelligence/${programId}/strategy`},{id:"content",label:"コンテンツ",path:`/affiliate-intelligence/${programId}/content`},{id:"graph",label:"インテリジェンスグラフ",path:`/affiliate-intelligence/${programId}/graph`},{id:"audit",label:"監査",path:`/affiliate-intelligence/${programId}/audit`}];
