import React from "react";
import {Badge} from "./Badge.jsx";import {Button} from "./Button.jsx";import {Card} from "./Card.jsx";import {Money} from "./Money.jsx";import {EmptyState} from "./States.jsx";

export function DataProvenance({source="Unknown",truthClass="unknown",freshness="Unknown"}){return <dl className="kv-provenance" aria-label="データ根拠"><div><dt>Source</dt><dd>{source}</dd></div><div><dt>Truth</dt><dd><Badge state={truthClass} /></dd></div><div><dt>Freshness</dt><dd>{freshness}</dd></div></dl>}
export function CompanyStateHero({state="unknown",title="会社状態は未確認です",reason="Canonical dataが不足しています。",source="Unknown",freshness="Unknown"}){return <Card variant="hero" className="kv-company-state"><div><p className="kv-eyebrow">COMPANY STATE</p><h2>{title}</h2><p>{reason}</p></div><Badge state={state}/><DataProvenance source={source} truthClass={state} freshness={freshness}/></Card>}
export function ProfitSummary({items=[],source="Unknown",freshness="Unknown"}){return <Card><h2>利益サマリー</h2>{items.length?<div className="kv-profit-summary">{items.map(item=><div key={item.currency}><span>{item.label||"純利益"}</span><Money value={item.value} currency={item.currency} kind={item.kind||"actual"} evidenceVerified={item.evidenceVerified===true} locale="ja-JP"/></div>)}</div>:<EmptyState title="利益はUnknownです" message="同一通貨・同一期間のVerified Actual RevenueとActual Costが揃っていません。"/>}<DataProvenance source={source} truthClass={items.length?"actual":"unknown"} freshness={freshness}/></Card>}
export function OwnerDecisionPanel({title,reason,impact="Unknown",deadline="Unknown",onAction,actionLabel="確認する"}){return <Card variant="decision"><p className="kv-eyebrow">NEXT OWNER ACTION</p><h2>{title||"判断事項はありません"}</h2>{reason?<p>{reason}</p>:null}<dl className="kv-decision-meta"><div><dt>利益影響</dt><dd>{impact}</dd></div><div><dt>期限</dt><dd>{deadline}</dd></div></dl>{onAction?<Button onClick={onAction}>{actionLabel}</Button>:null}</Card>}
export function RevenueEngineSummary({engines=[]}){return <Card><h2>Revenue Engine</h2>{engines.length?<ul className="kv-summary-list">{engines.map(engine=><li key={engine.id}><span>{engine.name}</span><Badge state={engine.state||"unknown"}/></li>)}</ul>:<EmptyState title="Revenue Engine分類はNot Implementedです" message="Canonical engine classificationがありません。"/>}</Card>}
export function WorkforceSummary({employees=[]}){return <Card><h2>AI組織</h2>{employees.length?<ul className="kv-summary-list">{employees.map(employee=><li key={employee.id}><span><strong>{employee.name}</strong><small>{employee.department} · {employee.responsibility}</small></span><Badge state={employee.state||"locked"}/></li>)}</ul>:<EmptyState title="AI組織データはありません" message="Migration 012適用前のためConditional / Lockedです。"/>}</Card>}
export function BottleneckList({items=[]}){return <Card><h2>ボトルネック</h2>{items.length?<ol className="kv-bottleneck-list">{items.map(item=><li key={item.id}><Badge state={item.state||"pending"}/><span><strong>{item.title}</strong>{item.reason?<small>{item.reason}</small>:null}</span></li>)}</ol>:<EmptyState title="確認可能なボトルネックはありません"/>}</Card>}
export function CostComposition({items=[],currency="JPY"}){return <Card><h2>コスト構成</h2>{items.length?<dl className="kv-cost-composition">{items.map(item=><div key={item.id}><dt>{item.label}</dt><dd><Money value={item.value} currency={currency} kind="actual" evidenceVerified={item.evidenceVerified===true} locale="ja-JP"/></dd></div>)}</dl>:<EmptyState title="コスト構成はUnknownです" message="Actual Costのcanonical categoryが不足しています。"/>}</Card>}
export function ResponsiveDetailDrawer({open=false,title="詳細",onClose,children}){if(!open)return null;return <div className="kv-detail-drawer" role="dialog" aria-modal="true" aria-labelledby="kv-detail-title"><button className="kv-detail-drawer__backdrop" aria-label="詳細を閉じる" onClick={onClose}/><section><header><h2 id="kv-detail-title">{title}</h2><Button variant="ghost" onClick={onClose} aria-label="詳細を閉じる">閉じる</Button></header>{children}</section></div>}
