import test from "node:test";
import assert from "node:assert/strict";
import { createAffiliateV2ProductRepository } from "../../src/repositories/affiliateV2ProductRepository.js";
import { createAffiliateV2IntelligenceRepository } from "../../src/repositories/affiliateV2IntelligenceRepository.js";
import { createAffiliateV2RiskRepository } from "../../src/repositories/affiliateV2RiskRepository.js";
import { createAffiliateV2BriefRepository } from "../../src/repositories/affiliateV2BriefRepository.js";
import { createAffiliateV2SnapshotService } from "../../src/services/affiliateV2SnapshotService.js";
import { createAffiliateV2CommandCenterService } from "../../src/services/affiliateV2CommandCenterService.js";
function fixture(tables={},rpcResult={data:"snapshot-1",error:null},tableErrors={}){const calls=[];return{calls,from(table){const s={table,filters:[],columns:null,order:null,limit:null};calls.push(s);const q={select(v){s.columns=v;return q;},eq(k,v){s.filters.push([k,v]);return q;},order(k,o){s.order=[k,o];return q;},limit(v){s.limit=v;return q;},then(resolve){let rows=[...(tables[table]||[])];for(const [k,v]of s.filters)rows=rows.filter((x)=>x[k]===v);return Promise.resolve({data:rows.slice(0,s.limit||rows.length),error:tableErrors[table]||null}).then(resolve);}};return q;},rpc(name,args){calls.push({rpc:name,args});return Promise.resolve(rpcResult);}};}
const dates={created_at:"2026-08-05T00:00:00Z",updated_at:"2026-08-05T00:00:00Z",archived_at:null};
test("products and sources are exact, bounded, Workspace scoped",async()=>{const c=fixture({affiliate_products:[{id:"p",workspace_id:"w",affiliate_program_id:"ap",name:"RingConn",lifecycle_status:"active",truth_class:"Unknown",safe_metadata:{},...dates}],affiliate_product_sources:[{id:"ps",workspace_id:"w",product_id:"p",source_type:"owner_input",source_reference:"owner",attribution:"Owner",lifecycle_status:"active",...dates}]});const r=createAffiliateV2ProductRepository(c);assert.equal((await r.listProducts("w"))[0].name,"RingConn");assert.equal((await r.getProductSources("w","p"))[0].sourceReference,"owner");assert.ok(c.calls.every((x)=>!x.columns?.includes("*")));assert.ok(c.calls.every((x)=>x.filters?.some(([k,v])=>k==="workspace_id"&&v==="w")));});
test("latest snapshot orders version deterministically",async()=>{const c=fixture({affiliate_intelligence_snapshots:[{id:"s",workspace_id:"w",affiliate_program_id:"ap",snapshot_type:"forecast",version:2,lifecycle_status:"draft",truth_class:"Forecast",generated_at:"2026-08-05",source_reference:"canonical",assumptions:["stable"],confidence:.5,model_version:"v2",payload:{expected:1},...dates}]});assert.equal((await createAffiliateV2IntelligenceRepository(c).getLatestSnapshot("w","ap","forecast")).version,2);assert.deepEqual(c.calls[0].order,["version",{ascending:false}]);assert.equal(c.calls[0].limit,1);});
test("risk, alert, and brief reads remain scoped",async()=>{const c=fixture({affiliate_risk_findings:[{id:"r",workspace_id:"w",affiliate_program_id:"ap",finding_type:"disclosure",classification:"BLOCKED",title:"Missing",rationale:"Required",lifecycle_status:"open",...dates}],affiliate_alerts:[{id:"a",workspace_id:"w",affiliate_program_id:"ap",severity:"Critical",alert_code:"DISCLOSURE_MISSING",summary:"Missing",lifecycle_status:"open",detected_at:"2026-08-05",...dates}],affiliate_daily_briefs:[{id:"b",workspace_id:"w",brief_date:"2026-08-05",rule_version:"v2",action_count:1,decision_ids:[],summary:{actions:[]},truth_class:"Inference",generated_at:"2026-08-05",lifecycle_status:"active",...dates}]});assert.equal(await createAffiliateV2RiskRepository(c).getOpenCriticalRiskCount("w","ap"),1);assert.equal((await createAffiliateV2RiskRepository(c).getCriticalAlerts("w")).length,1);assert.equal((await createAffiliateV2BriefRepository(c).getLatestDailyBrief("w")).actionCount,1);});
test("snapshot uses exact RPC args, idempotency, rejects Actual",async()=>{const c=fixture(),s=createAffiliateV2SnapshotService(c),input={workspaceId:"w",programId:"ap",snapshotType:"forecast",idempotencyKey:"snapshot:key",payload:{truthClass:"Forecast",generatedAt:"2026-08-05",sourceReference:"canonical",assumptions:["stable"],confidence:.5,modelVersion:"v2",payload:{expected:1}}};assert.equal((await s.saveAffiliateIntelligenceSnapshot(input)).auditEvent,"affiliate_intelligence_snapshot_saved");const call=c.calls.find((x)=>x.rpc);assert.equal(call.rpc,"save_affiliate_intelligence_snapshot");assert.deepEqual(Object.keys(call.args),["p_affiliate_program_id","p_snapshot_type","p_truth_class","p_input","p_idempotency_key"]);await assert.rejects(s.saveAffiliateIntelligenceSnapshot({...input,payload:{...input.payload,truthClass:"Actual"}}),(e)=>e.code==="VALIDATION_FAILED");});
test("command center Actuals only use canonical tables",async()=>{const c=fixture({affiliate_programs:[{id:"ap",workspace_id:"w",offer_id:"o",program_name:"RingConn",status:"active",risk_level:"low",truth_class:"Unknown",updated_at:"2026-08-05"}],affiliate_performance_records:[{id:"pf",workspace_id:"w",affiliate_program_id:"ap",clicks:10,conversions:2,truth_class:"Actual",period_end:"2026-08-05"}],revenue_records:[{id:"rev",workspace_id:"w",gross_amount_minor:1000,cost_amount_minor:100,net_amount_minor:900,campaign_id:"campaign-1",recognized_at:"2026-08-05"}],operating_cost_records:[{id:"cost",workspace_id:"w",amount_minor:200,value_type:"actual",campaign_id:"campaign-1",occurred_at:"2026-08-05"}],affiliate_alerts:[],affiliate_daily_briefs:[]});const v=await createAffiliateV2CommandCenterService(c).getAffiliateCommandCenter("w");assert.deepEqual([v.kpis.actualRevenue,v.kpis.actualCost,v.kpis.netProfit],[1000,200,700]);assert.deepEqual(v.actualFinancials,{actualRevenue:1000,actualCost:200,netProfit:800,roi:4,truthClass:"Actual"});assert.deepEqual(v.actualSource,{revenue:"revenue_records",cost:"operating_cost_records"});assert.equal(v.externalExecution,"LOCKED");const revenueCall=c.calls.find((x)=>x.table==="revenue_records"),costCall=c.calls.find((x)=>x.table==="operating_cost_records");for(const field of ["gross_amount_minor","cost_amount_minor","net_amount_minor","recognized_at"])assert.ok(revenueCall.columns.split(",").includes(field));for(const field of ["amount_minor","truth_class","recorded_at"])assert.equal(revenueCall.columns.split(",").includes(field),false);assert.deepEqual(revenueCall.order,["recognized_at",{ascending:false}]);for(const field of ["amount_minor","value_type","campaign_id","occurred_at"])assert.ok(costCall.columns.split(",").includes(field));for(const field of ["truth_class","operation_id","recorded_at"])assert.equal(costCall.columns.split(",").includes(field),false);assert.deepEqual(costCall.order,["occurred_at",{ascending:false}]);const unknown=await createAffiliateV2CommandCenterService(fixture({affiliate_programs:[],affiliate_performance_records:[],revenue_records:[],operating_cost_records:[],affiliate_alerts:[],affiliate_daily_briefs:[]})).getAffiliateCommandCenter("w");assert.deepEqual(unknown.actualFinancials,{actualRevenue:"Unknown",actualCost:"Unknown",netProfit:"Unknown",roi:"Unknown",truthClass:"Unknown"});assert.equal(unknown.externalExecution,"LOCKED");});
test("command center preserves an empty Affiliate page when protected Actual reads are unavailable",async()=>{const c=fixture({affiliate_programs:[],affiliate_performance_records:[],affiliate_alerts:[],affiliate_daily_briefs:[]},{data:null,error:null},{revenue_records:{code:"42501",message:"permission denied"},operating_cost_records:{code:"42501",message:"permission denied"}});const value=await createAffiliateV2CommandCenterService(c).getAffiliateCommandCenter("w");assert.deepEqual(value.programs,[]);assert.deepEqual(value.actualFinancials,{actualRevenue:"Unknown",actualCost:"Unknown",netProfit:"Unknown",roi:"Unknown",truthClass:"Unknown"});assert.deepEqual(value.actualAvailability,{revenue:"unavailable",cost:"unavailable"});assert.equal(value.externalExecution,"LOCKED");});
test("RingConn remains retrieval-only",()=>{const r=createAffiliateV2ProductRepository(fixture());assert.equal(typeof r.listProducts,"function");for(const key of ["insert","update","delete"])assert.equal(key in r,false);});
