import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createAffiliateProgramMasterRepository } from "../../src/repositories/affiliateProgramMasterRepository.js";

const migration=readFileSync(new URL("../../supabase/migrations/017_affiliate_program_master.sql",import.meta.url),"utf8");
test("Migration 017 registers exactly 11 canonical A8 program IDs idempotently",()=>{const ids=[...migration.matchAll(/'A8\.net','(s\d+)'/g)].map((match)=>match[1]);assert.equal(ids.length,11);assert.equal(new Set(ids).size,11);assert.match(migration,/unique\(workspace_id,asp_name,program_id\)/);assert.match(migration,/on conflict\(workspace_id,asp_name,program_id\) do nothing/);});
test("Migration 017 preserves critical listing compliance evidence",()=>{assert.match(migration,/array\['SAZO','sazo','サゾ'\]/);for(const word of ['社名','サービス名','商品名','表記ゆれ','aiボイスレコーダー','文字起こし','書き起こし','議事録','音声要約','aiガジェット','aiマイク'])assert.ok(migration.includes(word));assert.match(migration,/GMOペパボ等の商標・サービス名関連ワード/);for(const id of ['s00000027395002','s00000025109003']){const start=migration.indexOf(`'A8.net','${id}'`),end=migration.indexOf("),\n",start);const record=migration.slice(start,end);assert.match(record,/,null,null,'NOT_CONFIRMED'/);}});
test("Migration 017 is owner-only, audited, and cannot create financial truth",()=>{assert.match(migration,/workspace_owner_access_denied/);assert.match(migration,/affiliate_program_link_updated/);assert.match(migration,/external_execution_allowed boolean not null default false/);assert.doesNotMatch(migration,/insert into public\.(revenue_records|operating_cost_records|affiliate_performance_records)/);assert.match(migration,/revoke all on table public\.affiliate_program_master from public,anon,authenticated/);});
test("repository scopes reads and uses protected link/update RPCs",async()=>{const calls=[];const client={from(table){const q={select(columns){calls.push({table,columns,filters:[]});q.call=calls.at(-1);return q},eq(k,v){q.call.filters.push([k,v]);return q},order(){return q},limit(){return Promise.resolve({data:[],error:null})}};return q},rpc(name,args){calls.push({name,args});return Promise.resolve({data:"id",error:null})}};const repository=createAffiliateProgramMasterRepository(client);await repository.listPrograms("w");await repository.saveAffiliateLink("w","id",{affiliateUrl:"https://example.com",linkStatus:"ACTIVE"});await repository.updateProgram("id",{expectedUpdatedAt:"2026-08-20T00:00:00Z",changes:{programStatus:"PAUSED"}});assert.deepEqual(calls[0].filters,[["workspace_id","w"]]);assert.equal(calls[1].name,"save_affiliate_program_master_link");assert.equal(calls[2].name,"update_affiliate_program_master");assert.deepEqual(calls[2].args,{p_program_master_id:"id",p_expected_updated_at:"2026-08-20T00:00:00.000Z",p_changes:{program_status:"PAUSED"}});});
test("M030 mutation RPCs preserve Postgres microsecond concurrency snapshots",async()=>{const calls=[];const client={from(){},rpc(name,args){calls.push({name,args});return Promise.resolve({data:[{deleted:true}],error:null})}};const repository=createAffiliateProgramMasterRepository(client),stamp="2026-08-20T00:00:00.123456+00:00";await repository.updatePractical("program-id",{expectedUpdatedAt:stamp,expectedBusinessVersion:1,changes:{rewardSummary:"exact"}});await repository.deleteIfSafe("program-id",{expectedUpdatedAt:stamp,expectedBusinessVersion:2,idempotencyKey:"affiliate:delete:exact"});assert.equal(calls[0].args.p_expected_updated_at,stamp);assert.equal(calls[1].args.p_expected_updated_at,stamp);});
