import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
const sql=await fs.readFile("supabase/migrations/032_affiliate_revenue_cycle.sql","utf8");
test("M032 is additive and creates no synthetic business object",()=>{for(const value of["affiliate_cycle_publications","affiliate_cycle_performance","affiliate_revenue_candidates","affiliate_revenue_evidence","affiliate_actual_revenue_extensions"])assert.ok(sql.includes(value),value);for(const denied of[/insert into public\.opportunities/i,/insert into public\.campaigns/i,/insert into public\.tasks/i,/insert into public\.affiliate_strategies/i])assert.doesNotMatch(sql,denied)});
test("M032 adds an Affiliate Actual subtype behind verified evidence",()=>{assert.match(sql,/affiliate_actual_revenue_extensions/);assert.match(sql,/verification_status='VERIFIED'/);assert.match(sql,/reward_state='CONFIRMED'/);assert.match(sql,/status='CANDIDATE'/);assert.match(sql,/unique\(candidate_id\)/);assert.match(sql,/on conflict\(candidate_id\) do nothing/)});
test("M032 never weakens or replaces existing schema",()=>{for(const denied of[/drop\s+trigger/i,/drop\s+column/i,/drop\s+not\s+null/i,/alter\s+table\s+public\.revenue_records/i,/insert\s+into\s+public\.revenue_records/i])assert.doesNotMatch(sql,denied)});
test("M032 is owner-private, optimistic, idempotent and externally locked",()=>{assert.equal((sql.match(/force row level security/g)||[]).length,1);for(const value of["resolve_personal_workspace()","p_expected_version","idempotency_key","external_execution","LOCKED","revoke all","grant execute"])assert.ok(sql.toLowerCase().includes(value.toLowerCase()),value);assert.doesNotMatch(sql,/grant (insert|update|delete) on public\.affiliate_/i)});
test("M032 emits sanitized timeline and audit metadata",()=>{assert.match(sql,/insert into public\.operational_activity_events/);assert.match(sql,/insert into public\.audit_logs/);assert.match(sql,/metadata_sanitized/);});
