import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const sql=readFileSync(new URL("../../docs/database/m028/028_full_operational_completion.sql",import.meta.url),"utf8");
const rollback=readFileSync(new URL("../../docs/database/m028/028_rollback.sql",import.meta.url),"utf8");
const snapshot=readFileSync(new URL("../../docs/database/m028/028_preflight_and_scoped_snapshot.sql",import.meta.url),"utf8");
const security=readFileSync(new URL("../../docs/database/m028/028_security_test_plan.sql",import.meta.url),"utf8");
const exportSql=readFileSync(new URL("../../docs/database/m028/028_freeze_export_before_rollback.sql",import.meta.url),"utf8");
const reimportSql=readFileSync(new URL("../../docs/database/m028/028_reimport_after_reapply.sql",import.meta.url),"utf8");
const recoveryVerification=readFileSync(new URL("../../docs/database/m028/028_recovery_verification.sql",import.meta.url),"utf8");
const namespaceAudit=readFileSync(new URL("../../docs/database/m028/028_namespace_compatibility_audit.sql",import.meta.url),"utf8");

test("M028 is one additive transaction and preserves M001-M027 truth",()=>{assert.match(sql,/^begin;/m);assert.match(sql,/commit;\s*$/);assert.doesNotMatch(sql,/drop table public\.(revenue_records|evidence_candidates|affiliate_program_master|ai_conversation_threads)/);assert.doesNotMatch(sql,/insert into public\.(revenue_records|evidence_candidates)/)});
test("M028 creates eight force-RLS private tables with browser read only",()=>{for(const table of["operational_objects","operational_object_drafts","operational_object_links","operational_activity_events","research_sources","research_findings","internal_action_records","provider_free_quota_states"]){assert.match(sql,new RegExp(`create table public\\.${table}\\(`));assert.match(sql,new RegExp(`alter table public\\.${table} force row level security`))}assert.match(sql,/revoke all on table[\s\S]*from public,anon,authenticated/)});
test("M028 structurally denies paid unknown and external execution",()=>{assert.match(sql,/paid_cost_jpy numeric\(12,4\) not null default 0 check\(paid_cost_jpy=0\)/);assert.match(sql,/external_execution boolean not null default false check\(external_execution=false\)/);assert.match(sql,/paid_fallback boolean not null default false check\(paid_fallback=false\)/);assert.match(sql,/p_cost_class in\('PAID','UNKNOWN'\)/)});
test("M028 supports optimistic drafts links research actions and memory hygiene",()=>{for(const value of["operational_object_stale_or_not_found","operational_draft_stale_or_not_found","link_operational_objects","research_findings_supersedes_fk","prepare_internal_action","set_ai_memory_owner_state"])assert.ok(sql.includes(value))});
test("M028 rollback is bounded to M028 and three additive memory columns",()=>{assert.match(rollback,/drop table if exists public\.operational_objects/);assert.match(rollback,/drop column if exists pinned_at/);assert.doesNotMatch(rollback,/drop table if exists public\.(revenue_records|affiliate_program_master|ai_memory_records)/)});
test("M028 scoped recovery stores metadata hashes only and is not browser exposed",()=>{const executable=snapshot.replace(/^--.*$/gm,"");assert.match(executable,/create schema m028_recovery authorization postgres/);assert.match(executable,/revoke all on all tables in schema m028_recovery from public, anon, authenticated, service_role/);assert.doesNotMatch(executable,/content_text|provenance|audit_metadata|revenue_records|affiliate_program_master/)});
test("M028 does not become a second canonical business database",()=>{assert.match(sql,/object_type text not null check\(object_type in\('RESEARCH_PACKAGE','QUICK_CAPTURE'\)\)/);assert.match(sql,/create function public\.m028_reference_exists/);for(const table of["campaigns","owner_decisions","tasks","opportunities","clients","personal_operational_records","content_assets","business_memory_records","research_findings"])assert.match(sql,new RegExp(`from public\\.${table}`))});
test("M028 links actions findings and timeline are idempotent",()=>{assert.match(sql,/unique\(owner_user_id,idempotency_key\)/);assert.match(sql,/on conflict\(owner_user_id,idempotency_key\)/);assert.match(security,/duplicate_link_event/);assert.match(security,/duplicate_action_created/)});
test("M028 executable suite attacks privacy grants costs secrets and stale writes",()=>{for(const value of["cross_user_object_leak","admin_private_leak","cross_workspace_link_allowed","browser_dml_grant_exposed","service_rpc_allowed","paid_source_allowed","unknown_source_allowed","secret_allowed","stale_object_allowed","stale_draft_allowed"])assert.ok(security.includes(value))});
test("M028 post-use recovery freezes writes and exports accepted data",()=>{assert.match(exportSql,/revoke execute on function public\.save_operational_object/);assert.match(exportSql,/create schema m028_postuse_recovery authorization postgres/);assert.match(exportSql,/revoke all on all tables in schema m028_postuse_recovery/)});
test("M028 reimport restores the timeline identity sequence",()=>{assert.match(reimportSql,/setval\(pg_get_serial_sequence\('public\.operational_activity_events','id'\)/)});
test("M028 pgcrypto dependencies are schema-qualified for Production",()=>{const packageSql=[sql,snapshot,recoveryVerification,security,namespaceAudit].join("\n");assert.doesNotMatch(packageSql,/(?<![.])\b(?:digest|gen_random_uuid|crypt|gen_salt|hmac|encrypt|decrypt|pgp_[a-z_]+)\s*\(/);assert.match(snapshot,/extensions\.digest\(/);assert.match(sql,/extensions\.gen_random_uuid\(\)/);assert.match(namespaceAudit,/set local search_path = pg_catalog, public/)});
test("M028 namespace audit probes the exact extensions functions",()=>{assert.match(namespaceAudit,/to_regprocedure\('extensions\.digest\(text,text\)'\)/);assert.match(namespaceAudit,/to_regprocedure\('extensions\.gen_random_uuid\(\)'\)/);assert.match(namespaceAudit,/M028_NAMESPACE_COMPATIBILITY_PASS/)});
