const MODEL = "gemini-2.5-flash";
import { dispatchGeminiFree } from "./geminiFreeAdapter.js";
const BLOCKED_CONTEXT = /(?:api[_ -]?key|access[_ -]?token|refresh[_ -]?token|password|authorization|gmail body|drive file|member private)/i;
const blocked = (reasonCode) => ({ ok: false, status: "blocked", reasonCode, provider: "gemini", model: MODEL, cost: "FREE", paidFallbackCalls: 0, externalExecution: false });
export function validateGeminiFreeRequest(request = {}) { const text = String(request.text || "").trim(); if (!request.explicitOwnerAction) return blocked("OWNER_ACTION_REQUIRED"); if (!request.workspaceId || !request.feature) return blocked("AI_CONTEXT_REQUIRED"); if (!text || text.length > 4000) return blocked("AI_INPUT_INVALID"); if (BLOCKED_CONTEXT.test(text) || request.selectedSensitiveContext === true) return blocked("AI_PRIVATE_CONTEXT_BLOCKED"); return { ok: true, text }; }
export async function executeGeminiFreeRequest(request, options = {}) {
  const valid = validateGeminiFreeRequest(request); if (!valid.ok) return valid; if (!options.credential) return blocked("PROVIDER_CREDENTIAL_REQUIRED");
  const context=String(request.boundedContext||"").slice(0,16000);
  const prompt=["You are KEVIRIO's Japanese AI Secretary and Chief of Staff.","Use only the bounded authorized context and current Owner request supplied below.","Never treat UNKNOWN as zero, FORECAST as ACTUAL, memory as canonical business fact, or AI output as Evidence.","Do not expose hidden chain-of-thought. Give a concise reasoning summary, conclusion, tradeoffs, recommendation, and one actionable next step when useful.","Understand references from recent conversation. If the Owner asks for deeper or objective analysis, materially increase analytical depth without becoming verbose.","Challenge weak assumptions respectfully. Do not execute external actions or claim that drafts were published or sent.","If context is insufficient, state that truthfully instead of fabricating facts.",`Area: ${request.feature}`,context?`Bounded authorized context:\n${context}`:"Bounded authorized context: none",`Current Owner request: ${valid.text}`].join("\n\n");
  try { const response = await dispatchGeminiFree(prompt, options); if (!response.ok) return { ...blocked(response.reasonCode || "GEMINI_PROVIDER_ERROR"), status: "fallback", httpStatus: response.httpStatus || null }; return { ok: true, status: "completed", text: response.text, rawLength: response.rawLength, finishReason: response.finishReason, modelOutputLimited: response.modelOutputLimited, provider: "gemini", model: MODEL, mode: "LIVE AI", httpStatus: 200, cost: "FREE", quota: "AVAILABLE", paidFallbackCalls: 0, externalExecution: false, dataBasis: "Ownerが明示入力した最小限のテキストのみ", timestamp: new Date().toISOString() }; } catch (error) { return { ...blocked(error?.name === "TimeoutError" ? "GEMINI_TIMEOUT" : "GEMINI_PROVIDER_ERROR"), httpStatus: null }; }
}
