import { createOAuthCipher,createOAuthIntent,hashOAuthState } from "./oauthRuntime.js";
const blocked=(reasonCode)=>({ok:false,status:"blocked",reasonCode,externalExecution:false});
export function createProviderConnectionRuntime({client,encryptionKey,allowedRedirectUris=[]}={}){
  let cipher;try{cipher=createOAuthCipher(encryptionKey);}catch{return {available:false,beginOAuth:async()=>blocked("OAUTH_ENCRYPTION_KEY_REQUIRED"),completeOAuth:async()=>blocked("OAUTH_ENCRYPTION_KEY_REQUIRED")};}
  return {available:true,
    async beginOAuth(input){if(!client?.from||!allowedRedirectUris.includes(input.redirectUri))return blocked("OAUTH_REDIRECT_NOT_ALLOWED");let intent;try{intent=createOAuthIntent(input);}catch{return blocked("OAUTH_INTENT_INVALID");}const {error}=await client.from("provider_oauth_states").insert({workspace_id:intent.workspaceId,owner_id:intent.ownerId,provider:intent.provider,state_hash:intent.stateHash,pkce_verifier_ciphertext:cipher.encrypt(intent.pkceVerifier),redirect_uri:intent.redirectUri,requested_scopes:intent.scopes,expires_at:intent.expiresAt});if(error)return blocked("OAUTH_STATE_PERSIST_FAILED");return {ok:true,status:"authorization_pending",authorization:{state:intent.state,pkceChallenge:intent.pkceChallenge,scopes:intent.scopes,redirectUri:intent.redirectUri},externalExecution:false};},
    async completeOAuth(input){if(typeof input.exchangeCode!=="function"||!input.state||!input.code)return blocked("OAUTH_EXCHANGE_UNAVAILABLE");const consumed=await client.rpc("consume_provider_oauth_state",{p_state_hash:hashOAuthState(input.state),p_workspace_id:input.workspaceId,p_owner_id:input.ownerId,p_provider:input.provider,p_redirect_uri:input.redirectUri});if(consumed.error)return blocked("OAUTH_STATE_REPLAY_OR_INVALID");let token;try{token=await input.exchangeCode({code:input.code,verifier:cipher.decrypt(consumed.data.pkceVerifierCiphertext),redirectUri:input.redirectUri});}catch{return blocked("OAUTH_TOKEN_EXCHANGE_FAILED");}if(!token?.accessToken)return blocked("OAUTH_TOKEN_RESPONSE_INVALID");const row={workspace_id:input.workspaceId,provider:input.provider,connection_type:"oauth",state:"connected",provider_account_id:token.accountId||null,provider_account_label:token.accountLabel||null,token_ciphertext:cipher.encrypt(token.accessToken),refresh_token_ciphertext:token.refreshToken?cipher.encrypt(token.refreshToken):null,token_expires_at:token.expiresAt||null,token_type:token.tokenType||null,granted_scopes:token.scopes||[],created_by:input.ownerId,updated_at:new Date().toISOString()};const {error}=await client.from("provider_connections").upsert(row,{onConflict:"workspace_id,provider"});if(error)return blocked("OAUTH_CONNECTION_PERSIST_FAILED");return {ok:true,status:token.refreshToken?"connected":"connected_scope_limited",provider:input.provider,grantedScopes:[...(token.scopes||[])],externalExecution:false};},
    async refresh(input){if(typeof input.refreshToken!=="function")return blocked("OAUTH_REFRESH_UNAVAILABLE");const result=await client.from("provider_connections").select("refresh_token_ciphertext").eq("workspace_id",input.workspaceId).eq("provider",input.provider).maybeSingle();if(result.error||!result.data?.refresh_token_ciphertext)return blocked("OAUTH_REFRESH_TOKEN_MISSING");let token;try{token=await input.refreshToken({refreshToken:cipher.decrypt(result.data.refresh_token_ciphertext)});}catch{await client.from("provider_connections").update({state:"refresh_failed",updated_at:new Date().toISOString()}).eq("workspace_id",input.workspaceId).eq("provider",input.provider);return blocked("OAUTH_REFRESH_FAILED");}if(!token?.accessToken)return blocked("OAUTH_TOKEN_RESPONSE_INVALID");const updated=await client.from("provider_connections").update({token_ciphertext:cipher.encrypt(token.accessToken),refresh_token_ciphertext:token.refreshToken?cipher.encrypt(token.refreshToken):result.data.refresh_token_ciphertext,token_expires_at:token.expiresAt||null,state:"connected",updated_at:new Date().toISOString()}).eq("workspace_id",input.workspaceId).eq("provider",input.provider);return updated.error?blocked("OAUTH_CONNECTION_PERSIST_FAILED"):{ok:true,status:"connected",externalExecution:false};},
    async disconnect(input){const result=await client.rpc("disconnect_provider_connection",{p_workspace_id:input.workspaceId,p_provider:input.provider,p_owner_id:input.ownerId});return result.error?blocked("OAUTH_DISCONNECT_FAILED"):{ok:true,status:"disconnected",externalExecution:false};},
    async revoke(input){if(typeof input.revokeToken!=="function"||input.ownerConfirmed!==true)return blocked("OWNER_CONFIRMATION_REQUIRED");const result=await client.from("provider_connections").select("token_ciphertext").eq("workspace_id",input.workspaceId).eq("provider",input.provider).maybeSingle();if(result.error||!result.data?.token_ciphertext)return blocked("OAUTH_TOKEN_MISSING");try{await input.revokeToken({accessToken:cipher.decrypt(result.data.token_ciphertext)});}catch{return blocked("OAUTH_REVOKE_FAILED");}return this.disconnect(input);}
  };
}
