function fail(code){throw Object.assign(new Error(code),{reasonCode:code});}
export function createSupabaseProviderRuntimeStore(client, context = {}) {
  if (!client?.rpc || !client?.from || !context.workspaceId || !context.ownerId) return null;
  const workspaceId=context.workspaceId;
  return {
    async getRuntimeContext(request){if(request.workspaceId!==workspaceId)fail("WORKSPACE_MISMATCH");const [policy,usage,reservations,circuit]=await Promise.all([client.from("provider_cost_policies").select("*").eq("workspace_id",workspaceId).eq("provider",request.provider).maybeSingle(),client.from("provider_usage_ledger").select("actual_cost_jpy,created_at,status").eq("workspace_id",workspaceId).eq("provider",request.provider),client.from("provider_budget_reservations").select("reserved_cost_jpy,status,expires_at").eq("workspace_id",workspaceId).eq("provider",request.provider),client.from("provider_circuit_breakers").select("state,consecutive_failures").eq("workspace_id",workspaceId).eq("provider",request.provider).maybeSingle()]);if([policy,usage,reservations,circuit].some(x=>x.error)||!policy.data)fail("USAGE_UNAVAILABLE");const now=Date.now(),rows=usage.data||[],active=(reservations.data||[]).filter(x=>x.status==="reserved"&&Date.parse(x.expires_at)>now);const sumSince=(ms)=>rows.filter(x=>x.status==="completed"&&Date.parse(x.created_at)>=now-ms).reduce((n,x)=>n+Number(x.actual_cost_jpy||0),0);const reserved=active.reduce((n,x)=>n+Number(x.reserved_cost_jpy||0),0),p=policy.data;return {policy:{currency:"JPY",maxCostPerRequest:Number(p.max_cost_per_request_jpy),hourlyBudget:Number(p.hourly_budget_jpy),dailyBudget:Number(p.daily_budget_jpy),monthlyBudget:Number(p.monthly_budget_jpy),maxInputTokens:Number(p.max_input_tokens),maxOutputTokens:Number(p.max_output_tokens),maxTotalTokens:Number(p.max_total_tokens),maxRequestsPerJob:Number(p.max_requests_per_job),maxRequestsPerWorkflow:Number(p.max_requests_per_workflow),concurrency:Number(p.concurrency_limit),batchEnabled:false,autonomousLoopEnabled:false,maxRetries:Number(p.max_retries),globalExecutionEnabled:p.global_execution_enabled===true,providerExecutionEnabled:{[request.provider]:p.provider_execution_enabled===true},valid:true},usageAvailable:true,ledgerAvailable:true,inFlight:active.length,spent:{hourly:sumSince(3600000),daily:sumSince(86400000),monthly:sumSince(2678400000)},reserved:{hourly:reserved,daily:reserved,monthly:reserved},workflowBudgetJpy:Number(p.workflow_budget_jpy),aiEmployeeBudgetJpy:Number(p.ai_employee_budget_jpy),workspaceBudgetJpy:Number(p.workspace_budget_jpy),circuitOpen:circuit.data?.state==="open"};},
    async reserve({request,decision}){const {data,error}=await client.rpc("reserve_provider_budget",{p_workspace_id:workspaceId,p_workflow_id:request.workflowId,p_ai_employee_id:request.aiEmployeeId,p_provider:request.provider,p_model:request.model,p_idempotency_key:request.idempotencyKey,p_estimated_input_tokens:request.estimatedInputTokens,p_estimated_output_tokens:request.maxOutputTokens,p_estimated_cost_jpy:decision.reservedCostJpy,p_approval_id:request.approval?.id||null});if(error)fail("RESERVATION_FAILED");return data;},
    async appendLedger(row){const {error}=await client.from("provider_usage_ledger").insert({workspace_id:workspaceId,workflow_id:row.workflowId,ai_employee_id:row.aiEmployeeId,provider:row.provider,model:row.model,request_class:row.requestClass||"generation",purpose:row.purpose||"unspecified",idempotency_key:row.idempotencyKey,prompt_version:row.promptVersion,prompt_hash:row.promptHash,estimated_input_tokens:row.estimatedInputTokens,estimated_output_tokens:row.estimatedOutputTokens,reserved_cost_jpy:row.reservedCostJpy,estimated_cost_jpy:row.reservedCostJpy,actual_input_tokens:row.actualInputTokens,actual_output_tokens:row.actualOutputTokens,actual_cost_jpy:row.actualCostJpy,status:row.status,error_class:row.errorClass,approval_id:row.approvalId,retry_count:row.retryCount||0});if(error)fail("LEDGER_WRITE_FAILED");},
    async finalize({reservation,result}){const {error}=await client.rpc("finalize_provider_budget",{p_reservation_id:reservation.reservationId,p_actual_cost_jpy:Number(result?.cost?.actualJpy||0),p_status:result?.ok?"committed":"failed"});if(error)fail("FINALIZE_FAILED");},
    async release(reservation){const {error}=await client.rpc("release_provider_budget",{p_reservation_id:reservation.reservationId});if(error)fail("RELEASE_FAILED");},
    async fail({reservation}){return this.finalize({reservation,result:{ok:false,cost:{actualJpy:0}}});},
    async recordBlocked(event){await client.from("provider_execution_events").insert({workspace_id:workspaceId,provider:event.request.provider,workflow_id:event.request.workflowId,event_type:"blocked",reason_code:event.reasonCode,metadata:{requestClass:event.request.requestClass||null}});}
  };
}
