const required=client=>{if(!client?.from||!client?.rpc)throw new Error("SUPABASE_CLIENT_REQUIRED");return client};
const fail=(result)=>{if(result.error)throw result.error;return result.data};
export async function loadAffiliateRevenueCycle(client,{programId}){const db=required(client);const [publications,performance,candidates,evidence,revenue]=await Promise.all([
 db.from("affiliate_cycle_publications").select("*").eq("affiliate_program_id",programId).order("created_at",{ascending:false}),
 db.from("affiliate_cycle_performance").select("*").eq("affiliate_program_id",programId).order("observed_at",{ascending:false}),
 db.from("affiliate_revenue_candidates").select("*").eq("affiliate_program_id",programId).order("created_at",{ascending:false}),
 db.from("affiliate_revenue_evidence").select("*").eq("affiliate_program_id",programId).order("created_at",{ascending:false}),
 db.from("revenue_records").select("id,affiliate_revenue_candidate_id,currency,gross_amount_minor,cost_amount_minor,net_amount_minor,recognized_at,origin_type").eq("origin_type","AFFILIATE_PROGRAM").order("recognized_at",{ascending:false})]);
 return{publications:fail(publications)||[],performance:fail(performance)||[],candidates:fail(candidates)||[],evidence:fail(evidence)||[],revenue:fail(revenue)||[]};}
export async function saveAffiliatePublication(client,input){return fail(await required(client).rpc("save_affiliate_cycle_publication",{p_id:input.id||null,p_expected_version:input.expectedVersion??null,p_program:input.programId,p_content:input.contentId,p_strategy:input.strategyId||null,p_research:input.researchId||null,p_platform:input.platform,p_external_url:input.externalUrl||null,p_published_at:input.publishedAt||null,p_status:input.status,p_idempotency_key:input.idempotencyKey}))?.[0]}
export async function recordAffiliatePerformance(client,input){return fail(await required(client).rpc("record_affiliate_cycle_performance",{p_publication:input.publicationId,p_expected_publication_version:input.expectedPublicationVersion,p_observed_at:input.observedAt,p_clicks:input.clicks,p_conversions:input.conversions,p_pending:input.pendingRewardMinor,p_confirmed:input.confirmedRewardMinor,p_rejected:input.rejectedRewardMinor,p_currency:input.currency,p_source:input.source,p_idempotency_key:input.idempotencyKey}))?.[0]}
export async function createAffiliateRevenueCandidate(client,input){return fail(await required(client).rpc("create_affiliate_revenue_candidate",{p_performance:input.performanceId,p_status:input.status,p_amount_minor:input.amountMinor,p_currency:input.currency,p_reward_state:input.rewardState,p_source:input.source,p_conversion_at:input.conversionAt||null,p_confirmation_at:input.confirmationAt||null,p_provenance:input.provenance,p_idempotency_key:input.idempotencyKey}))?.[0]}
export async function attachAffiliateRevenueEvidence(client,input){return fail(await required(client).rpc("attach_affiliate_revenue_evidence",{p_candidate:input.candidateId,p_expected_version:input.expectedVersion,p_type:input.type,p_reference:input.reference,p_amount_minor:input.amountMinor,p_currency:input.currency,p_occurred_at:input.occurredAt,p_provenance:input.provenance,p_idempotency_key:input.idempotencyKey}))}
export async function confirmAffiliateActualRevenue(client,input){return fail(await required(client).rpc("confirm_affiliate_actual_revenue",{p_candidate:input.candidateId,p_expected_version:input.expectedVersion,p_evidence:input.evidenceId,p_idempotency_key:input.idempotencyKey}))}
