import { mapOrganizationRow, mapBusinessRow, mapTeamRow } from "../domain/companyCore.js";
const cols={organizations:"id,workspace_id,owner_id,name,status,lifecycle_state,policies,default_locale,default_timezone,default_currency,created_at,updated_at",businesses:"id,workspace_id,organization_id,owner_id,name,business_type,operating_status,status,lifecycle_state,revenue_model,strategy_reference,profitability_status,maturity,created_at,updated_at",teams:"id,workspace_id,organization_id,business_id,name,role_scope,permissions,membership_status,status,lifecycle_state,created_at,updated_at"};
const required=(v,n)=>{if(!v)throw new TypeError(`${n}_required`);return v};
async function read(client,table,workspaceId,filters={}){let q=client.from(table).select(cols[table]).eq("workspace_id",required(workspaceId,"workspace_id"));for(const [k,v] of Object.entries(filters))if(v!=null)q=q.eq(k,v);const {data,error}=await q.limit(100);if(error){if(error.code==="42P01")return {unavailable:true,rows:[]};throw Object.assign(new Error("company_core_read_failed"),{cause:error,table});}return {unavailable:false,rows:data||[]};}
export function createCompanyCoreV3Repository(client){if(!client?.from||!client?.rpc)throw new TypeError("company_core_client_required");const list=async(t,w,f,m)=>(await read(client,t,w,f)).rows.map(m);const one=async(t,w,id,m)=>{const x=await read(client,t,w,{id});return x.unavailable?Object.freeze({status:"Unavailable",reasonCode:"MIGRATION_016_UNAVAILABLE"}):(x.rows[0]?m(x.rows[0]):null)};const mutate=async(name,args)=>{const {data,error}=await client.rpc(name,args);if(error)throw Object.assign(new Error("company_core_protected_mutation_failed"),{cause:error});return Object.freeze({...data,externalExecution:false});};return Object.freeze({
 listOrganizations:(w)=>list("organizations",w,{},mapOrganizationRow),getOrganizationById:(w,id)=>one("organizations",w,id,mapOrganizationRow),
 listBusinesses:(w,f={})=>list("businesses",w,{organization_id:f.organizationId,business_type:f.businessType,operating_status:f.operatingStatus},mapBusinessRow),getBusinessById:(w,id)=>one("businesses",w,id,mapBusinessRow),
 listTeams:(w,f={})=>list("teams",w,{organization_id:f.organizationId,business_id:f.businessId,status:f.status},mapTeamRow),getTeamById:(w,id)=>one("teams",w,id,mapTeamRow),
 registerOrganization:(x)=>mutate("register_v3_organization",x),registerBusiness:(x)=>mutate("register_v3_business",x),registerTeam:(x)=>mutate("register_v3_team",x)
});}
