import { useEffect, useMemo, useState } from "react";
import { createRevenueRepository } from "../repositories/revenueRepository.js";
import { createOfferOperationsRepository } from "../repositories/offerOperationsRepository.js";
import { mapCanonicalActualAnalytics } from "../domain/revenueAnalytics.js";
import { buildProfitByCurrency } from "../domain/offerOperations.js";
import { Badge, EmptyState, EnvironmentBadge, ErrorState, KpiCard, Money, PageHeader, SectionHeader, SkeletonGroup, Stack, Table } from "../design-system/index.js";
import "./ProductionScreens.css";

const laneLabel = { service: "サービス", affiliate: "アフィリエイト", digital_product: "デジタル商品", media: "メディア" };
export default function Analytics({ ownerSupabaseClient, ownerSession }) {
  const revenueRepository = useMemo(() => createRevenueRepository(ownerSupabaseClient), [ownerSupabaseClient]);
  const operationsRepository = useMemo(() => createOfferOperationsRepository(ownerSupabaseClient), [ownerSupabaseClient]);
  const [actual, setActual] = useState(null); const [profit, setProfit] = useState([]); const [error, setError] = useState("");
  useEffect(() => { let active = true; (async () => { try { const context = await revenueRepository.loadContext(ownerSession); const [revenue, operations] = await Promise.all([revenueRepository.loadSnapshot(context.workspace.id), operationsRepository.loadSnapshot(context.workspace.id)]); if (active) { setActual(mapCanonicalActualAnalytics(revenue.revenue, revenue.campaigns, revenue.evidence)); setProfit(buildProfitByCurrency({ revenueRecords: revenue.revenue, costRecords: operations.costs })); setError(""); } } catch { if (active) setError("Actual and Profit data could not be retrieved."); } })(); return () => { active = false; }; }, [revenueRepository, operationsRepository, ownerSession]);
  const columns = [{ key: "campaign", label: "Campaign" }, { key: "lane", label: "Lane", render: (row) => laneLabel[row.lane] || "Revenue" }, { key: "period", label: "Period" }, { key: "evidenceStatus", label: "Evidence", render: (row) => <Badge state={row.evidenceStatus === "検証済み" ? "actual" : "unknown"} label={row.evidenceStatus} /> }, { key: "net", label: "Verified net", render: (row) => <Money value={row.netMinor} currency={row.currency} kind="actual" evidenceVerified locale="ja-JP" /> }];
  return <main className="content kv-production-screen"><Stack gap="8"><PageHeader title="Insights" description="Verified repository outputs only" actions={<EnvironmentBadge environment={actual ? "production" : "locked"} />}/>{error ? <ErrorState title="Insights unavailable" message={error} /> : null}{!actual && !error ? <SkeletonGroup count={4} label="Loading Insights" /> : null}<div className="kv-kpi-grid"><KpiCard label="Actual gross" value={actual?.rows.length ? <Money value={actual.grossMinor} currency="JPY" kind="actual" evidenceVerified locale="ja-JP" /> : null} state={actual?.rows.length ? "actual" : "unknown"} comparison="Verified Evidence only" /><KpiCard label="Revenue cost" value={actual?.rows.length ? <Money value={actual.costMinor} currency="JPY" kind="actual" evidenceVerified locale="ja-JP" /> : null} state={actual?.rows.length ? "actual" : "unknown"} /><KpiCard label="Actual net" value={actual?.rows.length ? <Money value={actual.netMinor} currency="JPY" kind="actual" evidenceVerified locale="ja-JP" /> : null} state={actual?.rows.length ? "actual" : "unknown"} /><KpiCard label="Last verified" value={actual?.lastVerifiedAt ? new Date(actual.lastVerifiedAt).toLocaleDateString("ja-JP") : null} state={actual?.lastVerifiedAt ? "actual" : "unknown"} /></div><section><SectionHeader title="Verified profit by currency" description="Forecast, test and pending evidence are excluded." />{profit.length ? <div className="kv-card-list">{profit.map((row) => <KpiCard key={row.currency} label={`${row.currency} verified profit`} value={<Money value={row.netProfitMinor} currency={row.currency} kind="actual" evidenceVerified locale="ja-JP" />} state="actual" comparison="Verified gross − Revenue cost − Actual operating cost" />)}</div> : <EmptyState title="Insufficient verified data" message="Zero is not shown because no verified record exists." />}</section><section><SectionHeader title="Verified records" /><Table caption="Verified Actual revenue records" columns={columns} rows={actual?.rows || []} loading={!actual && !error} emptyTitle="No verified Actual records" emptyMessage="Evidence and Owner approval are required before a record appears here." /></section></Stack></main>;
}
