import { useEffect, useState } from "react";
import { validateCredentialFreePayload } from "../services/credentialSecurityBoundary.js";
import { EmptyState, EnvironmentBadge, ErrorState, PageHeader, SectionHeader, SkeletonGroup, Stack, Table, Timeline } from "../design-system/index.js";
import "./ProductionScreens.css";

function safeSummary(value) { return validateCredentialFreePayload(value || {}).ok ? JSON.stringify(value || {}) : "[redacted]"; }
export default function CanonicalAudit({ ownerSupabaseClient, ownerSession }) {
  const [events, setEvents] = useState([]); const [status, setStatus] = useState("loading");
  useEffect(() => { let active = true; (async () => { if (!ownerSupabaseClient || !ownerSession?.user?.id) { setStatus("blocked"); return; } const membership = await ownerSupabaseClient.from("workspace_members").select("workspace_id").eq("user_id", ownerSession.user.id).eq("role", "owner").eq("status", "active"); if (!active) return; if (membership.error || membership.data?.length !== 1) { setStatus("blocked"); return; } const result = await ownerSupabaseClient.from("audit_logs").select("id,actor_type,action,entity_type,after_summary,metadata_sanitized,created_at").eq("workspace_id", membership.data[0].workspace_id).order("created_at", { ascending: false }).limit(100); if (!active) return; if (result.error) { setStatus("unavailable"); setEvents([]); } else { setEvents((result.data || []).map((item) => ({ ...item, safeSummary: safeSummary(item.after_summary), safeMetadata: safeSummary(item.metadata_sanitized) }))); setStatus("ready"); } })(); return () => { active = false; }; }, [ownerSupabaseClient, ownerSession]);
  const columns = [{ key: "created_at", label: "Timestamp", render: (item) => new Date(item.created_at).toLocaleString() }, { key: "actor_type", label: "Actor" }, { key: "action", label: "Action" }, { key: "entity_type", label: "Entity" }, { key: "safeSummary", label: "Redacted summary" }];
  const timeline = events.slice(0, 10).map((item) => ({ id: item.id, timestamp: item.created_at, title: item.action, description: item.entity_type, meta: item.safeSummary }));
  return <main className="content kv-production-screen"><Stack gap="8"><PageHeader title="Audit" description="Append-only Production audit records" actions={<EnvironmentBadge environment={status === "ready" ? "production" : "locked"} />}/>{status === "loading" ? <SkeletonGroup count={5} label="Loading Audit" /> : null}{status === "blocked" || status === "unavailable" ? <ErrorState title="Audit unavailable" message={status === "blocked" ? "Exactly one active Owner Workspace is required." : "The canonical audit source could not be read."} /> : null}{status === "ready" && !events.length ? <EmptyState title="No audit records" message="No append-only audit record exists in this Workspace." /> : null}{events.length ? <><section><SectionHeader title="Recent activity" /><Timeline items={timeline} /></section><section><SectionHeader title="Audit records" description="Actor identifiers, Workspace identifiers, credentials and secret values are not rendered." /><Table caption="Redacted append-only audit records" columns={columns} rows={events} /></section></> : null}</Stack></main>;
}
