import { useEffect, useState } from "react";
import { validateCredentialFreePayload } from "../services/credentialSecurityBoundary.js";
import { EmptyState, EnvironmentBadge, ErrorState, PageHeader, SectionHeader, SkeletonGroup, Stack, SystemBoundary, Table, Timeline } from "../design-system/index.js";
import "./ProductionScreens.css";

function safeSummary(value) { return validateCredentialFreePayload(value || {}).ok ? JSON.stringify(value || {}) : "[redacted]"; }
export default function CanonicalAudit({ ownerSupabaseClient, ownerSession }) {
  const [events, setEvents] = useState([]); const [status, setStatus] = useState("loading");
  useEffect(() => { let active = true; (async () => { if (!ownerSupabaseClient || !ownerSession?.user?.id) { setStatus("blocked"); return; } const workspace = await ownerSupabaseClient.rpc("resolve_personal_workspace"); if (!active) return; if (workspace.error || !workspace.data) { setStatus("blocked"); return; } let result = await ownerSupabaseClient.from("audit_logs").select("id,actor_type,action,entity_type,after_summary,metadata_sanitized,created_at").eq("workspace_id", workspace.data).order("created_at", { ascending: false }).limit(100); if (result.error) { const timeline = await ownerSupabaseClient.from("operational_activity_events").select("id,actor_type,event_type,object_type,safe_metadata,created_at").eq("workspace_id", workspace.data).order("created_at", { ascending: false }).limit(100); result = timeline.error ? { error: timeline.error, data: [] } : { error: null, data: (timeline.data || []).map((item) => ({ id: item.id, actor_type: item.actor_type, action: item.event_type, entity_type: item.object_type, after_summary: item.safe_metadata, metadata_sanitized: { source: "OPERATIONAL_ACTIVITY" }, created_at: item.created_at })) }; } if (!active) return; if (result.error) { setStatus("unavailable"); setEvents([]); } else { setEvents((result.data || []).map((item) => ({ ...item, safeSummary: safeSummary(item.after_summary), safeMetadata: safeSummary(item.metadata_sanitized) }))); setStatus("ready"); } })(); return () => { active = false; }; }, [ownerSupabaseClient, ownerSession]);
  const columns = [{ key: "created_at", label: "Timestamp", render: (item) => new Date(item.created_at).toLocaleString() }, { key: "actor_type", label: "Actor" }, { key: "action", label: "Action" }, { key: "entity_type", label: "Entity" }, { key: "safeSummary", label: "Redacted summary" }];
  const timeline = events.slice(0, 10).map((item) => ({ id: item.id, timestamp: item.created_at, title: item.action, description: item.entity_type, meta: item.safeSummary }));
  return <main className="content kv-production-screen kv-archetype-audit"><Stack gap="8"><PageHeader eyebrow="APPEND-ONLY RECORD" title="監査" description="追記専用のProduction監査記録を、秘匿情報を除いて確認します。" actions={<EnvironmentBadge environment={status === "ready" ? "production" : "locked"} />}/><SystemBoundary title="監査データ境界" description="表示失敗によってデータ変更は発生しません。生の例外、Secret、内部識別子は表示しません。" items={["Append-only", "Workspace scoped", "Secret redacted"]} />{status === "loading" ? <SkeletonGroup count={5} label="監査記録を読み込み中" /> : null}{status === "blocked" || status === "unavailable" ? <ErrorState title="監査記録を表示できません" message={status === "blocked" ? "Owner Workspaceを一意に確認できないため、安全に停止しました。データ変更はありません。" : "正式な監査データソースを読み取れませんでした。データ変更はありません。"} /> : null}{status === "ready" && !events.length ? <EmptyState title="監査記録はありません" message="このWorkspaceには表示可能な追記専用監査記録がありません。" /> : null}{events.length ? <><section><SectionHeader title="最近の活動" /><Timeline items={timeline} /></section><section><SectionHeader title="監査記録" description="Actor ID、Workspace ID、認証情報、秘密値は表示しません。" /><Table caption="秘匿情報を除いた追記専用監査記録" columns={columns} rows={events} /></section></> : null}</Stack></main>;
}
