import { useCallback, useEffect, useMemo, useState } from "react";
import { createOfferOperationsRepository } from "../repositories/offerOperationsRepository.js";
import { buildProfitByCurrency, formatContentPackageMarkdown, nextOperationAction, validateAffiliateOffer } from "../domain/offerOperations.js";
import { Card, EnvironmentBadge, KpiCard, Money, PageHeader } from "../design-system/index.js";
import "./ProductionScreens.css";

const statusLabel={owner_artifact_approval:"Content承認待ち",manual_package_ready:"手動実行準備完了",performance_waiting:"Performance待ち",learning_ready:"学習準備完了",closed:"完了"};
const readinessLabel={adapter_unavailable:"Adapter未提供",credentials_missing:"認証情報未設定",authorization_required:"Owner認証が必要",permission_missing:"権限不足",configuration_incomplete:"設定未完了",dry_run_ready:"手動/Dry-run準備完了",production_ready:"本番準備完了",owner_locked:"Owner方針でロック",error:"接続エラー"};
const initialOffer={title:"",advertiser:"",sourceUrl:"",category:"SaaS",commissionSummary:"",commissionMinor:"",currency:"JPY",termsSummary:"",disclosure:"広告・アフィリエイトを含むコンテンツです。",targetMarkets:["JP","GLOBAL"]};

export default function OfferOperationsWorkspace({ownerSupabaseClient,ownerSession}){
  const repository=useMemo(()=>createOfferOperationsRepository(ownerSupabaseClient),[ownerSupabaseClient]);
  const [context,setContext]=useState(null);const [snapshot,setSnapshot]=useState(null);const [offer,setOffer]=useState(initialOffer);
  const [selected,setSelected]=useState("");const [busy,setBusy]=useState("");const [notice,setNotice]=useState("");const [error,setError]=useState("");
  const [performance,setPerformance]=useState({market:"JP",channel:"manual",periodStart:new Date().toISOString().slice(0,10),periodEnd:new Date().toISOString().slice(0,10),impressions:"0",clicks:"0",conversions:"0",sourceReference:"",isTest:false});
  const [cost,setCost]=useState({category:"ai_api",amountMinor:"0",currency:"JPY",valueType:"actual",occurredAt:new Date().toISOString(),sourceReference:"",note:""});
  const refresh=useCallback(async()=>{try{const c=await repository.loadContext(ownerSession);const s=await repository.loadSnapshot(c.workspace.id);setContext(c);setSnapshot(s);setSelected((old)=>old||s.operations?.[0]?.id||"");setError("");}catch{setError("運用Repositoryを取得できません。Migration 009の適用状態とOwner Sessionを確認してください。");}},[repository,ownerSession]);
  useEffect(()=>{refresh();},[refresh]);
  const run=async(key,action,message)=>{if(busy)return;setBusy(key);setError("");setNotice("");try{await action();setNotice(message);await refresh();}catch{setError("処理を安全に停止しました。入力、承認Snapshot、Workspace境界、重複Referenceを確認してください。");}finally{setBusy("");}};
  const operation=snapshot?.operations?.find((v)=>v.id===selected)||snapshot?.operations?.[0];
  const selectedOffer=snapshot?.offers?.find((v)=>v.id===operation?.offer_id);
  const approval=snapshot?.approvals?.find((v)=>v.id===operation?.approval_request_id);
  const pkg=snapshot?.packages?.find((v)=>v.approval_request_id===operation?.approval_request_id);
  const learning=snapshot?.learnings?.filter((v)=>v.campaign_id===operation?.campaign_id).at(-1);
  const profits=buildProfitByCurrency({revenueRecords:snapshot?.revenue,costRecords:snapshot?.costs});
  const register=()=>{const checked=validateAffiliateOffer(offer);if(!checked.valid){setError(checked.errors[0]);return;}const key=`offer:${checked.normalized.advertiser.toLowerCase()}:${checked.normalized.title.toLowerCase()}`;run("register",()=>repository.registerOffer(context.workspace.id,context.brand.id,key,checked.normalized),"OfferをSupabaseへ登録しました。次に運用準備を開始してください。");};
  const copyPackage=()=>run("copy",async()=>{await navigator.clipboard.writeText(formatContentPackageMarkdown(pkg.payload_snapshot));await repository.recordPackageAccess(pkg.id,"copied");},"承認済みPackageをコピーしました。外部送信は実行していません。");
  const downloadPackage=()=>run("download",async()=>{const blob=new Blob([formatContentPackageMarkdown(pkg.payload_snapshot)],{type:"text/markdown;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="kevirio-approved-content-package.md";a.click();URL.revokeObjectURL(url);await repository.recordPackageAccess(pkg.id,"downloaded");},"承認済みPackageをダウンロードしました。外部送信は実行していません。");
  return <main className="content production-revenue offer-operations kv-production-screen">
    <PageHeader eyebrow="OPERATION LIFECYCLE" title="オペレーション" description="オファー登録からEvidence・学習まで、保護された運用ライフサイクルを管理します。" actions={<EnvironmentBadge environment={context ? "production" : "locked"} />} />
    <ol className="kv-operation-lifecycle" aria-label="オペレーションのライフサイクル">{["Offer", "Intelligence", "Strategy", "Content", "Approval", "Schedule / Manual publish", "Evidence", "Revenue", "Learning"].map((stage, index) => <li key={stage} className={operation && index === 4 ? "is-current" : ""}><span>{index + 1}</span>{stage}</li>)}</ol>
    <Card variant="decision" className="kv-operation-boundary"><strong>外部実行：ロック中</strong><p>CopyとDownloadのみ。SNS、API、OAuth、課金、公開操作は実行しません。</p></Card>
    {notice&&<p className="production-alert success">{notice}</p>}{error&&<p className="production-alert danger">{error}</p>}
    <section className="kv-kpi-grid" aria-label="Operations summary"><KpiCard label="Registered offers" value={snapshot ? snapshot.offers.length : null} state={snapshot ? "actual" : "unknown"} /><KpiCard label="Active operations" value={snapshot ? snapshot.operations.length : null} state={snapshot ? "running" : "unknown"} /><KpiCard label="Owner approvals" value={snapshot ? snapshot.approvals.filter((v)=>v.status==="pending"&&snapshot.operations.some((o)=>o.approval_request_id===v.id)).length : null} state="pending" /><KpiCard label="Verified Actual records" value={snapshot ? snapshot.revenue.length : null} state={snapshot?.revenue?.length ? "actual" : "unknown"} comparison="Evidence-backed records only" /></section>
    <section className="production-grid">
      <article className="production-panel"><div className="panel-heading"><div><span className="eyebrow">1. OFFER</span><h2>実Offerを登録</h2></div><span className="mode-badge">OWNER-SUPPLIED</span></div>
        <label>Offer名<input value={offer.title} onChange={(e)=>setOffer({...offer,title:e.target.value})} placeholder="例: 業務効率化SaaS パートナープログラム"/></label><label>広告主<input value={offer.advertiser} onChange={(e)=>setOffer({...offer,advertiser:e.target.value})}/></label><label>報酬条件の要約<textarea value={offer.commissionSummary} onChange={(e)=>setOffer({...offer,commissionSummary:e.target.value})} placeholder="確定条件だけを記載"/></label>
        <div className="evidence-fields"><label>カテゴリ<input value={offer.category} onChange={(e)=>setOffer({...offer,category:e.target.value})}/></label><label>通貨<input maxLength="3" value={offer.currency} onChange={(e)=>setOffer({...offer,currency:e.target.value.toUpperCase()})}/></label></div><label>公式URL（任意）<input value={offer.sourceUrl} onChange={(e)=>setOffer({...offer,sourceUrl:e.target.value})}/></label><details><summary>条件・開示の詳細</summary><label>利用条件<textarea value={offer.termsSummary} onChange={(e)=>setOffer({...offer,termsSummary:e.target.value})}/></label><label>広告開示<textarea value={offer.disclosure} onChange={(e)=>setOffer({...offer,disclosure:e.target.value})}/></label></details><button className="production-primary" disabled={!context||Boolean(busy)} onClick={register}>Offerを登録</button>
        {(snapshot?.offers||[]).map((v)=><div className="approval-row" key={v.id}><div><strong>{v.title}</strong><small>{v.advertiser} · {v.target_markets?.join(" / ")}</small></div><button disabled={Boolean(busy)||snapshot.operations.some((o)=>o.offer_id===v.id)} onClick={()=>run(`prepare:${v.id}`,()=>repository.prepareOperation(v.id,`operation:${v.id}:v1`),"Intelligence、Strategy、Content、Approval、Scheduleを準備しました。")} >{snapshot.operations.some((o)=>o.offer_id===v.id)?"準備済み":"運用準備"}</button></div>)}
      </article>
      <article className="production-panel"><div className="panel-heading"><div><span className="eyebrow">NEXT OWNER ACTION</span><h2>{operation?statusLabel[operation.status]:"Offer登録待ち"}</h2></div></div><p className="evidence-boundary">{nextOperationAction(operation)}</p>{snapshot?.operations?.length>1&&<label>Operation<select value={operation?.id||""} onChange={(e)=>setSelected(e.target.value)}>{snapshot.operations.map((v)=><option value={v.id} key={v.id}>{snapshot.offers.find((o)=>o.id===v.offer_id)?.title}</option>)}</select></label>}
        {operation&&<><div className="workflow-row"><span>Offer</span><strong>{selectedOffer?.title}</strong><small>{selectedOffer?.advertiser}</small></div><div className="workflow-row"><span>現在Step</span><strong>{statusLabel[operation.status]}</strong><small>Reload復元対象</small></div><div className="workflow-row"><span>External</span><strong>Owner操作のみ</strong><small>自動実行なし</small></div></>}
      </article>
      {operation&&<article className="production-panel featured"><div className="panel-heading"><div><span className="eyebrow">2–5. INTELLIGENCE / STRATEGY / CONTENT / APPROVAL</span><h2>Owner Review</h2></div><span className="lock-chip">Forecast / Inferenceを明示</span></div><div className="package-preview-grid">
        <section><h4>日本市場</h4><p>{operation.intelligence_snapshot?.JP?.summary}</p><p>{operation.strategy_snapshot?.JP?.positioning}</p></section><section><h4>英語市場</h4><p>{operation.intelligence_snapshot?.GLOBAL?.summary}</p><p>{operation.strategy_snapshot?.GLOBAL?.positioning}</p></section><section><h4>対象Audience</h4><ul>{Object.values(operation.audience_snapshot||{}).flat().map((v,i)=><li key={i}>{v.name}: {v.need}</li>)}</ul></section><section><h4>Content Batch</h4><strong>{operation.content_snapshot?.article?.headline}</strong><ul>{operation.content_snapshot?.article?.outline?.map((v)=><li key={v}>{v}</li>)}</ul></section><section className="wide"><h4>広告開示</h4><p>{operation.content_snapshot?.disclosure}</p></section></div>
        {approval?.status==="pending"&&<button className="production-primary" disabled={Boolean(busy)} onClick={()=>run("approve",()=>repository.decideApproval(approval.id,approval.preview_snapshot),"Contentを承認し、改変不能SnapshotからManual Packageを生成しました。")}>Snapshotを確認して承認</button>}
        {approval?.status==="approved"&&<p className="production-alert success">Owner承認済み。承認SnapshotとArtifact versionは固定されています。</p>}
      </article>}
      {pkg&&<article className="production-panel featured"><div className="panel-heading"><div><span className="eyebrow">6–7. SCHEDULE / EXECUTION BOUNDARY</span><h2>承認済みManual Execution Package</h2></div><span className="lock-chip">外部自動実行なし</span></div><div className="manual-package-actions"><button onClick={copyPackage}>MarkdownをCopy</button><button onClick={downloadPackage}>MarkdownをDownload</button></div><pre className="operation-preview">{formatContentPackageMarkdown(pkg.payload_snapshot)}</pre></article>}
      {operation&&<article className="production-panel"><div className="panel-heading"><div><span className="eyebrow">8. PERFORMANCE</span><h2>公開後の実測値</h2></div><span className="mode-badge actual">Revenueではありません</span></div><div className="evidence-fields"><label>市場<select value={performance.market} onChange={(e)=>setPerformance({...performance,market:e.target.value})}><option>JP</option><option>GLOBAL</option></select></label><label>Reference<input value={performance.sourceReference} onChange={(e)=>setPerformance({...performance,sourceReference:e.target.value})}/></label></div><div className="fact-grid">{["impressions","clicks","conversions"].map((key)=><label key={key}>{key}<input inputMode="numeric" value={performance[key]} onChange={(e)=>setPerformance({...performance,[key]:e.target.value})}/></label>)}</div><label className="check-line"><input type="checkbox" checked={performance.isTest} onChange={(e)=>setPerformance({...performance,isTest:e.target.checked})}/>Test dataとして明示</label><button className="production-secondary" disabled={!pkg||!performance.sourceReference||Boolean(busy)} onClick={()=>run("performance",()=>repository.recordPerformance(operation.id,{...performance,impressions:Number(performance.impressions),clicks:Number(performance.clicks),conversions:Number(performance.conversions)}),"Performanceを保存しました。Actual Revenueには加算していません。")} >Performanceを登録</button></article>}
      {operation&&<article className="production-panel"><div className="panel-heading"><div><span className="eyebrow">9–10. COST / PROFIT</span><h2>Operating Costと検証済み利益</h2></div></div><div className="evidence-fields"><label>区分<select value={cost.category} onChange={(e)=>setCost({...cost,category:e.target.value})}><option value="ai_api">AI API</option><option value="content_production">Content制作</option><option value="platform">Platform</option><option value="contractor">外注</option><option value="owner_labor">Owner工数</option><option value="other">その他</option></select></label><label>Actual区分<select value={cost.valueType} onChange={(e)=>setCost({...cost,valueType:e.target.value})}><option value="actual">Actual cost</option><option value="forecast">Forecast</option><option value="test">Test</option></select></label></div><div className="evidence-fields"><label>金額 minor<input inputMode="numeric" value={cost.amountMinor} onChange={(e)=>setCost({...cost,amountMinor:e.target.value})}/></label><label>Reference<input value={cost.sourceReference} onChange={(e)=>setCost({...cost,sourceReference:e.target.value})}/></label></div><button className="production-secondary" disabled={!cost.sourceReference||Boolean(busy)} onClick={()=>run("cost",()=>repository.recordCost(operation.id,{...cost,amountMinor:Number(cost.amountMinor)}),"Costを区分付きで保存しました。")} >Costを登録</button>{!profits.length?<p className="empty-copy">実績未登録。Forecast/TestはActual利益に含めません。</p>:profits.map((v)=><div className="actual-row" key={v.currency}><div><strong>{v.currency} Verified Profit</strong><small>Gross − Revenue cost − Actual operating cost</small></div><div><Money value={v.netProfitMinor} currency={v.currency} kind="actual" evidenceVerified locale="ja-JP" /><small>{v.verifiedRevenueCount} verified revenue</small></div></div>)}</article>}
      {operation&&<article className="production-panel featured"><div className="panel-heading"><div><span className="eyebrow">11. LEARNING</span><h2>Actual Performanceから次の検証へ</h2></div><span className="mode-badge">GENERATED INFERENCE</span></div>{learning?<><p>{learning.learning_snapshot?.finding}</p><p><strong>次の一要素テスト:</strong> {learning.learning_snapshot?.recommendedNextTest}</p></>:<p className="empty-copy">Performance登録後に生成できます。学習は推論として保存され、Actual Revenueを変更しません。</p>}<button className="production-secondary" disabled={!snapshot?.performance?.some((v)=>v.campaign_id===operation.campaign_id)||Boolean(busy)} onClick={()=>run("learning",()=>repository.generateLearning(operation.id),"Performanceからgenerated inferenceを保存しました。")} >Learningを生成</button></article>}
      <article className="production-panel featured"><div className="panel-heading"><div><span className="eyebrow">CONNECTION READINESS</span><h2>外部連携はProvider単位でロック</h2></div></div><div className="connection-grid">{(snapshot?.connections||[]).map((v)=><div key={v.id}><strong>{v.provider}</strong><span>{readinessLabel[v.readiness]}</span><small>{v.external_execution_allowed?"実行可能":"外部実行なし"}</small></div>)}</div></article>
    </section>
  </main>;
}
