import { useEffect, useMemo, useState } from "react";
import { buildConnectionView } from "../services/providerPlatform";
import { EmptyState, EnvironmentBadge, ErrorState, PageHeader, ProviderCard, SectionHeader, SkeletonGroup, Stack } from "../design-system/index.js";
import "./ProductionScreens.css";

const ITEMS = [{ provider: "google", label: "Google", type: "oauth", maturity: "Conditional", ownerActionRequired: "Confirm the registered OAuth redirect URI" }, { provider: "canva", label: "Canva", type: "oauth", maturity: "Conditional", ownerActionRequired: "Confirm the registered callback configuration" }, { provider: "openai", label: "OpenAI", type: "api_key", maturity: "Locked", ownerActionRequired: "Confirm Cost Guard policy and allowlisted model" }, { provider: "anthropic", label: "Anthropic", type: "api_key", maturity: "Locked", ownerActionRequired: "No verified model and pricing contract is registered" }, { provider: "gemini", label: "Gemini", type: "api_key", maturity: "Conditional", ownerActionRequired: "Keep execution locked after health verification" }, { provider: "perplexity", label: "Perplexity", type: "api_key", maturity: "Conditional", ownerActionRequired: "Confirm the formal payload contract" }];
export default function ProviderHub({ ownerSupabaseClient, ownerSession }) {
  const [remote, setRemote] = useState([]); const [status, setStatus] = useState("loading");
  useEffect(() => { let active = true; (async () => { if (!ownerSupabaseClient || !ownerSession?.user?.id) { setStatus("blocked"); return; } const memberships = await ownerSupabaseClient.from("workspace_members").select("workspace_id").eq("user_id", ownerSession.user.id).eq("role", "owner").eq("status", "active"); if (!active) return; if (memberships.error || memberships.data?.length !== 1) { setStatus(memberships.data?.length > 1 ? "workspace_required" : "unavailable"); setRemote([]); return; } const result = await ownerSupabaseClient.from("provider_connections").select("provider,connection_type,state,granted_scopes,last_checked_at,last_success_at,last_error_class").eq("workspace_id", memberships.data[0].workspace_id).order("provider"); if (!active) return; if (result.error) { setStatus("unavailable"); setRemote([]); } else { setRemote(result.data || []); setStatus("ready"); } })(); return () => { active = false; }; }, [ownerSupabaseClient, ownerSession]);
  const cards = useMemo(() => ITEMS.map((item) => { const found = remote.find((row) => row.provider === item.provider); return { ...item, ...buildConnectionView({ ...item, type: found?.connection_type || item.type, state: found?.state || "locked", grantedScopes: found?.granted_scopes, lastCheckedAt: found?.last_checked_at, lastSuccessAt: found?.last_success_at }) }; }), [remote]);
  return <main className="content kv-production-screen"><Stack gap="8"><PageHeader title="Integrations" description="Connection, permission and execution are separate states" actions={<EnvironmentBadge environment={status === "ready" ? "production" : "locked"} />} /><p className="kv-boundary-note">External Execution: LOCKED</p>{status === "loading" ? <SkeletonGroup count={4} label="Loading Integrations" /> : null}{status === "unavailable" || status === "workspace_required" || status === "blocked" ? <ErrorState title="Integrations blocked" message={status === "workspace_required" ? "Exactly one active Owner Workspace is required." : "Provider connection state is unavailable."} /> : null}<section><SectionHeader title="Provider connections" description="Credential values are never returned or rendered." />{cards.length ? <div className="kv-screen-grid">{cards.map((card) => <ProviderCard key={card.provider} provider={card.label} maturity={card.maturity} connection={card.connectionState} credentialStorage="Server only — value not exposed" readCapability={card.permissionState} writeCapability="Locked" scope={card.grantedScopes.length ? card.grantedScopes.join(", ") : "None"} quota="Unknown" costGuard={card.costState} health={card.lastCheckedAt} ownerAction={card.ownerActionRequired} externalExecution={false} />)}</div> : <EmptyState title="No provider definitions" />}</section></Stack></main>;
}
