import { useEffect, useMemo, useState } from "react";
import { buildConnectionView } from "../services/providerPlatform";
import { PRIVATE_BETA_INTEGRATIONS } from "../data/privateBetaIntegrationCatalog.js";
import { EmptyState, EnvironmentBadge, ErrorState, PageHeader, ProviderCard, SectionHeader, SkeletonGroup, Stack, SystemBoundary } from "../design-system/index.js";
import "./ProductionScreens.css";

const ITEMS = PRIVATE_BETA_INTEGRATIONS.map(item=>({...item,maturity:item.state,ownerActionRequired:item.ownerAction,permissionState:item.read,costState:item.cost}));
export default function ProviderHub({ ownerSupabaseClient, ownerSession }) {
  // Production invariant: External Execution: LOCKED
  const [remote, setRemote] = useState([]); const [status, setStatus] = useState("loading");
  useEffect(() => { let active = true; (async () => { if (!ownerSupabaseClient || !ownerSession?.user?.id) { setStatus("blocked"); return; } const memberships = await ownerSupabaseClient.from("workspace_members").select("workspace_id").eq("user_id", ownerSession.user.id).eq("role", "owner").eq("status", "active"); if (!active) return; if (memberships.error || memberships.data?.length !== 1) { setStatus(memberships.data?.length > 1 ? "workspace_required" : "unavailable"); setRemote([]); return; } const result = await ownerSupabaseClient.from("provider_connections").select("provider,connection_type,state,granted_scopes,last_checked_at,last_success_at,last_error_class").eq("workspace_id", memberships.data[0].workspace_id).order("provider"); if (!active) return; if (result.error) { setStatus("unavailable"); setRemote([]); } else { setRemote(result.data || []); setStatus("ready"); } })(); return () => { active = false; }; }, [ownerSupabaseClient, ownerSession]);
  const cards = useMemo(() => ITEMS.map((item) => { const found = remote.find((row) => row.provider === item.provider); if(!found)return {...item,connectionState:item.state,grantedScopes:[],lastCheckedAt:null}; return { ...item, ...buildConnectionView({ ...item, type: found.connection_type || item.type, state: found.state, grantedScopes: found.granted_scopes, lastCheckedAt: found.last_checked_at, lastSuccessAt: found.last_success_at }) }; }), [remote]);
  return <main className="content kv-production-screen kv-archetype-directory"><Stack gap="8"><PageHeader eyebrow="PROVIDER DIRECTORY" title="連携" description="接続、権限、Cost Guard、実行可能性を分けて安全に確認します。" actions={<EnvironmentBadge environment={status === "ready" ? "production" : "locked"} />} /><SystemBoundary title="Provider外部実行はロック中" description="接続状態は実行権限を意味しません。認証情報の値は取得も表示もしません。" items={["Credential server-only", "Writeロック", "Cost Guard必須"]} />{status === "loading" ? <SkeletonGroup count={4} label="連携状態を読み込み中" /> : null}{status === "unavailable" || status === "workspace_required" || status === "blocked" ? <ErrorState title="連携状態を表示できません" message={status === "workspace_required" ? "有効なOwner Workspaceが1つだけ必要です。" : "Provider接続状態を取得できません。"} /> : null}<section><SectionHeader title="Provider接続" description="現在利用可能な状態と、条件付き・ロック状態をカード内で明示します。" />{cards.length ? <div className="kv-screen-grid kv-provider-directory">{cards.map((card) => <ProviderCard key={card.provider} provider={card.label} maturity={card.maturity} connection={card.connectionState} credentialStorage="サーバー管理・値は非表示" readCapability={card.permissionState} writeCapability="ロック中" scope={card.grantedScopes.length ? card.grantedScopes.join(", ") : "なし"} quota="未取得" costGuard={card.costState} health={card.lastCheckedAt} ownerAction={card.ownerActionRequired} externalExecution={false} />)}</div> : <EmptyState title="Provider定義はありません" />}</section></Stack></main>;
}
