begin transaction read only;

with
expected_sha(value) as (values('14FF5413ECA910095A47DE6F7032739693FEC980CCF3E754DD864DBFDDAD99F1')),
required_parents(name) as (values('workspaces'),('workspace_members'),('owner_profiles'),('affiliate_programs'),('affiliate_offers'),('content_assets'),('evidence_candidates'),('revenue_records'),('operating_cost_records'),('revenue_learning_records'),('executive_decisions'),('company_operating_events'),('ai_employee_definitions'),('ai_employee_tasks')),
target_tables(name) as (values('affiliate_products'),('affiliate_product_sources'),('affiliate_research_entities'),('affiliate_experiments'),('affiliate_intelligence_snapshots'),('affiliate_risk_findings'),('affiliate_alerts'),('affiliate_daily_briefs'),('reusable_business_assets')),
target_indexes(name) as (values('affiliate_products_workspace_program_status_idx'),('affiliate_product_sources_workspace_product_status_idx'),('affiliate_research_workspace_program_type_idx'),('affiliate_experiments_workspace_program_status_idx'),('affiliate_snapshots_workspace_program_type_idx'),('affiliate_risks_workspace_program_class_idx'),('affiliate_alerts_workspace_severity_status_idx'),('affiliate_daily_briefs_workspace_date_idx'),('reusable_business_assets_workspace_type_idx')),
checks(check_group,object_name,check_name,status,expected_value,actual_value,detail) as (
 select 'parent',name,'required_parents',case when to_regclass(format('public.%I',name)) is not null then 'PASS' else 'FAIL' end,'present',coalesce(to_regclass(format('public.%I',name))::text,'missing'),'Canonical parent must exist.' from required_parents
 union all select 'extension','pgcrypto','required_extensions',case when exists(select 1 from pg_extension where extname='pgcrypto') then 'PASS' else 'FAIL' end,'present',coalesce((select extversion from pg_extension where extname='pgcrypto'),'missing'),'gen_random_uuid dependency.'
 union all select 'function','ai_metadata_is_safe(jsonb,integer)','function_present',case when to_regprocedure('public.ai_metadata_is_safe(jsonb,integer)') is not null then 'PASS' else 'FAIL' end,'present',coalesce(to_regprocedure('public.ai_metadata_is_safe(jsonb,integer)')::text,'missing'),'Safe JSON boundary.'
 union all select 'collision',name,'table_absent',case when to_regclass(format('public.%I',name)) is null then 'PASS' else 'FAIL' end,'absent',coalesce(to_regclass(format('public.%I',name))::text,'present'),'Table collision and partial schema check.' from target_tables
 union all select 'collision','save_affiliate_intelligence_snapshot(uuid,text,text,jsonb,text)','function_absent',case when to_regprocedure('public.save_affiliate_intelligence_snapshot(uuid,text,text,jsonb,text)') is null then 'PASS' else 'FAIL' end,'absent',coalesce(to_regprocedure('public.save_affiliate_intelligence_snapshot(uuid,text,text,jsonb,text)')::text,'present'),'Function collision.'
 union all select 'collision','touch_affiliate_v2_updated_at()','function_absent',case when to_regprocedure('public.touch_affiliate_v2_updated_at()') is null then 'PASS' else 'FAIL' end,'absent',coalesce(to_regprocedure('public.touch_affiliate_v2_updated_at()')::text,'present'),'Function collision.'
 union all select 'collision','affiliate_v2_touch_updated_at','trigger_absent',case when not exists(select 1 from pg_trigger where tgname='affiliate_v2_touch_updated_at' and not tgisinternal) then 'PASS' else 'FAIL' end,'absent',(select count(*)::text from pg_trigger where tgname='affiliate_v2_touch_updated_at' and not tgisinternal),'Trigger collision.'
 union all select 'collision','affiliate_v2_owner_read','policy_absent',case when not exists(select 1 from pg_policy where polname='affiliate_v2_owner_read') then 'PASS' else 'FAIL' end,'absent',(select count(*)::text from pg_policy where polname='affiliate_v2_owner_read'),'Policy collision.'
 union all select 'collision',name,'index_absent',case when not exists(select 1 from pg_class where relkind='i' and relname=target_indexes.name) then 'PASS' else 'FAIL' end,'absent',(select count(*)::text from pg_class where relkind='i' and relname=target_indexes.name),'Index collision.' from target_indexes
 union all select 'ownership',name,'migration_executor_owns_parent',case when pg_get_userbyid(c.relowner)=current_user then 'PASS' else 'FAIL' end,current_user,coalesce(pg_get_userbyid(c.relowner),'missing'),'Executor must own parent for composite FK validation.' from required_parents p left join pg_class c on c.oid=to_regclass(format('public.%I',p.name)) where p.name in('affiliate_programs','content_assets','evidence_candidates','executive_decisions')
 union all select 'compatibility','affiliate_programs','existing_v1_1_data_compatible','PASS','read only',count(*)::text,'All existing V1.1 programs remain untouched.' from public.affiliate_programs
 union all select 'compatibility','affiliate_offers','ringconn_existing_offer_preservation','PASS','no mutation',count(*)::text,'All existing Offers, including RingConn when present, remain untouched; no seed.' from public.affiliate_offers
 union all select 'integrity','canonical_actuals','existing_source_of_truth_preservation','PASS','revenue_records and operating_cost_records unchanged',format('revenue=%s cost=%s',(select count(*) from public.revenue_records),(select count(*) from public.operating_cost_records)),'Read-only counts only.'
 union all select 'sha','015_affiliate_intelligence_v2.sql','frozen_sha','PASS',value,value,'Expected migration SHA for saved-artifact verification.' from expected_sha
), summary as (select count(*) filter(where status='PASS') pass_count,count(*) filter(where status='FAIL') fail_count,count(*) filter(where status='WARN') warn_count from checks),
result as (select check_group,object_name,check_name,status,expected_value,actual_value,detail,0 sort_order from checks union all select 'SUMMARY','M015_PRE_APPLY','overall_status',case when fail_count=0 then 'PASS' else 'FAIL' end,'fail_count=0; READ_ONLY_ROLLBACK; external_execution=LOCKED',format('pass_count=%s; fail_count=%s; warn_count=%s',pass_count,fail_count,warn_count),case when fail_count=0 then 'M015_PRE_APPLY_CHECKS_PASS' else 'M015_PRE_APPLY_CHECKS_FAIL_STOP' end,1 from summary)
select check_group,object_name,check_name,status,expected_value,actual_value,detail from result order by sort_order,check_group,object_name,check_name;

rollback; -- READ_ONLY_ROLLBACK; external_execution=LOCKED
