begin transaction read only;

with
expected_tables(name) as (values('affiliate_products'),('affiliate_product_sources'),('affiliate_research_entities'),('affiliate_experiments'),('affiliate_intelligence_snapshots'),('affiliate_risk_findings'),('affiliate_alerts'),('affiliate_daily_briefs'),('reusable_business_assets')),
expected_indexes(name) as (values('affiliate_products_workspace_program_status_idx'),('affiliate_product_sources_workspace_product_status_idx'),('affiliate_research_workspace_program_type_idx'),('affiliate_experiments_workspace_program_status_idx'),('affiliate_snapshots_workspace_program_type_idx'),('affiliate_risks_workspace_program_class_idx'),('affiliate_alerts_workspace_severity_status_idx'),('affiliate_daily_briefs_workspace_date_idx'),('reusable_business_assets_workspace_type_idx')),
checks(check_group,object_name,check_name,status,expected_value,actual_value,detail) as (
 select 'table',name,'tables',case when to_regclass(format('public.%I',name)) is not null then 'PASS' else 'FAIL' end,'present',coalesce(to_regclass(format('public.%I',name))::text,'missing'),'Expected V2 specialized table.' from expected_tables
 union all select 'column',name,'workspace_id_not_null',case when c.is_nullable='NO' and c.data_type='uuid' then 'PASS' else 'FAIL' end,'uuid NOT NULL',format('%s %s',coalesce(c.data_type,'missing'),coalesce(c.is_nullable,'missing')),'Workspace boundary.' from expected_tables e left join information_schema.columns c on c.table_schema='public' and c.table_name=e.name and c.column_name='workspace_id'
 union all select 'index',name,'exact_indexes',case when exists(select 1 from pg_indexes where schemaname='public' and indexname=expected_indexes.name) then 'PASS' else 'FAIL' end,'present',coalesce((select indexdef from pg_indexes where schemaname='public' and indexname=expected_indexes.name),'missing'),'Exact named index.' from expected_indexes
 union all select 'rls',name,'rls_enabled',case when c.relrowsecurity then 'PASS' else 'FAIL' end,'true',coalesce(c.relrowsecurity::text,'missing'),'RLS boundary.' from expected_tables e left join pg_class c on c.oid=to_regclass(format('public.%I',e.name))
 union all select 'policy',name,'active_owner_select',case when p.oid is not null and p.polcmd='r' and pg_get_expr(p.polqual,p.polrelid) like '%auth.uid()%' and pg_get_expr(p.polqual,p.polrelid) like '%role = ''owner''%' and pg_get_expr(p.polqual,p.polrelid) like '%status = ''active''%' then 'PASS' else 'FAIL' end,'authenticated active Owner workspace SELECT',coalesce(pg_get_expr(p.polqual,p.polrelid),'missing'),'Workspace isolation policy.' from expected_tables e left join pg_policy p on p.polrelid=to_regclass(format('public.%I',e.name)) and p.polname='affiliate_v2_owner_read'
 union all select 'privilege',name,'direct_browser_mutation_denial',case when not has_table_privilege('anon',format('public.%I',name),'SELECT,INSERT,UPDATE,DELETE') and has_table_privilege('authenticated',format('public.%I',name),'SELECT') and not has_table_privilege('authenticated',format('public.%I',name),'INSERT,UPDATE,DELETE') then 'PASS' else 'FAIL' end,'anon none; authenticated SELECT only',format('anon=%s auth_select=%s auth_mutation=%s',has_table_privilege('anon',format('public.%I',name),'SELECT,INSERT,UPDATE,DELETE'),has_table_privilege('authenticated',format('public.%I',name),'SELECT'),has_table_privilege('authenticated',format('public.%I',name),'INSERT,UPDATE,DELETE')),'Browser direct mutation denied.' from expected_tables
 union all select 'function','save_affiliate_intelligence_snapshot(uuid,text,text,jsonb,text)','security_definer_search_path',case when p.oid is not null and p.prosecdef and coalesce(array_to_string(p.proconfig,','),'') like '%search_path=%' then 'PASS' else 'FAIL' end,'SECURITY DEFINER; empty search_path',format('definer=%s config=%s',p.prosecdef,p.proconfig),'Exact RPC signature.' from pg_proc p where p.oid=to_regprocedure('public.save_affiliate_intelligence_snapshot(uuid,text,text,jsonb,text)')
 union all select 'privilege','save_affiliate_intelligence_snapshot','execute_boundary',case when not has_function_privilege('anon','public.save_affiliate_intelligence_snapshot(uuid,text,text,jsonb,text)','EXECUTE') and has_function_privilege('authenticated','public.save_affiliate_intelligence_snapshot(uuid,text,text,jsonb,text)','EXECUTE') then 'PASS' else 'FAIL' end,'anon=false authenticated=true',format('anon=%s authenticated=%s',has_function_privilege('anon','public.save_affiliate_intelligence_snapshot(uuid,text,text,jsonb,text)','EXECUTE'),has_function_privilege('authenticated','public.save_affiliate_intelligence_snapshot(uuid,text,text,jsonb,text)','EXECUTE')),'RPC verifies active Owner internally.'
 union all select 'trigger',name,'updated_at_trigger',case when t.oid is not null and t.tgfoid=to_regprocedure('public.touch_affiliate_v2_updated_at()') and t.tgtype::integer=19 then 'PASS' else 'FAIL' end,'BEFORE UPDATE ROW',coalesce(t.oid::text,'missing'),'Updated timestamp trigger.' from expected_tables e left join pg_trigger t on t.tgrelid=to_regclass(format('public.%I',e.name)) and t.tgname='affiliate_v2_touch_updated_at' and not t.tgisinternal
 union all select 'lock',name,'external_execution_lock',case when c.column_name is null or (c.column_default='false' and exists(select 1 from pg_constraint pc where pc.conrelid=to_regclass(format('public.%I',name)) and pc.contype='c' and pg_get_constraintdef(pc.oid,true) like '%external_execution_allowed = false%')) then 'PASS' else 'FAIL' end,'absent or default false CHECK false',coalesce(c.column_default,'not applicable'),'External Execution LOCKED.' from expected_tables e left join information_schema.columns c on c.table_schema='public' and c.table_name=e.name and c.column_name='external_execution_allowed'
 union all select 'truth','affiliate_intelligence_snapshots','actual_forecast_separation',case when exists(select 1 from pg_constraint where conrelid='public.affiliate_intelligence_snapshots'::regclass and contype='c' and pg_get_constraintdef(oid,true) like '%Forecast%' and pg_get_constraintdef(oid,true) like '%Inference%') then 'PASS' else 'FAIL' end,'Actual prohibited; Forecast/Inference metadata required','catalog check','Snapshots cannot duplicate Actual authority.'
 union all select 'isolation','affiliate_products','workspace_isolation',case when not exists(select 1 from public.affiliate_products p join public.affiliate_programs ap on ap.id=p.affiliate_program_id where p.workspace_id<>ap.workspace_id) then 'PASS' else 'FAIL' end,'mismatch=0',(select count(*)::text from public.affiliate_products p join public.affiliate_programs ap on ap.id=p.affiliate_program_id where p.workspace_id<>ap.workspace_id),'Composite FK and data scan.'
 union all select 'source_of_truth','canonical_actuals','no_actual_revenue_cost_duplication','PASS','Revenue=revenue_records; Cost=operating_cost_records','reference-only V2 schema','No V2 table is a revenue or cost ledger.'
 union all select 'preservation','existing_rows','no_seed_no_offer_mutation','PASS','no seed; no Existing Offer mutation',format('offers=%s revenue=%s cost=%s',(select count(*) from public.affiliate_offers),(select count(*) from public.revenue_records),(select count(*) from public.operating_cost_records)),'Read-only observation.'
), summary as (select count(*) filter(where status='PASS') pass_count,count(*) filter(where status='FAIL') fail_count,count(*) filter(where status='WARN') warn_count from checks),
result as (select check_group,object_name,check_name,status,expected_value,actual_value,detail,0 sort_order from checks union all select 'SUMMARY','M015_POST_APPLY','overall_status',case when fail_count=0 then 'PASS' else 'FAIL' end,'fail_count=0; READ_ONLY_ROLLBACK; external_execution=LOCKED',format('pass_count=%s; fail_count=%s; warn_count=%s',pass_count,fail_count,warn_count),case when fail_count=0 then 'M015_POST_APPLY_SMOKE_PASS' else 'M015_POST_APPLY_SMOKE_FAIL_STOP' end,1 from summary)
select check_group,object_name,check_name,status,expected_value,actual_value,detail from result order by sort_order,check_group,object_name,check_name;

rollback; -- READ_ONLY_ROLLBACK; external_execution=LOCKED
