import { useMemo, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import "./next-workspace.css";
import AssistantSecretary from "./AssistantSecretary.jsx";
import { PRIVATE_BETA_INTEGRATIONS } from "../../data/privateBetaIntegrationCatalog.js";
import AiCapabilityCard from "./AiCapabilityCard.jsx";
import OperationalCommandSurface from "./OperationalCommandSurface.jsx";
import InternalActionWorkforce from "./InternalActionWorkforce.jsx";

const UNKNOWN = "未確認";
const PAGE = {
  home:{title:"ホーム",lead:"今日の仕事と判断を、ここから始めます。",tabs:["今日","要確認","進行中","収益","AI提案","通知"]},
  assistant:{title:"AI秘書",lead:"相談内容を整理し、次の作業場所へ安全に案内します。",tabs:["チャット","今日の相談","アイデア","事業相談","収益化相談","履歴","記憶"]},
  goals:{title:"目標・戦略",lead:"目標、優先順位、実行方針を一つの流れで確認します。",tabs:["目標","戦略","今月","優先順位"]},
  sns:{title:"SNS運用",lead:"各SNSを独立して管理。未接続でも手動運用を続けられます。",tabs:["概要","Instagram","Threads","X","TikTok","カレンダー","下書き","投稿済み"]},
  snsAnalytics:{title:"SNS分析",lead:"実データだけを分析し、未接続や未登録をゼロとして扱いません。",tabs:["アカウント","投稿","トレンド","競合","キーワード","Audience","成長","AI分析"]},
  content:{title:"コンテンツ制作",lead:"目的を選び、少ない入力から下書きを始めます。",tabs:["SNS","記事","ライティング","台本","コピー","画像","動画","再利用"]},
  note:{title:"note",lead:"価値のある長文コンテンツを企画し、手動公開まで管理します。",tabs:["企画","下書き","レビュー","公開済み"]},
  affiliate:{title:"アフィリエイト",lead:"Program Master、リンク、規約、実績証拠を混同せず管理します。",tabs:["優先","プログラム","コンテンツ","実績証拠"]},
  opportunities:{title:"仕事を探す",lead:"案件情報を手動登録し、評価から提案準備まで進めます。",tabs:["CrowdWorks","ココナラ","ランサーズ","直接営業","Opportunity Radar"]},
  outreach:{title:"応募・営業",lead:"応募候補、提案準備、送付後の状態を整理します。",tabs:["応募候補","提案準備","送付済み","結果"]},
  projects:{title:"案件・仕事",lead:"獲得した仕事と進行状態を、担当・期限・成果物で確認します。",tabs:["進行中","要確認","完了","保留"]},
  studio:{title:"制作スタジオ",lead:"文章・画像・動画・資料の制作入口をまとめます。",tabs:["すべて","文章","画像","動画","資料"]},
  revenueCenter:{title:"収益管理",lead:"確定売上、見込み、入金、経費、利益を明確に分けます。",tabs:["全体","確定売上","見込み","未入金","入金","経費","利益","案件別","事業別"]},
  crm:{title:"顧客・営業管理",lead:"顧客情報と営業状況を必要最小限で管理します。",tabs:["顧客","商談","フォロー","履歴"]},
  employees:{title:"AI社員",lead:"役割と実行可能範囲を確認します。外部自動実行は停止中です。",tabs:["一覧","担当","タスク","権限"]},
  team:{title:"チーム",lead:"個人領域を共有せず、明示的な共有と権限だけを管理します。",tabs:["メンバー","招待","担当","権限","共有","活動"]},
  knowledge:{title:"Knowledge",lead:"意思決定や学びを、個人と共有の境界を保って蓄積します。",tabs:["自分の知識","共有知識","学び","決定"]},
  analytics:{title:"分析",lead:"事業全体の状態を、実データと未確認を区別して読み解きます。",tabs:["事業","収益","活動","改善"]},
  feedback:{title:"改善BOX",lead:"使いづらさ、不具合、要望を記録して改善につなげます。",tabs:["不具合","使いづらい","要望","欲しい機能","問い合わせ","対応状況"]},
  connectors:{title:"接続・API",lead:"接続状態、読み書き範囲、費用、エラーを安全に確認します。",tabs:["全体","AI","SNS","Google","Canva","ASP","Health","Logs"]},
  safety:{title:"監査・安全",lead:"権限、監査、費用、外部自動実行の安全状態を確認します。",tabs:["監査","権限","費用","実績証拠"]},
  settings:{title:"設定",lead:"アカウント、プライバシー、通知、法的同意を管理します。",tabs:["アカウント","プライバシー","通知","法的同意"]},
  legal:{title:"利用開始前の確認",lead:"必須文書を確認し、明示的に同意するまで利用開始できません。",tabs:["同意確認"]},
};

const STATE_LABEL={ready:"準備完了",manual:"手動運用",unknown:"未確認",blocked:"停止中",coming:"次のフェーズ"};
function State({kind="unknown",children}){return <span className={`next-state next-state--${kind}`}>{children||STATE_LABEL[kind]}</span>}
function Card({title,children,action,className=""}){return <section className={`next-card ${className}`}><header><h2>{title}</h2>{action}</header>{children}</section>}
function Empty({title="データ未登録",children}){return <div className="next-empty"><strong>{title}</strong><p>{children}</p></div>}
function Tabs({tabs}){const [params,setParams]=useSearchParams();const current=tabs.includes(params.get("tab"))?params.get("tab"):tabs[0];return <div className="next-tabs" role="tablist" aria-label="ページ内メニュー">{tabs.map(tab=><button key={tab} role="tab" aria-selected={current===tab} onClick={()=>setParams({tab})}>{tab}</button>)}</div>}

function Home({go}){return <div className="next-grid next-grid--home"><Card title="AI秘書に相談" className="next-card--hero"><p>迷ったら、やりたいことを日本語で入力してください。</p><button className="next-primary" onClick={()=>go("/assistant")}>「今日何をしたらいい？」と相談</button></Card><Card title="今日やること"><ul className="next-list"><li><b>Revenue Sprint 001</b><span>優先アフィリエイトURLを確認</span></li><li><b>Threads下書き</b><span>Ownerレビュー待ち</span></li></ul></Card><Card title="要確認"><Empty title="リンク確認が必要">公式URLが確認できるまで公開準備は停止します。</Empty></Card><Card title="進行中"><p><State kind="manual"/> SNSは手動公開で安全に運用できます。</p></Card><Card title="収益概要"><div className="next-metrics"><span><small>確定売上</small><b>{UNKNOWN}</b></span><span><small>見込み</small><b>{UNKNOWN}</b></span><span><small>利益</small><b>{UNKNOWN}</b></span></div><button className="next-link" onClick={()=>go("/revenue")}>収益管理を開く</button></Card><Card title="AIからの提案"><p>Threads投稿を1件レビューし、公開URLを実績証拠として登録できる状態にしましょう。</p><button className="next-link" onClick={()=>go("/content?tab=SNS")}>投稿を作る</button></Card></div>}

function Assistant({go}){const [input,setInput]=useState("");const [answer,setAnswer]=useState(null);const submit=()=>{const text=input.trim();if(!text)return;const threads=/Threads|投稿/.test(text),work=/CrowdWorks|案件/.test(text),revenue=/収益|売上/.test(text);setAnswer(threads?{text:"Threads用の下書き作成へ進めます。目的と伝えたい内容を入力してください。",path:"/content?tab=SNS",label:"コンテンツ制作を開く"}:work?{text:"案件情報を手動登録し、適合度とリスクを整理できます。",path:"/opportunities?tab=CrowdWorks",label:"CrowdWorks案件を登録"}:revenue?{text:"確定売上・見込み・未入金を分けて確認します。",path:"/revenue",label:"収益管理を開く"}:{text:"現在は無料の決定ルールで相談先を案内します。外部AIによる回答生成は停止中です。",path:"/goals",label:"目標・戦略を開く"});};return <div className="next-grid"><Card title="何を相談しますか？" className="next-card--wide"><div className="next-chat"><label htmlFor="assistant-input">日本語で入力</label><textarea id="assistant-input" value={input} onChange={e=>setInput(e.target.value)} placeholder="例：Threadsの投稿を作りたい"/><div className="next-actions"><button className="next-primary" onClick={submit}>相談を整理する</button><State kind="blocked">外部AI停止中・¥0</State></div></div>{answer?<div className="next-answer" role="status"><p>{answer.text}</p><button className="next-link" onClick={()=>go(answer.path)}>{answer.label}</button></div>:null}</Card><Card title="よく使う相談">{["今日何をしたらいい？","Threadsの投稿を作りたい","CrowdWorksの案件を評価して","収益を見る"].map(x=><button className="next-prompt" key={x} onClick={()=>setInput(x)}>{x}</button>)}</Card><Card title="現在のAI状態"><p><State kind="manual">安全なルーティング</State></p><p>会話内容は他ユーザーに共有されません。外部プロバイダーへの送信はありません。</p></Card></div>}

function ContentCreator(){const [type,setType]=useState("SNS投稿"),[platform,setPlatform]=useState("Threads"),[purpose,setPurpose]=useState("集客"),[topic,setTopic]=useState(""),[draft,setDraft]=useState("");const create=()=>setDraft(topic.trim()?`【${platform}下書き】\n${topic.trim()}について、${purpose}を目的に要点を3つ整理します。\n\nCTA：詳しい内容を確認する\n\n※事実・利用経験・成果は公開前にOwnerが確認してください。`:"");return <div className="next-grid"><Card title="何を作りますか？" className="next-card--wide"><div className="next-choice">{["SNS投稿","note","記事","ライティング","台本","コピー","提案資料","業務改善資料","マニュアル","画像","動画"].map(x=><button key={x} aria-pressed={type===x} onClick={()=>setType(x)}>{x}</button>)}</div><div className="next-form"><label>プラットフォーム<select value={platform} onChange={e=>setPlatform(e.target.value)}><option>Instagram</option><option>Threads</option><option>X</option><option>TikTok</option></select></label><label>目的<select value={purpose} onChange={e=>setPurpose(e.target.value)}><option>集客</option><option>認知</option><option>販売</option><option>Affiliate</option><option>教育</option><option>共感</option><option>その他</option></select></label><label className="next-span">伝えたいこと<textarea value={topic} onChange={e=>setTopic(e.target.value)} placeholder="一番伝えたい内容を短く入力"/></label></div><button className="next-primary" disabled={!topic.trim()} onClick={create}>無料テンプレートで下書き</button></Card>{draft?<Card title="下書き・レビュー" className="next-card--wide"><pre className="next-draft">{draft}</pre><div className="next-actions"><State kind="manual">ローカル下書き</State><button className="next-link">保存準備</button></div></Card>:null}</div>}

function SNS({analytics=false,go}){const platforms=["Instagram","Threads","X","TikTok"];return <div className="next-grid">{platforms.map(name=><Card key={name} title={name} action={<State kind="manual"/>}>{analytics?<Empty title="分析データ未登録">実績URLまたは集計データを追加すると、投稿・成長傾向を確認できます。</Empty>:<><p>公式APIは未接続です。手動公開を前提に安全に運用します。</p><div className="next-actions"><button className="next-link" onClick={()=>go("/content?tab=SNS")}>投稿を作る</button><button className="next-link">実績を入力</button></div></>}</Card>)}{analytics?<Card title="トレンド・AI分析" className="next-card--wide"><Empty title="未接続 / 未確認">データがないためチャートや数値を表示しません。投稿実績を登録すると分析を開始できます。</Empty></Card>:null}</div>}

function Opportunities(){const [saved,setSaved]=useState(false);return <div className="next-grid"><Card title="案件を手動登録" className="next-card--wide"><form className="next-form" onSubmit={e=>{e.preventDefault();setSaved(true)}}><label>プラットフォーム<select name="platform"><option>CrowdWorks</option><option>ココナラ</option><option>ランサーズ</option><option>直接営業</option></select></label><label>案件名<input name="title" required/></label><label>URL<input name="url" type="url" placeholder="https://"/></label><label>報酬<input name="compensation" inputMode="numeric"/></label><label className="next-span">仕事内容<textarea name="description" required/></label><button className="next-primary" type="submit">ローカル評価を準備</button></form>{saved?<div className="next-answer" role="status"><b>提案準備へ進めます</b><p>保存先はまだ接続されていません。入力内容はこの画面の一時状態で、永続保存されていません。</p></div>:null}</Card><Card title="評価項目"><ul><li>適合度：未確認</li><li>想定作業：未確認</li><li>想定利益：未確認</li><li>リスク：手動確認</li><li>提案推奨：未確認</li></ul></Card></div>}

function Revenue(){return <div className="next-grid"><Card title="収益の全体像" className="next-card--wide"><div className="next-metrics next-metrics--six">{["確定売上","見込み","未入金","入金済み","経費","利益"].map(label=><span key={label}><small>{label}</small><b>{UNKNOWN}</b></span>)}</div><p className="next-note">確定売上は実績証拠で検証された記録だけです。見込みや未確認をゼロまたは確定として表示しません。</p></Card><Card title="収益源"><p>CrowdWorks / ココナラ / ランサーズ / SNS運用 / 動画編集 / ライティング / 資料制作 / Affiliate / note / 直接顧客 / その他</p></Card><Card title="次の操作"><Empty title="実績証拠待ち">受注・入金・ASP成果の証拠を登録してから確定売上へ進めます。</Empty></Card></div>}

function Team(){return <div className="next-grid"><Card title="メンバー"><p><State kind="ready">Owner</State> アカウント状態と権限設定を管理できます。</p><p><State kind="coming">Member</State> Beta招待は永続同意・RLS確認後に有効化します。</p></Card><Card title="プライバシー境界"><ul><li>個人ワークスペースは本人だけが閲覧</li><li>Owner権限でも私的会話やSNS生データを通常閲覧しない</li><li>共有は明示したデータだけ</li><li>AI検索にも同じ権限境界を適用</li></ul></Card><Card title="招待・権限"><Empty title="永続化には追加実装が必要">UIで権限を隠すだけでは有効化しません。追加RLSと同意記録が必要です。</Empty></Card></div>}

function Feedback(){const [sent,setSent]=useState(false);return <Card title="意見・不具合を送る" className="next-card--wide"><form className="next-form" onSubmit={e=>{e.preventDefault();setSent(true)}}><label>種類<select><option>使いにくい</option><option>分かりにくい</option><option>不具合</option><option>欲しい機能</option><option>AI回答</option><option>表示</option><option>その他</option></select></label><label className="next-span">内容<textarea required/></label><label className="next-span">どうなれば良い？<textarea/></label><label>スクリーンショット<input type="file" accept="image/*"/></label><button className="next-primary" type="submit">一時保存して確認</button></form>{sent?<div className="next-answer" role="status">この内容はローカル一時状態です。永続保存は未実装で、送信されていません。</div>:null}</Card>}

const CONNECTOR_PURPOSE={openai:"AI回答生成",gemini:"AI Secretary候補",google:"Google OAuth基盤",gmail:"メールmetadata読取",calendar:"予定・空き時間読取",drive:"file metadata読取",analytics:"site分析読取",search_console:"検索performance読取",youtube:"channel・video metadata読取",canva:"design連携",anthropic:"長文review候補",perplexity:"調査・出典候補",a8:"Affiliate実績",instagram_threads:"投稿・分析候補",x:"投稿・分析候補",tiktok:"投稿・分析候補"};
function Connectors(){const rows=PRIVATE_BETA_INTEGRATIONS.map(item=>[item.label,item.state,CONNECTOR_PURPOSE[item.provider],item.read,"LOCKED",item.cost]);return <Card title="コネクター状態" className="next-card--wide"><div className="next-table" role="table"><div role="row" className="next-table__head"><b>名前</b><b>状態</b><b>用途</b><b>読取</b><b>書込</b><b>費用</b></div>{rows.map(row=><div role="row" key={row[0]}>{row.map((x,i)=><span role="cell" key={i}>{x}</span>)}</div>)}</div><p className="next-note">認証情報、トークン、接続URLは表示しません。自動pollingなし。Send / Publish / DeleteはLOCKEDです。</p></Card>}

const LEGAL_DOCS=[["利用規約","TERMS_1.0",true],["プライバシーポリシー","PRIVACY_1.0",true],["AI機能・データ処理に関する説明","AI_NOTICE_1.0",true],["外部サービス連携に関する説明","EXTERNAL_SERVICES_1.0",true],["匿名化・抽象化された利用傾向の提供","LEARNING_OPT_IN_1.0",false]];
function LegalGate(){const [accepted,setAccepted]=useState({});const required=LEGAL_DOCS.filter(x=>x[2]);const ready=required.every(x=>accepted[x[1]]);return <div className="next-grid"><Card title="必須文書の確認" className="next-card--wide"><p className="next-warning">DRAFT — LEGAL REVIEW REQUIRED</p>{LEGAL_DOCS.map(([title,version,mandatory])=><div className="next-consent" key={version}><div><b>{title}</b><small>{version}・{mandatory?"必須":"任意"}</small><button className="next-link" type="button">全文を開く</button></div><label><input type="checkbox" checked={Boolean(accepted[version])} onChange={e=>setAccepted({...accepted,[version]:e.target.checked})}/>{mandatory?"内容を確認し、同意します":"任意で同意します"}</label></div>)}<button className="next-primary" disabled={!ready}>同意記録を作成して利用開始</button><p className="next-note">このチェックポイントでは永続同意記録を作成しません。データベース移行とサーバー側有効化ゲートが実装されるまでボタンは製品有効化に接続されません。</p></Card><Card title="アカウント状態"><p><State kind={ready?"manual":"blocked"}>{ready?"同意入力済み・永続化待ち":"同意必須"}</State></p><p>必須同意がない新規アカウントは通常機能へ進めない設計です。</p></Card></div>}

function Generic({page}){const useful={goals:"今月の最優先目標と判断基準を登録します。",note:"長文企画を作成し、Ownerレビュー後に手動公開します。",outreach:"案件を選び、提案文を準備して手動送付します。",projects:"受注済み案件の担当、期限、成果物を確認します。",studio:"作りたい成果物を選び、コンテンツ制作へ進みます。",crm:"必要最小限の顧客情報と次の営業行動を管理します。",employees:"AI社員は権限内で準備・分析だけを行い、外部実行しません。",knowledge:"個人知識と共有知識を分離し、確認済みの学びだけを残します。",analytics:"接続済みの実データだけを分析し、欠損値は未確認と表示します。",safety:"外部自動実行は停止中、Paid AIは¥0、実績は証拠必須です。",settings:"プライバシーと法的同意を確認できます。",affiliate:"既存のAffiliate Program Masterは保持されています。"};return <div className="next-grid"><Card title="この場所でできること" className="next-card--wide"><p>{useful[page]||"業務の準備と確認を行います。"}</p><div className="next-actions"><State kind="manual"/><State kind="blocked">外部自動実行は停止中</State></div></Card><Card title="次のアクション"><Empty title="段階的に提供">現在の安全な手動フローを使い、接続や永続化が必要な機能は明示します。</Empty></Card></div>}

export default function NextWorkspace({page="home",client=null}){const config=PAGE[page]||PAGE.home,navigate=useNavigate();const body=useMemo(()=>{if(page==="home")return <Home go={navigate}/>;if(page==="assistant")return <AssistantSecretary/>;if(page==="content")return <ContentCreator/>;if(page==="sns")return <SNS go={navigate}/>;if(page==="snsAnalytics")return <SNS analytics go={navigate}/>;if(page==="opportunities")return <Opportunities/>;if(page==="revenueCenter")return <Revenue/>;if(page==="team")return <Team/>;if(page==="feedback")return <Feedback/>;if(page==="connectors")return <Connectors/>;if(page==="legal")return <LegalGate/>;return <Generic page={page}/>},[page,navigate]);const operationalPages=new Set(["goals","sns","snsAnalytics","note","outreach","studio","crm","knowledge","analytics","safety","settings"]);return <main className="next-workspace"><header className="next-header"><div><span>KEVIRIO NEXT</span><h1>{config.title}</h1><p>{config.lead}</p></div><div className="next-header__state"><State kind="blocked">外部自動実行 停止中</State><small>Paid AI ¥0</small></div></header><Tabs tabs={config.tabs}/>{body}{client&&page==="employees"?<InternalActionWorkforce client={client}/>:null}{client&&operationalPages.has(page)?<OperationalCommandSurface client={client} showCapture={page==="note"} heading={config.title}/>:null}{page!=="assistant"&&page!=="legal"?<AiCapabilityCard feature={page}/>:null}{page!=="feedback"?<button className="next-feedback-fab" onClick={()=>navigate("/feedback")}>意見・不具合を送る</button>:null}</main>}
