import { useEffect, useState } from "react";
import { friendlyError } from "./nextUx.js";
const STATE={INVITED:"招待済み",REGISTERING:"登録手続き中",CONSENT_REQUIRED:"同意が必要",ACTIVE:"利用中",SUSPENDED:"利用停止中",DEACTIVATED:"無効"};
const ROLE={owner:"管理者",member:"メンバー"};
export default function NextTeamAdministration({session}){
  const[members,setMembers]=useState([]),[email,setEmail]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(false);
  const call=async body=>{const response=await fetch("/api/members",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${session?.access_token||""}`},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.reasonCode||"MEMBER_ADMIN_FAILED");return result};
  const inspect=async()=>{try{return await call({action:"inspect"})}catch{await new Promise(resolve=>window.setTimeout(resolve,300));return call({action:"inspect"})}};
  const load=async()=>{setLoading(true);setLoadError(false);try{const result=await inspect();setMembers(result.members);setMessage("")}catch(error){setLoadError(true);setMessage(friendlyError(error,"チーム情報を読み込めませんでした。通信状態を確認して、もう一度お試しください。"))}finally{setLoading(false)}};
  useEffect(()=>{load()},[session?.access_token]);
  const invite=async event=>{event.preventDefault();try{await call({action:"invite",email});setEmail("");await load();setMessage("招待メールを送信しました。")}catch(error){setMessage(friendlyError(error))}};
  const transition=async(action,targetUserId)=>{if(!window.confirm(action==="deactivate"?"このメンバーを無効化しますか？":"アカウント状態を変更しますか？"))return;try{await call({action,targetUserId});await load();setMessage("アカウント状態を更新しました。")}catch(error){setMessage(friendlyError(error))}};
  return <main className="next-workspace"><header className="next-header"><div><span>KEVIRIO NEXT</span><h1>チーム管理</h1><p>アカウント状態だけを管理します。個人のコンテンツは表示しません。</p></div></header><section className="next-card"><header><h2>メンバーを招待</h2></header><form className="next-form" onSubmit={invite}><label>メールアドレス<input type="email" value={email} onChange={event=>setEmail(event.target.value)} required autoComplete="email"/></label><button className="next-primary">招待メールを送る</button></form></section><section className="next-card next-card--wide"><header><h2>メンバー</h2></header>{loading?<p role="status">メンバーを読み込んでいます。</p>:members.length?<div className="next-table" role="table" aria-label="チームメンバー一覧">{members.map(member=><div role="row" key={member.id}><span role="cell">{member.email||"メール未確認"}</span><span role="cell">{ROLE[member.role]||"メンバー"}</span><span role="cell">{member.invitationState==="ACCEPTED"?"登録済み":member.invitationState==="INVITED"?"招待済み":"登録手続き中"}</span><span role="cell">{STATE[member.accountState]||"状態を確認できません"}</span><span role="cell">参加先 {member.memberships.length}件</span><span role="cell" className="next-actions">{member.accountState==="SUSPENDED"?<button onClick={()=>transition("reactivate",member.id)}>利用を再開</button>:member.accountState!=="DEACTIVATED"?<button onClick={()=>transition("suspend",member.id)}>一時停止</button>:null}{member.accountState!=="DEACTIVATED"?<button onClick={()=>transition("deactivate",member.id)}>無効化</button>:null}</span></div>)}</div>:<div className="next-empty"><strong>招待したメンバーはいません</strong><p>上のフォームからメールアドレスを入力して招待できます。</p></div>}{message?<p role={loadError?"alert":"status"}>{message}</p>:null}{loadError?<button type="button" className="next-link" onClick={load}>もう一度試す</button>:null}</section><section className="next-card next-card--wide"><header><h2>プライバシー</h2></header><p>チームに参加しても個人データは自動共有されません。明示的に共有された情報またはチーム用情報だけを利用できます。管理者権限は個人データの閲覧権限ではありません。</p></section></main>;
}
