import { useEffect, useState } from "react";
import { acceptCurrentLegalDocuments, listPersonalRecords, loadCurrentLegalDocuments, resolvePersonalWorkspace, savePersonalRecord } from "../../repositories/personalWorkspaceRepository.js";
import { friendlyError } from "./nextUx.js";

const Card=({title,children})=><section className="next-card next-card--wide"><header><h2>{title}</h2></header>{children}</section>;
const resultMessage=(error,success)=>error?friendlyError(error,"保存できませんでした。通信状態を確認して、もう一度お試しください。"):success;
function useRecords(client,recordType){const[state,setState]=useState({loading:true,workspaceId:null,records:[]});const reload=async()=>{try{const workspaceId=await resolvePersonalWorkspace(client);const records=await listPersonalRecords(client,{workspaceId,recordType});setState({loading:false,workspaceId,records});return workspaceId}catch(error){setState({loading:false,workspaceId:null,records:[],error});return null}};useEffect(()=>{if(client)reload();else setState({loading:false,workspaceId:null,records:[],error:new Error("supabase_client_required")})},[client,recordType]);return[state,reload]}

export function DurableContent({client}){const[state,reload]=useRecords(client,"CONTENT"),[topic,setTopic]=useState(""),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);useEffect(()=>{const warn=event=>{if(topic.trim()){event.preventDefault();event.returnValue=""}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[topic]);const save=async()=>{setSaving(true);setMessage("");try{await savePersonalRecord(client,{workspaceId:state.workspaceId,recordType:"CONTENT",title:topic,payload:{content_type:"SNS_POST",platform:"THREADS",body:topic,status:"DRAFT"},lifecycleStatus:"DRAFT"});setTopic("");setMessage("Threadsの下書きを保存しました。");await reload()}catch(error){setMessage(resultMessage(error,""))}finally{setSaving(false)}};return <div className="next-grid"><Card title="Threads下書き"><label className="next-form next-span">投稿内容<textarea value={topic} onChange={event=>setTopic(event.target.value)} placeholder="伝えたいことを入力してください"/></label><div className="next-actions"><button className="next-primary" disabled={!topic.trim()||!state.workspaceId||saving} onClick={save}>{saving?"保存中…":"非公開で保存"}</button><span>自分だけが閲覧できます</span></div>{topic.trim()?<p className="next-note">未保存の変更があります。</p>:null}{message?<p role="status">{message}</p>:null}</Card><Card title="保存済み下書き">{state.loading?<p role="status">下書きを読み込んでいます。</p>:state.error?<div className="next-empty"><strong>下書きを表示できません</strong><p>通信状態を確認して、もう一度お試しください。</p><button className="next-link" onClick={reload}>もう一度試す</button></div>:state.records.length?<ul className="next-list">{state.records.map(record=><li key={record.id}><b>{record.title||"無題"}</b><span>Threads / 下書き / 自分だけ</span></li>)}</ul>:<div className="next-empty"><strong>まだ下書きはありません</strong><p>左の入力欄から最初の投稿を作れます。</p></div>}</Card></div>}

export function DurableOpportunities({client}){const[state,reload]=useRecords(client,"OPPORTUNITY"),[message,setMessage]=useState("");const submit=async event=>{event.preventDefault();const formElement=event.currentTarget,form=new FormData(formElement);try{await savePersonalRecord(client,{workspaceId:state.workspaceId,recordType:"OPPORTUNITY",title:String(form.get("title")||""),payload:{platform:String(form.get("platform")),url:String(form.get("url")||""),description:String(form.get("description")||""),status:"SAVED"},lifecycleStatus:"ACTIVE"});formElement.reset();setMessage("案件を非公開で保存しました。");await reload()}catch(error){setMessage(resultMessage(error,""))}};return <div className="next-grid"><Card title="案件を手動登録"><form className="next-form" onSubmit={submit}><label>プラットフォーム<select name="platform"><option value="CROWDWORKS">CrowdWorks</option><option value="COCONALA">ココナラ</option><option value="LANCERS">ランサーズ</option><option value="DIRECT">直接営業</option><option value="OTHER">その他</option></select></label><label>案件名<input name="title" required/></label><label>URL<input name="url" type="url"/></label><label className="next-span">仕事内容<textarea name="description" required/></label><button className="next-primary" disabled={!state.workspaceId}>非公開で保存</button></form>{message?<p role="status">{message}</p>:null}</Card><Card title="登録済み案件">{state.records.length?<ul className="next-list">{state.records.map(record=><li key={record.id}><b>{record.title}</b><span>{record.payload?.platform} / {record.payload?.status}</span></li>)}</ul>:<p>登録した案件はまだありません。</p>}</Card></div>}

export function DurableFeedback({client,route="/feedback"}){const[state,reload]=useRecords(client,"FEEDBACK"),[message,setMessage]=useState(""),[refreshWarning,setRefreshWarning]=useState("");const submit=async event=>{event.preventDefault();const formElement=event.currentTarget,form=new FormData(formElement);setRefreshWarning("");try{await savePersonalRecord(client,{workspaceId:state.workspaceId,recordType:"FEEDBACK",title:String(form.get("category")),payload:{category:String(form.get("category")),message:String(form.get("message")),desired_outcome:String(form.get("desired_outcome")||""),route,status:"OPEN"},lifecycleStatus:"ACTIVE"});formElement.reset();setMessage("ご意見を非公開で保存しました。");const refreshed=await reload();if(!refreshed)setRefreshWarning("保存済みですが、一覧の再読み込みに失敗しました。通信状態を確認してください。")}catch(error){setMessage(resultMessage(error,""))}};return <Card title="意見・不具合を送る"><form className="next-form" onSubmit={submit}><label>種類<select name="category">{["使いにくい","分かりにくい","不具合","欲しい機能","AI回答","表示","その他"].map(value=><option key={value}>{value}</option>)}</select></label><label className="next-span">内容<textarea name="message" required/></label><label className="next-span">どうなれば良い？<textarea name="desired_outcome"/></label><button className="next-primary" disabled={!state.workspaceId}>非公開で保存</button></form>{message?<p role="status">{message}</p>:null}{refreshWarning?<p className="next-warning" role="alert">{refreshWarning}</p>:null}<p className="next-note">Ownerを含む他ユーザーには自動共有されません。サポート提出経路は別途設計が必要です。</p></Card>}

const LABEL={TERMS:"利用規約",PRIVACY:"プライバシーポリシー",AI_NOTICE:"AI機能・データ処理に関する説明",EXTERNAL_SERVICES_NOTICE:"外部サービス連携に関する説明"};
export function DurableLegal({client}){const[docs,setDocs]=useState([]),[accepted,setAccepted]=useState({}),[workspaceId,setWorkspaceId]=useState(null),[message,setMessage]=useState("");useEffect(()=>{if(!client)return;Promise.all([loadCurrentLegalDocuments(client),resolvePersonalWorkspace(client)]).then(([nextDocs,nextWorkspace])=>{setDocs(nextDocs);setWorkspaceId(nextWorkspace)}).catch(error=>setMessage(resultMessage(error,"")))},[client]);const required=docs.filter(doc=>doc.mandatory),ready=required.length>0&&required.every(doc=>accepted[doc.id]);const accept=async()=>{try{await acceptCurrentLegalDocuments(client,{documents:required,workspaceId});setMessage("現在の必須文書への同意を記録しました。")}catch(error){setMessage(resultMessage(error,""))}};return <div className="next-grid"><Card title="必須文書の確認"><p className="next-warning">DRAFT — LEGAL REVIEW REQUIRED / PRIVATE BETA ONLY</p>{docs.map(doc=><div className="next-consent" key={doc.id}><div><b>{LABEL[doc.document_type]||doc.document_type}</b><small>{doc.document_version}{doc.effective_at?` / ${new Date(doc.effective_at).toLocaleDateString("ja-JP")}`:""}</small>{doc.content_reference?<a className="next-link" href={doc.content_reference} target="_blank" rel="noreferrer">全文を開く</a>:null}</div>{doc.mandatory?<label><input type="checkbox" checked={Boolean(accepted[doc.id])} onChange={event=>setAccepted({...accepted,[doc.id]:event.target.checked})}/>内容を確認し、同意します</label>:null}</div>)}<button className="next-primary" disabled={!ready||!workspaceId} onClick={accept}>同意を記録して利用開始</button>{message?<p role="status">{message}</p>:null}</Card></div>}
