import{useEffect,useState}from"react";import{listPersonalRecords,resolvePersonalWorkspace,savePersonalRecord,transitionPersonalOpportunity}from"../../repositories/personalWorkspaceRepository.js";import"./next-workspace.css";

const LABEL={SAVED:"保存",EVALUATING:"検討中",APPLYING:"応募準備中",APPLIED:"応募済み",WON:"受注",LOST:"不成立",ARCHIVED:"アーカイブ"};
const NEXT={SAVED:["EVALUATING","ARCHIVED"],EVALUATING:["APPLYING","LOST","ARCHIVED"],APPLYING:["APPLIED","LOST","ARCHIVED"],APPLIED:["WON","LOST","ARCHIVED"],WON:["ARCHIVED"],LOST:["ARCHIVED"],ARCHIVED:[]};
export default function NextOpportunityLifecyclePage({client}){
  const[workspaceId,setWorkspaceId]=useState(null),[records,setRecords]=useState([]),[message,setMessage]=useState(""),[saving,setSaving]=useState(false),[transitioning,setTransitioning]=useState("");
  const reload=async()=>{const id=await resolvePersonalWorkspace(client);setWorkspaceId(id);setRecords(await listPersonalRecords(client,{workspaceId:id,recordType:"OPPORTUNITY"}))};
  useEffect(()=>{reload().catch(()=>setMessage("案件を読み込めませんでした。通信状態を確認してください。"))},[client]);
  const create=async event=>{event.preventDefault();if(saving)return;const formElement=event.currentTarget,form=new FormData(formElement);setSaving(true);setMessage("");try{await savePersonalRecord(client,{workspaceId,recordType:"OPPORTUNITY",title:String(form.get("title")),payload:{platform:String(form.get("platform")),description:String(form.get("description")),status:"SAVED"},lifecycleStatus:"ACTIVE"});formElement.reset();setMessage("案件を非公開で保存しました。");await reload()}catch{setMessage("保存できませんでした。通信状態と入力内容を確認してください。")}finally{setSaving(false)}};
  const transition=async(record,status)=>{const key=`${record.id}:${status}`;if(transitioning)return;setTransitioning(key);try{await transitionPersonalOpportunity(client,{opportunityId:record.id,nextStatus:status,createActiveWork:status==="WON"});setMessage(status==="WON"?"受注案件として仕事を開始しました。元の案件を安全に追跡できます。":"状態を更新しました。");await reload()}catch{setMessage("状態を更新できませんでした。現在の状態を確認してください。")}finally{setTransitioning("")}};
  return <main className="next-workspace"><header className="next-header"><div><span>KEVIRIO NEXT</span><h1>仕事を探す</h1><p>案件は個人ワークスペースへ非公開で保存されます。</p></div></header><section className="next-card next-card--wide"><header><h2>案件を登録</h2></header><form className="next-form" onSubmit={create}><label>プラットフォーム<select name="platform"><option value="CROWDWORKS">CrowdWorks</option><option value="COCONALA">ココナラ</option><option value="LANCERS">ランサーズ</option><option value="DIRECT">直接営業</option><option value="OTHER">その他</option></select></label><label>案件名<input name="title" required/></label><label className="next-span">仕事内容<textarea name="description" required/></label><button className="next-primary" disabled={!workspaceId||saving}>{saving?"保存中…":"非公開で保存"}</button></form></section><section className="next-card next-card--wide"><header><h2>登録済み案件</h2></header>{records.length?<ul className="next-list">{records.map(record=>{const status=record.payload?.status||"SAVED";return <li key={record.id}><b>{record.title}</b><span>{record.payload?.platform} / {LABEL[status]}</span><div className="next-actions">{NEXT[status].map(next=><button className="next-link" disabled={Boolean(transitioning)} key={next} onClick={()=>transition(record,next)}>{transitioning===`${record.id}:${next}`?"更新中…":LABEL[next]}</button>)}</div>{record.payload?.active_work?<small>進行中の仕事・元の案件を追跡可能</small>:null}</li>})}</ul>:<p>登録した案件はまだありません。</p>}{message?<p role="status">{message}</p>:null}</section></main>;
}
