import{useCallback,useEffect,useMemo,useState}from"react";
import{archiveOperationalObject,ATTENTION_STATES,CAPTURE_INTENTS,loadOperationalCommandContext,operationalAttention,saveOperationalObject,searchOperationalContext}from"../../repositories/operationalRepository.js";
import{friendlyError}from"./nextUx.js";

const LABEL={IDEA:"アイデア",TASK:"タスク",MEMO:"メモ",IMPROVEMENT:"改善",AFFILIATE_CANDIDATE:"Affiliate候補",CONTENT_IDEA:"コンテンツ案",WORK_OPPORTUNITY:"仕事候補",RESEARCH_REQUEST:"調査依頼"};
const Card=({title,children,className=""})=><section className={`next-card ${className}`}><header><h2>{title}</h2></header>{children}</section>;

export default function OperationalCommandSurface({client,showCapture=true,heading="オペレーション"}){
 const[state,setState]=useState({loading:true,objects:[],timeline:[],error:null}),[query,setQuery]=useState(""),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
 const reload=useCallback(async()=>{setState(value=>({...value,loading:true,error:null}));try{const context=await loadOperationalCommandContext(client);setState({loading:false,...context,error:null})}catch(error){setState({loading:false,objects:[],timeline:[],error})}},[client]);
 useEffect(()=>{reload()},[reload]);
 const attention=useMemo(()=>operationalAttention(state.objects),[state.objects]),results=useMemo(()=>searchOperationalContext(state.objects,query),[state.objects,query]);
 const submit=async event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form);setSaving(true);setMessage("");try{await saveOperationalObject(client,{intent:String(data.get("intent")),title:String(data.get("title")),summary:String(data.get("summary")||""),attentionState:String(data.get("attention")||"")||null,dueAt:String(data.get("due_at")||"")||null});form.reset();setMessage("保存しました。別の端末からも再開できます。");await reload()}catch(error){setMessage(friendlyError(error,"保存できませんでした。入力内容はこの画面に残っています。通信状態を確認して再試行してください。"))}finally{setSaving(false)}};
 const archive=async item=>{if(!window.confirm(`「${item.title}」をアーカイブしますか？`))return;try{await archiveOperationalObject(client,{id:item.id,version:item.version});setMessage("アーカイブしました。");await reload()}catch(error){setMessage(friendlyError(error,"更新競合または通信エラーです。再読み込みして確認してください。"))}};
 return <div className="next-grid" aria-busy={state.loading}>{showCapture?<Card title="クイックキャプチャ" className="next-card--wide"><form className="next-form" onSubmit={submit}><label>種類<select name="intent">{CAPTURE_INTENTS.map(value=><option value={value} key={value}>{LABEL[value]}</option>)}</select></label><label>注意状態<select name="attention"><option value="">指定なし</option>{ATTENTION_STATES.map(value=><option key={value}>{value}</option>)}</select></label><label className="next-span">タイトル<input name="title" required maxLength={300}/></label><label className="next-span">内容<textarea name="summary" maxLength={4000}/></label><label>期限<input type="datetime-local" name="due_at"/></label><button className="next-primary" disabled={saving||!client}>{saving?"保存中…":"サーバーへ保存"}</button></form>{message?<p role="status">{message}</p>:null}</Card>:null}<Card title={`${heading}検索`} className="next-card--wide"><label className="next-span">自分の保存済み情報を検索<input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="タイトル・内容・種類"/></label>{query?(results.length?<ul className="next-list">{results.map(item=><li key={item.id}><b>{item.title}</b><span>{LABEL[item.details?.intent]||item.object_type} / {item.attention_state||"通常"}</span><button className="next-link" onClick={()=>archive(item)}>アーカイブ</button></li>)}</ul>:<p>一致する記録はありません。</p>):<p className="next-note">検索結果は認証済みPersonal Workspace内だけです。</p>}</Card><Card title="要対応">{attention.length?<ul className="next-list">{attention.slice(0,10).map(item=><li key={item.id}><b>{item.title}</b><span>{item.computed_attention}{item.due_at?` / ${new Date(item.due_at).toLocaleString("ja-JP")}`:""}</span></li>)}</ul>:<p>現在、要対応として登録された項目はありません。</p>}</Card><Card title="最近の活動">{state.timeline.length?<ul className="next-list">{state.timeline.slice(0,10).map(event=><li key={event.id}><b>{event.event_type}</b><span>{event.object_type} / {new Date(event.created_at).toLocaleString("ja-JP")}</span></li>)}</ul>:<p>活動履歴はまだありません。</p>}</Card>{state.error?<Card title="読み込みエラー"><p role="alert">情報を読み込めませんでした。</p><button className="next-link" onClick={reload}>再試行</button></Card>:null}</div>
}
