-- C. Roll back M029. Independent SQL Editor execution unit.
begin;
drop function if exists public.convert_canonical_domain_object(text,uuid,text,jsonb,text,jsonb);
revoke all on function public.save_canonical_domain_object(text,uuid,bigint,jsonb,text),public.save_personal_operational_record_v2(uuid,text,text,jsonb,text,bigint,text),public.save_canonical_domain_draft(text,uuid,bigint,bigint,jsonb,text),public.archive_canonical_domain_object(text,uuid,bigint,text),public.link_canonical_domain_objects(text,uuid,text,uuid,text,jsonb) from public,anon,authenticated,service_role;
drop function public.link_canonical_domain_objects(text,uuid,text,uuid,text,jsonb);
drop function public.archive_canonical_domain_object(text,uuid,bigint,text);
drop function public.save_canonical_domain_object(text,uuid,bigint,jsonb,text);
drop function public.save_canonical_domain_draft(text,uuid,bigint,bigint,jsonb,text);
drop function public.save_personal_operational_record_v2(uuid,text,text,jsonb,text,bigint,text);
drop function public.m029_append_event(uuid,uuid,text,uuid,text,bigint,text,jsonb);
drop function public.m029_owned_reference_exists(text,uuid,uuid,uuid);
drop table public.canonical_domain_conversions;
drop table public.canonical_domain_drafts;
drop index if exists public.clients_owner_updated_idx;
drop index if exists public.campaigns_owner_updated_idx;
drop index if exists public.tasks_owner_due_idx;
drop index if exists public.content_assets_owner_updated_idx;
drop index if exists public.memory_owner_updated_idx;
drop policy if exists clients_private_read on public.clients;
drop policy if exists opportunities_private_read on public.opportunities;
drop policy if exists owner_decisions_private_read on public.owner_decisions;
drop policy if exists campaigns_private_read on public.campaigns;
drop policy if exists tasks_private_read on public.tasks;
drop policy if exists content_assets_private_read on public.content_assets;
drop policy if exists business_memory_private_read on public.business_memory_records;
create policy clients_member_all on public.clients for all to authenticated using(public.is_active_workspace_member(workspace_id)) with check(public.is_active_workspace_member(workspace_id));
create policy opportunities_member_all on public.opportunities for all to authenticated using(public.is_active_workspace_member(workspace_id)) with check(public.is_active_workspace_member(workspace_id));
create policy owner_decisions_member_all on public.owner_decisions for all to authenticated using(public.is_active_workspace_member(workspace_id)) with check(public.is_active_workspace_member(workspace_id));
create policy campaigns_member_all on public.campaigns for all to authenticated using(public.is_active_workspace_member(workspace_id)) with check(public.is_active_workspace_member(workspace_id));
create policy tasks_member_all on public.tasks for all to authenticated using(public.is_active_workspace_member(workspace_id)) with check(public.is_active_workspace_member(workspace_id));
create policy business_memory_member_all on public.business_memory_records for all to authenticated using(public.is_active_workspace_member(workspace_id)) with check(public.is_active_workspace_member(workspace_id));
create policy company_owner_read on public.content_assets for select to authenticated using(exists(select 1 from public.workspace_members wm where wm.workspace_id=content_assets.workspace_id and wm.user_id=auth.uid() and wm.role='owner' and wm.status='active'));
alter table public.clients no force row level security;
alter table public.opportunities no force row level security;
alter table public.owner_decisions no force row level security;
alter table public.campaigns no force row level security;
alter table public.tasks no force row level security;
alter table public.content_assets no force row level security;
alter table public.business_memory_records no force row level security;
alter table public.personal_operational_records drop column version;
alter table public.business_memory_records drop column visibility,drop column data_owner_id,drop column version;
alter table public.content_assets drop column visibility,drop column data_owner_id;
alter table public.tasks drop column visibility,drop column data_owner_id,drop column version;
alter table public.campaigns drop column visibility,drop column data_owner_id;
alter table public.owner_decisions drop column visibility,drop column version;
alter table public.opportunities drop column visibility;
alter table public.clients drop column visibility,drop column data_owner_id,drop column version;
create or replace function public.m028_reference_exists(p_type text,p_id uuid,p_owner uuid,p_workspace uuid)
returns boolean language plpgsql stable security definer set search_path='' as $$
begin
  if p_id is null or p_owner is null or p_workspace is null or not exists(select 1 from public.account_personal_workspaces where user_id=p_owner and workspace_id=p_workspace) then return false;end if;
  case p_type
    when 'GOAL' then return exists(select 1 from public.campaigns where id=p_id and workspace_id=p_workspace and status not in('closed','cancelled'));
    when 'STRATEGY' then return exists(select 1 from public.owner_decisions where id=p_id and workspace_id=p_workspace and decided_by=p_owner and is_active);
    when 'WORK' then return exists(select 1 from public.tasks where id=p_id and workspace_id=p_workspace and status<>'cancelled');
    when 'APPLICATION' then return exists(select 1 from public.opportunities where id=p_id and workspace_id=p_workspace and created_by=p_owner and status not in('rejected','expired'));
    when 'CLIENT' then return exists(select 1 from public.clients where id=p_id and workspace_id=p_workspace and status<>'archived');
    when 'CONTENT' then return exists(select 1 from public.personal_operational_records where id=p_id and workspace_id=p_workspace and data_owner_id=p_owner and record_type='CONTENT' and lifecycle_status not in('ARCHIVED','DELETED'));
    when 'SNS_ITEM' then return exists(select 1 from public.content_assets where id=p_id and workspace_id=p_workspace and asset_type in('sns_post','thread','short_video_script','long_video_script') and status<>'archived');
    when 'KNOWLEDGE' then return exists(select 1 from public.business_memory_records where id=p_id and workspace_id=p_workspace and deletion_status='active');
    when 'IMPROVEMENT' then return exists(select 1 from public.personal_operational_records where id=p_id and workspace_id=p_workspace and data_owner_id=p_owner and record_type='FEEDBACK' and lifecycle_status not in('ARCHIVED','DELETED'));
    when 'GLOBAL_OPPORTUNITY' then return exists(select 1 from public.research_findings where id=p_id and workspace_id=p_workspace and owner_user_id=p_owner and research_domain='OPPORTUNITY' and status='ACTIVE');
    when 'RESEARCH_PACKAGE' then return exists(select 1 from public.operational_objects where id=p_id and workspace_id=p_workspace and owner_user_id=p_owner and object_type='RESEARCH_PACKAGE' and lifecycle_status<>'ARCHIVED');
    when 'QUICK_CAPTURE' then return exists(select 1 from public.operational_objects where id=p_id and workspace_id=p_workspace and owner_user_id=p_owner and object_type='QUICK_CAPTURE' and lifecycle_status<>'ARCHIVED');
    when 'AI_THREAD' then return exists(select 1 from public.ai_conversation_threads where id=p_id and workspace_id=p_workspace and owner_user_id=p_owner and status<>'ARCHIVED');
    when 'AFFILIATE_PROGRAM' then return exists(select 1 from public.affiliate_program_master where id=p_id and workspace_id=p_workspace and program_status<>'EXPIRED');
    else return false;
  end case;
end; $$;
commit;
