begin read only;
with current_rows as(
 select 'clients' t,id,to_jsonb(x) j from public.clients x union all select 'opportunities',id,to_jsonb(x) from public.opportunities x union all select 'owner_decisions',id,to_jsonb(x) from public.owner_decisions x union all select 'campaigns',id,to_jsonb(x) from public.campaigns x union all select 'tasks',id,to_jsonb(x) from public.tasks x union all select 'content_assets',id,to_jsonb(x) from public.content_assets x union all select 'business_memory_records',id,to_jsonb(x) from public.business_memory_records x union all select 'personal_operational_records',id,to_jsonb(x) from public.personal_operational_records x
),rows_ok as(select count(*) filter(where c.id is null or b.row_hash<>encode(extensions.digest(c.j::text,'sha256'),'hex')) mismatches from _m029_recovery.business_rows b left join current_rows c on c.t=b.source_table and c.id=b.source_id),sec_current as(
 select 'TABLE_SECURITY' kind,c.oid::regclass::text identity,encode(extensions.digest(jsonb_build_object('rls',c.relrowsecurity,'force_rls',c.relforcerowsecurity,'owner',pg_get_userbyid(c.relowner))::text,'sha256'),'hex') h from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname=any(array['clients','opportunities','owner_decisions','campaigns','tasks','content_assets','business_memory_records','personal_operational_records'])
 union all select 'POLICY',tablename||'.'||policyname,encode(extensions.digest(to_jsonb(p)::text,'sha256'),'hex') from pg_policies p where schemaname='public' and tablename=any(array['clients','opportunities','owner_decisions','campaigns','tasks','content_assets','business_memory_records','personal_operational_records'])
 union all select 'GRANT',table_name||':'||grantee||':'||privilege_type,encode(extensions.digest(to_jsonb(g)::text,'sha256'),'hex') from information_schema.role_table_grants g where table_schema='public' and table_name=any(array['clients','opportunities','owner_decisions','campaigns','tasks','content_assets','business_memory_records','personal_operational_records']) and grantee in('anon','authenticated','service_role')
 union all select 'FUNCTION',p.oid::regprocedure::text,encode(extensions.digest(pg_get_functiondef(p.oid),'sha256'),'hex') from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='m028_reference_exists'
 union all select case c.contype when 'p' then 'PRIMARY_KEY' when 'f' then 'FOREIGN_KEY' when 'u' then 'UNIQUE' else 'CHECK' end,c.conrelid::regclass::text||'.'||c.conname,encode(extensions.digest(pg_get_constraintdef(c.oid,true),'sha256'),'hex') from pg_constraint c where c.conrelid=any(array['public.clients'::regclass,'public.opportunities'::regclass,'public.owner_decisions'::regclass,'public.campaigns'::regclass,'public.tasks'::regclass,'public.content_assets'::regclass,'public.business_memory_records'::regclass,'public.personal_operational_records'::regclass])
 union all select 'INDEX',schemaname||'.'||indexname,encode(extensions.digest(indexdef,'sha256'),'hex') from pg_indexes where schemaname='public' and tablename=any(array['clients','opportunities','owner_decisions','campaigns','tasks','content_assets','business_memory_records','personal_operational_records'])
),sec_ok as(select count(*) mismatches from _m029_recovery.security_metadata s full join sec_current c on c.kind=s.kind and c.identity=s.object_identity where coalesce(s.kind,c.kind) in('TABLE_SECURITY','POLICY','GRANT','FUNCTION','PRIMARY_KEY','FOREIGN_KEY','UNIQUE','CHECK','INDEX') and (s.definition_hash is distinct from c.h))
select jsonb_build_object('result',case when r.mismatches=0 and s.mismatches=0 then 'M029_PRE_APPLY_RESTORE_VERIFICATION_PASS' else 'FAIL' end,'row_mismatches',r.mismatches,'security_mismatches',s.mismatches) verification from rows_ok r,sec_ok s;
rollback;
