begin;
create temp table _m032_test as select workspace_id,owner_user_id,null::uuid program_id,null::uuid source_id,null::uuid research_id,null::uuid strategy_id,null::uuid content_id,null::uuid publication_id,null::bigint publication_version,null::uuid performance_id,null::uuid candidate_id,1::bigint candidate_version,null::uuid evidence_id,null::uuid revenue_id from(select apw.workspace_id,apw.user_id owner_user_id from public.account_personal_workspaces apw join public.workspaces w on w.id=apw.workspace_id and w.status='active' join public.workspace_members m on m.workspace_id=w.id and m.user_id=apw.user_id and m.role='owner' and m.status='active' limit 1)x;
do $$ begin if not exists(select 1 from _m032_test) then raise exception 'm032_owner_fixture_required';end if;end $$;
insert into public.user_account_states(user_id,lifecycle_state,activated_at) select owner_user_id,'ACTIVE',clock_timestamp() from _m032_test on conflict(user_id) do update set lifecycle_state='ACTIVE';
with x as(insert into public.affiliate_program_master(workspace_id,asp_name,program_id,advertiser_name,program_name,listing_ng_words_verification_status,source_type,created_by) select workspace_id,'M032_FIXTURE','M032-FIXTURE','M032 Fixture','M032 Fixture Program','UNKNOWN','OWNER_TEST',owner_user_id from _m032_test returning id) update _m032_test t set program_id=x.id from x;
with x as(insert into public.research_sources(workspace_id,owner_user_id,canonical_url,source_name,source_domain,source_type,reliability_class,cost_class,limitations) select workspace_id,owner_user_id,'https://example.com/m032','M032 fixture','example.com','OTHER_WEB','LOW','FREE_CONFIRMED','rollback fixture' from _m032_test returning id) update _m032_test t set source_id=x.id from x;
with x as(insert into public.research_findings(workspace_id,owner_user_id,source_id,research_domain,observed_at,statement,truth_class,confidence,content_sha256,provenance) select workspace_id,owner_user_id,source_id,'AFFILIATE',clock_timestamp(),'M032 fixture','AI_INFERENCE',0.5,encode(extensions.digest('M032 fixture','sha256'),'hex'),'{"fixture":true,"evidence_status":"NOT_EVIDENCE"}'::jsonb from _m032_test returning id) update _m032_test t set research_id=x.id from x;
insert into public.operational_object_links(workspace_id,owner_user_id,from_type,from_id,to_type,to_id,relation_type,provenance) select workspace_id,owner_user_id,'GLOBAL_OPPORTUNITY',research_id,'AFFILIATE_PROGRAM',program_id,'CREATED_FOR','{"fixture":true}' from _m032_test;
with x as(insert into public.affiliate_strategies(workspace_id,owner_user_id,affiliate_program_id,source_research_id,status,provenance,idempotency_key) select workspace_id,owner_user_id,program_id,research_id,'CONFIRMED','{"source":"M032_FIXTURE"}','m032:fixture:strategy' from _m032_test returning id) update _m032_test t set strategy_id=x.id from x;
with x as(insert into public.personal_operational_records(workspace_id,data_owner_id,record_type,title,payload,lifecycle_status) select workspace_id,owner_user_id,'CONTENT','M032 Fixture Content',jsonb_build_object('workflow','AFFILIATE_REAL_CYCLE','affiliate_program_id',program_id::text,'affiliate_strategy_id',strategy_id::text,'affiliate_research_id',research_id::text,'truth_class','AI_OUTPUT','evidence_status','NOT_EVIDENCE'),'ACTIVE' from _m032_test returning id) update _m032_test t set content_id=x.id from x;
grant select,update on _m032_test to authenticated;
set local role authenticated;select set_config('request.jwt.claims',jsonb_build_object('role','authenticated','sub',(select owner_user_id from _m032_test))::text,true);
with x as(select * from public.save_affiliate_cycle_publication(null,null,(select program_id from _m032_test),(select content_id from _m032_test),(select strategy_id from _m032_test),(select research_id from _m032_test),'THREADS',null,null,'READY_FOR_REVIEW','m032:fixture:publication')) update _m032_test t set publication_id=x.object_id,publication_version=x.object_version from x;
with x as(select * from public.save_affiliate_cycle_publication((select publication_id from _m032_test),(select publication_version from _m032_test),(select program_id from _m032_test),(select content_id from _m032_test),(select strategy_id from _m032_test),(select research_id from _m032_test),'THREADS','https://example.com/m032-published',clock_timestamp(),'EXECUTED_EXTERNALLY','m032:fixture:publication:execute')) update _m032_test t set publication_version=x.object_version from x;
with x as(select * from public.record_affiliate_cycle_performance((select publication_id from _m032_test),(select publication_version from _m032_test),clock_timestamp(),10,1,1000,null,null,'JPY','OWNER_MANUAL','m032:fixture:performance')) update _m032_test t set performance_id=x.performance_id from x;
with x as(select * from public.create_affiliate_revenue_candidate((select performance_id from _m032_test),'CANDIDATE',1000,'JPY','CONFIRMED','OWNER_MANUAL',clock_timestamp(),clock_timestamp(),'{"source":"M032_ISOLATED_FIXTURE"}','m032:fixture:candidate')) update _m032_test t set candidate_id=x.candidate_id,candidate_version=x.candidate_version from x;
with x as(select public.attach_affiliate_revenue_evidence((select candidate_id from _m032_test),(select candidate_version from _m032_test),'ASP_CONFIRMED_CONVERSION','m032-fixture-reference',1000,'JPY',clock_timestamp(),'{"source":"M032_ISOLATED_FIXTURE","truth_class":"OWNER_REPORTED"}','m032:fixture:evidence') id) update _m032_test t set evidence_id=x.id,candidate_version=2 from x;
with x as(select public.confirm_affiliate_actual_revenue((select candidate_id from _m032_test),(select candidate_version from _m032_test),(select evidence_id from _m032_test),'m032:fixture:actual') id) update _m032_test t set revenue_id=x.id from x;
do $$ begin
 begin perform public.confirm_affiliate_actual_revenue((select candidate_id from _m032_test),2,(select evidence_id from _m032_test),'m032:fixture:actual:duplicate');raise exception 'm032_double_actual_not_denied';exception when others then if sqlerrm='m032_double_actual_not_denied' then raise;end if;end;
 begin update public.affiliate_revenue_candidates set amount_minor=0 where false;raise exception 'm032_browser_dml_not_denied';exception when insufficient_privilege then null;end;
end $$;
reset role;
do $$ begin
 if (select count(*) from public.revenue_records where affiliate_revenue_candidate_id=(select candidate_id from _m032_test))<>1 then raise exception 'm032_actual_duplicate';end if;
end $$;
select jsonb_build_object('result','M032_EXECUTABLE_RECOVERY_PASS','publication','EXECUTED_EXTERNALLY','performance_rows',1,'candidate','CONFIRMED_ACTUAL','evidence','VERIFIED','actual_rows',1,'duplicate_actual',false,'browser_direct_dml','DENIED','paid_ai_jpy',0,'external_execution','LOCKED','transaction_rolled_back',true) verification;
rollback;
