begin;

create table if not exists public.provider_cost_policies (
  id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id), provider text not null check(provider in ('openai','anthropic','gemini','perplexity','canva')),
  global_execution_enabled boolean not null default false, provider_execution_enabled boolean not null default false,
  max_cost_per_request_jpy numeric(14,6) not null default 5 check(max_cost_per_request_jpy>=0), hourly_budget_jpy numeric(14,6) not null default 20 check(hourly_budget_jpy>=0), daily_budget_jpy numeric(14,6) not null default 100 check(daily_budget_jpy>=0), monthly_budget_jpy numeric(14,6) not null default 1000 check(monthly_budget_jpy>=0),
  workflow_budget_jpy numeric(14,6) not null default 100 check(workflow_budget_jpy>=0), ai_employee_budget_jpy numeric(14,6) not null default 50 check(ai_employee_budget_jpy>=0), workspace_budget_jpy numeric(14,6) not null default 1000 check(workspace_budget_jpy>=0),
  max_input_tokens integer not null default 4000 check(max_input_tokens>=0), max_output_tokens integer not null default 800 check(max_output_tokens>0), max_total_tokens integer not null default 4800 check(max_total_tokens>=max_input_tokens+max_output_tokens),
  max_requests_per_job integer not null default 1 check(max_requests_per_job=1), max_requests_per_workflow integer not null default 3 check(max_requests_per_workflow>0), concurrency_limit integer not null default 1 check(concurrency_limit=1), max_retries integer not null default 1 check(max_retries between 0 and 1),
  updated_by uuid references public.owner_profiles(owner_id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,provider)
);
create table if not exists public.provider_model_allowlist (
  id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id), provider text not null, model text not null, request_class text not null check(request_class in ('generation','health_check')), pricing_input_per_million_jpy numeric(14,6), pricing_output_per_million_jpy numeric(14,6), pricing_verified_at timestamptz, high_cost boolean not null default false, enabled boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,provider,model,request_class), check(model !~* 'latest$'), check((pricing_input_per_million_jpy is null and pricing_output_per_million_jpy is null and pricing_verified_at is null) or (pricing_input_per_million_jpy>=0 and pricing_output_per_million_jpy>=0 and pricing_verified_at is not null))
);
create table if not exists public.provider_budget_reservations (
  id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id), workflow_id text not null, ai_employee_id text not null, provider text not null, model text not null, idempotency_key text not null, approval_id uuid, reserved_cost_jpy numeric(14,6) not null check(reserved_cost_jpy>=0), status text not null default 'reserved' check(status in ('reserved','committed','released','failed','expired')), expires_at timestamptz not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,provider,idempotency_key), unique(approval_id)
);
create table if not exists public.provider_usage_ledger (
  id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id), workflow_id text not null, ai_employee_id text not null, provider text not null, model text not null, purpose text not null, request_class text not null check(request_class in ('generation','health_check')), estimated_input_tokens integer not null check(estimated_input_tokens>=0), estimated_output_tokens integer not null check(estimated_output_tokens>=0), actual_input_tokens integer check(actual_input_tokens>=0), actual_output_tokens integer check(actual_output_tokens>=0), reserved_cost_jpy numeric(14,6) not null check(reserved_cost_jpy>=0), estimated_cost_jpy numeric(14,6) not null check(estimated_cost_jpy>=0), actual_cost_jpy numeric(14,6) check(actual_cost_jpy>=0), currency text not null default 'JPY' check(currency='JPY'), latency_ms integer check(latency_ms>=0), status text not null check(status in ('reserved','completed','blocked','failed','released')), error_class text, retry_count integer not null default 0 check(retry_count between 0 and 1), approval_id uuid, idempotency_key text not null, prompt_version text not null, prompt_hash text not null check(prompt_hash ~ '^[a-f0-9]{64}$'), created_at timestamptz not null default now()
);
create table if not exists public.provider_circuit_breakers (
  id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id), provider text not null, state text not null default 'closed' check(state in ('closed','open','half_open')), consecutive_failures integer not null default 0 check(consecutive_failures>=0), opened_at timestamptz, last_failure_class text, updated_at timestamptz not null default now(), unique(workspace_id,provider)
);
create table if not exists public.provider_execution_events (
  id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id), provider text not null, workflow_id text, event_type text not null check(event_type in ('threshold_50','threshold_75','threshold_90','hard_stop','blocked','circuit_opened','circuit_closed','policy_changed')), reason_code text not null, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), check(not (metadata ?| array['api_key','secret','access_token','refresh_token','authorization','prompt']))
);

create index if not exists provider_usage_ledger_workspace_created_idx on public.provider_usage_ledger(workspace_id,created_at desc);
create index if not exists provider_reservations_active_idx on public.provider_budget_reservations(workspace_id,provider,status,expires_at);
create index if not exists provider_events_workspace_created_idx on public.provider_execution_events(workspace_id,created_at desc);

alter table public.provider_cost_policies enable row level security; alter table public.provider_model_allowlist enable row level security; alter table public.provider_budget_reservations enable row level security; alter table public.provider_usage_ledger enable row level security; alter table public.provider_circuit_breakers enable row level security; alter table public.provider_execution_events enable row level security;
do $$ declare t text; begin foreach t in array array['provider_cost_policies','provider_model_allowlist','provider_budget_reservations','provider_usage_ledger','provider_circuit_breakers','provider_execution_events'] loop execute format('drop policy if exists %I on public.%I','provider_owner_read',t); execute format('create policy %I on public.%I for select to authenticated using (exists(select 1 from public.workspace_members wm where wm.workspace_id=%I.workspace_id and wm.user_id=auth.uid() and wm.role=''owner'' and wm.status=''active''))','provider_owner_read',t,t); end loop; end $$;

revoke all on table public.provider_cost_policies,public.provider_model_allowlist,public.provider_budget_reservations,public.provider_usage_ledger,public.provider_circuit_breakers,public.provider_execution_events from public,anon,authenticated;
grant select on table public.provider_cost_policies,public.provider_model_allowlist,public.provider_budget_reservations,public.provider_usage_ledger,public.provider_circuit_breakers,public.provider_execution_events to authenticated;
grant select,insert,update on table public.provider_cost_policies,public.provider_model_allowlist,public.provider_budget_reservations,public.provider_circuit_breakers to service_role;
grant select,insert on table public.provider_usage_ledger,public.provider_execution_events to service_role;

create or replace function public.reserve_provider_budget(p_workspace_id uuid,p_workflow_id text,p_ai_employee_id text,p_provider text,p_model text,p_idempotency_key text,p_estimated_input_tokens integer,p_estimated_output_tokens integer,p_estimated_cost_jpy numeric,p_approval_id uuid default null) returns jsonb language plpgsql security definer set search_path='' as $$
declare p public.provider_cost_policies; r public.provider_budget_reservations; spent_hour numeric; spent_day numeric; spent_month numeric; reserved_total numeric;
begin
  if p_workspace_id is null or p_estimated_cost_jpy is null or p_estimated_cost_jpy<0 then raise exception 'provider_request_invalid'; end if;
  perform pg_advisory_xact_lock(hashtextextended(p_workspace_id::text||':'||p_provider,0));
  select * into p from public.provider_cost_policies where workspace_id=p_workspace_id and provider=p_provider for update;
  if not found or not p.global_execution_enabled or not p.provider_execution_enabled then raise exception 'provider_execution_locked'; end if;
  if not exists(select 1 from public.provider_model_allowlist a where a.workspace_id=p_workspace_id and a.provider=p_provider and a.model=p_model and a.request_class='generation' and a.enabled and a.pricing_verified_at is not null) then raise exception 'model_not_allowlisted'; end if;
  if p_estimated_input_tokens>p.max_input_tokens or p_estimated_output_tokens>p.max_output_tokens or p_estimated_input_tokens+p_estimated_output_tokens>p.max_total_tokens then raise exception 'token_limit_exceeded'; end if;
  select coalesce(sum(actual_cost_jpy) filter(where created_at>=date_trunc('hour',now())),0),coalesce(sum(actual_cost_jpy) filter(where created_at>=date_trunc('day',now())),0),coalesce(sum(actual_cost_jpy) filter(where created_at>=date_trunc('month',now())),0) into spent_hour,spent_day,spent_month from public.provider_usage_ledger where workspace_id=p_workspace_id and provider=p_provider and status='completed';
  select coalesce(sum(reserved_cost_jpy),0) into reserved_total from public.provider_budget_reservations where workspace_id=p_workspace_id and provider=p_provider and status='reserved' and expires_at>now();
  if p_estimated_cost_jpy>p.max_cost_per_request_jpy or spent_hour+reserved_total+p_estimated_cost_jpy>p.hourly_budget_jpy or spent_day+reserved_total+p_estimated_cost_jpy>p.daily_budget_jpy or spent_month+reserved_total+p_estimated_cost_jpy>p.monthly_budget_jpy then raise exception 'provider_budget_exceeded'; end if;
  insert into public.provider_budget_reservations(workspace_id,workflow_id,ai_employee_id,provider,model,idempotency_key,approval_id,reserved_cost_jpy,expires_at) values(p_workspace_id,p_workflow_id,p_ai_employee_id,p_provider,p_model,p_idempotency_key,p_approval_id,p_estimated_cost_jpy,now()+interval '10 minutes') returning * into r;
  return jsonb_build_object('reservationId',r.id,'reservedCostJpy',r.reserved_cost_jpy);
exception when unique_violation then raise exception 'duplicate_provider_request'; end $$;
create or replace function public.finalize_provider_budget(p_reservation_id uuid,p_actual_cost_jpy numeric,p_status text) returns boolean language plpgsql security definer set search_path='' as $$ begin if p_actual_cost_jpy is null or p_actual_cost_jpy<0 or p_status not in ('committed','failed') then raise exception 'provider_finalize_invalid'; end if; update public.provider_budget_reservations set status=p_status,updated_at=now() where id=p_reservation_id and status='reserved'; if not found then raise exception 'provider_reservation_invalid'; end if; return true; end $$;
create or replace function public.release_provider_budget(p_reservation_id uuid) returns boolean language plpgsql security definer set search_path='' as $$ begin update public.provider_budget_reservations set status='released',updated_at=now() where id=p_reservation_id and status='reserved'; if not found then raise exception 'provider_reservation_invalid'; end if; return true; end $$;
revoke all on function public.reserve_provider_budget(uuid,text,text,text,text,text,integer,integer,numeric,uuid) from public,anon,authenticated; revoke all on function public.finalize_provider_budget(uuid,numeric,text) from public,anon,authenticated; revoke all on function public.release_provider_budget(uuid) from public,anon,authenticated;
grant execute on function public.reserve_provider_budget(uuid,text,text,text,text,text,integer,integer,numeric,uuid) to service_role; grant execute on function public.finalize_provider_budget(uuid,numeric,text) to service_role; grant execute on function public.release_provider_budget(uuid) to service_role;

commit;
