import path from"node:path";import{execFileSync}from"node:child_process";import{mkdir,readFile,rename,unlink,writeFile}from"node:fs/promises";import{START,END,vaultFile}from"./config.mjs";
export const UNKNOWN="UNKNOWN";const SECRET=[/sk-[a-z0-9_-]{12,}/i,/bearer\s+[a-z0-9._~+/=-]{12,}/i,/(?:password|client_secret|service_role_key|access_token|refresh_token)\s*[:=]\s*\S+/i,/postgres(?:ql)?:\/\/[^\s:@]+:[^\s@]+@/i];
export function assertNoSecrets(v){if(SECRET.some(x=>x.test(v)))throw Error("SECURITY_BLOCK")}
export function replaceManagedBlock(original,generated){assertNoSecrets(generated);const block=`${START}\n${generated.trim()}\n${END}`,s=original.indexOf(START),e=original.indexOf(END);if(s<0&&e<0)return`${original.trimEnd()}\n\n${block}\n`;if(s<0||e<s)throw Error("INVALID_MANAGED_BLOCK");return original.slice(0,s)+block+original.slice(e+END.length)}
export async function atomicWriteIfChanged(file,content){assertNoSecrets(content);let before=null;try{before=await readFile(file,"utf8")}catch(e){if(e.code!=="ENOENT")throw e}if(before===content)return false;await mkdir(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.tmp`;await writeFile(tmp,content,{encoding:"utf8",flag:"wx"});try{await rename(tmp,file)}catch(e){await unlink(tmp).catch(()=>{});throw e}return true}
export async function updateManagedNote(vault,relative,generated,seed=""){const file=vaultFile(vault,relative);let original=seed;try{original=await readFile(file,"utf8")}catch(e){if(e.code!=="ENOENT")throw e}return atomicWriteIfChanged(file,replaceManagedBlock(original,generated))}
export function gitState(cwd=process.cwd()){const run=(...a)=>execFileSync("git",a,{cwd,encoding:"utf8"}).trim();try{return{branch:run("branch","--show-current")||UNKNOWN,sha:run("rev-parse","HEAD"),status:run("status","--short")||"CLEAN"}}catch{return{branch:UNKNOWN,sha:UNKNOWN,status:UNKNOWN}}}
export async function appendUnique(file,id,entry){assertNoSecrets(entry);let original="";try{original=await readFile(file,"utf8")}catch(e){if(e.code!=="ENOENT")throw e}if(original.includes(`## ${id}`))return false;return atomicWriteIfChanged(file,`${original.trimEnd()}\n\n## ${id}\n${entry.trim()}\n`)}
export const valueOrUnknown=v=>v===null||v===undefined||v===""?UNKNOWN:v;
export function separateRevenue(rows=[]){const groups={actual:[],forecast:[],unknown:[]};for(const row of rows){const k=String(row.truth_class||row.value_type||"unknown").toLowerCase();(groups[k]||groups.unknown).push(row)}return groups}
export async function readProductionSnapshot(env=process.env,fetchImpl=globalThis.fetch){const url=env.VITE_SUPABASE_URL,key=env.VITE_SUPABASE_PUBLISHABLE_KEY,workspace=env.KEVIRIO_OBSIDIAN_WORKSPACE_ID;if(!url||!key||!workspace||!fetchImpl)return{state:UNKNOWN,revenue:[],evidence:[],affiliate:[],performance:[],errors:["READ_CONFIGURATION_UNAVAILABLE"]};const headers={apikey:key,Authorization:`Bearer ${key}`,Accept:"application/json"},get=async(table,select)=>{const r=await fetchImpl(`${url}/rest/v1/${table}?workspace_id=eq.${encodeURIComponent(workspace)}&select=${encodeURIComponent(select)}`,{method:"GET",headers});if(!r.ok)throw Error(`${table}:${r.status}`);return r.json()};const s=await Promise.allSettled([get("revenue_records","id,amount_minor,currency,recognized_at"),get("evidence_candidates","id,evidence_type,source_reference,verification_status,verified_at"),get("affiliate_programs","id,program_name,asp_name,status,affiliate_link_status,affiliate_url,listing_verification_status"),get("affiliate_performance_records","affiliate_program_id,clicks,conversions,approved_revenue_minor,cost_minor,period_end,source_reference")]),data=s.map(x=>x.status==="fulfilled"?x.value:[]),errors=s.filter(x=>x.status==="rejected").map(x=>x.reason.message);return{state:errors.length?UNKNOWN:"READ_ONLY_OK",revenue:data[0],evidence:data[1],affiliate:data[2],performance:data[3],errors}}
