import test from "node:test";
import assert from "node:assert/strict";
import { ASSISTANT_INTENTS, classifyAssistantIntent } from "../../src/domain/assistantIntent.js";
import { canUseAssistantContext, createAssistantContextEnvelope, orchestrateAssistantRequest } from "../../src/services/assistantOrchestration.js";
import { createAssistantConversationRepository } from "../../src/repositories/assistantConversationRepository.js";

test("Japanese work intents map to stable deep links with zero execution",()=>{const cases=[["今日何をしたらいい？",ASSISTANT_INTENTS.TODAY,"/home?tab=今日"],["この事業アイデアどう思う？",ASSISTANT_INTENTS.BUSINESS_IDEA,"/goals?tab=戦略"],["今月あと10万円増やすなら？",ASSISTANT_INTENTS.MONETIZATION,"/goals?tab=今月"],["Threadsの投稿を作りたい",ASSISTANT_INTENTS.THREADS_CONTENT,"/content?tab=SNS&platform=Threads"],["CrowdWorksの案件を評価して",ASSISTANT_INTENTS.OPPORTUNITY_REVIEW,"/opportunities?tab=CrowdWorks"],["提案資料を作りたい",ASSISTANT_INTENTS.PROPOSAL,"/outreach?tab=提案準備"]];for(const [input,intent,path] of cases){assert.equal(classifyAssistantIntent(input),intent);const result=orchestrateAssistantRequest(input);assert.equal(result.actions[0].path,path);assert.deepEqual(result.execution,{provider:"deterministic-local",paidAiCalls:0,externalExecution:false})}});
test("private context denies cross-user access unless explicitly shared",()=>{const denied=createAssistantContextEnvelope({requestingUserId:"member-b",workspaceId:"w",dataOwnerId:"member-a"});assert.deepEqual(canUseAssistantContext(denied),{allowed:false,reason:"PRIVATE_DATA_DENIED"});assert.equal(orchestrateAssistantRequest("AのSNSを見せて",{context:denied}).status,"denied");const shared=createAssistantContextEnvelope({requestingUserId:"member-b",workspaceId:"w",dataOwnerId:"member-a",sharingPermission:"explicit"});assert.equal(canUseAssistantContext(shared).allowed,true)});
test("conversation repository caps and sanitizes private session history",()=>{const repository=createAssistantConversationRepository();for(let i=0;i<55;i++)repository.append({id:i,role:i%2?"assistant":"user",text:"x"});assert.equal(repository.list().length,50);assert.equal(repository.persistence,"memory-only");repository.clear();assert.equal(repository.list().length,0)});
