import test from"node:test";import assert from"node:assert/strict";import path from"node:path";import{mkdtemp,mkdir,readFile,writeFile}from"node:fs/promises";import{tmpdir}from"node:os";import{appendUnique,atomicWriteIfChanged,readProductionSnapshot,replaceManagedBlock,separateRevenue,UNKNOWN}from"../../tools/obsidian/core.mjs";import{buildRevenue,createDaily,evidenceCount,syncEvidence,syncRevenue}from"../../tools/obsidian/sync.mjs";import{vaultFile}from"../../tools/obsidian/config.mjs";
test("managed block preserves Owner content",()=>{const x=replaceManagedBlock("Owner before\n<!-- KEVIRIO:AUTO:START -->\nold\n<!-- KEVIRIO:AUTO:END -->\nOwner after","new");assert.match(x,/Owner before/);assert.match(x,/Owner after/);assert.doesNotMatch(x,/old/)});
test("managed replacement is idempotent",()=>{const x=replaceManagedBlock("Owner","same");assert.equal(replaceManagedBlock(x,"same"),x)});
test("no change causes no write",async()=>{const d=await mkdtemp(path.join(tmpdir(),"obsidian-")),f=path.join(d,"x.md");await writeFile(f,"same");assert.equal(await atomicWriteIfChanged(f,"same"),false)});
test("missing fields are UNKNOWN and truth classes stay separate",()=>{const g=separateRevenue([{truth_class:"actual"},{truth_class:"forecast"},{}]);assert.deepEqual([g.actual.length,g.forecast.length,g.unknown.length],[1,1,1]);assert.equal(UNKNOWN,"UNKNOWN")});
test("secret detection blocks output",()=>assert.throws(()=>replaceManagedBlock("","password=forbidden-value"),/SECURITY_BLOCK/));
test("Vault traversal is rejected",()=>assert.throws(()=>vaultFile("C:\\Vault","../escape.md"),/TRAVERSAL/));
test("daily note is idempotent",async()=>{const v=await mkdtemp(path.join(tmpdir(),"vault-"));await mkdir(path.join(v,"12_DAILY"));const n=new Date("2026-08-10T00:00:00Z");await createDaily(v,n);const f=path.join(v,"12_DAILY","2026-08-10.md"),x=await readFile(f,"utf8");assert.equal(await createDaily(v,n),false);assert.equal(await readFile(f,"utf8"),x)});
test("release log is append-only",async()=>{const d=await mkdtemp(path.join(tmpdir(),"obsidian-")),f=path.join(d,"r.md");assert.equal(await appendUnique(f,"REL-1","Date: now"),true);assert.equal(await appendUnique(f,"REL-1","Date: later"),false);assert.doesNotMatch(await readFile(f,"utf8"),/later/)});
test("decision approval is not auto-created",()=>assert.doesNotMatch(replaceManagedBlock("Owner Approval:\n","technical"),/Owner Approval:\s*YES/));
test("Production adapter has GET only",async()=>{const methods=[],fetchImpl=async(_u,i)=>(methods.push(i.method),{ok:true,json:async()=>[]});await readProductionSnapshot({VITE_SUPABASE_URL:"https://example.supabase.co",VITE_SUPABASE_PUBLISHABLE_KEY:"public-key",KEVIRIO_OBSIDIAN_WORKSPACE_ID:"workspace"},fetchImpl);assert.deepEqual(methods,["GET","GET","GET","GET"])})
const snapshot=(state,evidence=[],errors=[])=>({state,revenue:[],evidence,affiliate:[],performance:[],errors});
test("successful Evidence read preserves verified zero and non-zero counts",()=>{assert.equal(evidenceCount(snapshot("READ_ONLY_OK")),0);assert.equal(evidenceCount(snapshot("READ_ONLY_OK",[{verification_status:"verified"},{verification_status:"pending"},{verification_status:"verified"}])),2)});
test("unavailable failed and unknown Evidence reads remain UNKNOWN",()=>{for(const state of["UNAVAILABLE","FAILED",UNKNOWN])assert.equal(evidenceCount(snapshot(state)),UNKNOWN)});
test("missing read configuration keeps unavailable summaries UNKNOWN",async()=>{const s=await readProductionSnapshot({},async()=>{throw Error("transport must not run")}),r=buildRevenue(s);assert.equal(s.state,UNKNOWN);assert.deepEqual([r.actual,r.forecast,r.cost,r.evidence],[UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN]);assert.equal(s.affiliate.length,0)});
test("failed Evidence transport remains UNKNOWN",async()=>{const s=await readProductionSnapshot({VITE_SUPABASE_URL:"https://example.supabase.co",VITE_SUPABASE_PUBLISHABLE_KEY:"public-key",KEVIRIO_OBSIDIAN_WORKSPACE_ID:"workspace"},async()=>({ok:false,status:503,json:async()=>[]}));assert.equal(s.state,UNKNOWN);assert.equal(evidenceCount(s),UNKNOWN)});
test("Evidence summaries remain UNKNOWN and idempotent when unavailable",async()=>{const v=await mkdtemp(path.join(tmpdir(),"vault-")),n=new Date("2026-08-11T00:00:00Z"),s=snapshot(UNKNOWN,[],["READ_CONFIGURATION_UNAVAILABLE"]);await mkdir(path.join(v,"06_REVENUE","SNAPSHOTS"),{recursive:true});await mkdir(path.join(v,"09_EVIDENCE"),{recursive:true});await syncRevenue(v,s,n);await syncEvidence(v,s,n);const files=[path.join(v,"06_REVENUE","REVENUE_VALIDATION.md"),path.join(v,"06_REVENUE","SNAPSHOTS","2026-08-11.md"),path.join(v,"09_EVIDENCE","EVIDENCE_INDEX.md")],before=await Promise.all(files.map(f=>readFile(f,"utf8")));assert.match(before[0],/Verified Evidence Count: UNKNOWN/);assert.match(before[1],/Evidence Count: UNKNOWN/);assert.match(before[2],/## Verified Evidence\nUNKNOWN/);await syncRevenue(v,s,n);await syncEvidence(v,s,n);assert.deepEqual(await Promise.all(files.map(f=>readFile(f,"utf8"))),before)});
