import test from"node:test";import assert from"node:assert/strict";import path from"node:path";import{mkdtemp,mkdir,readFile,writeFile}from"node:fs/promises";import{tmpdir}from"node:os";import{appendUnique,atomicWriteIfChanged,readProductionSnapshot,replaceManagedBlock,separateRevenue,UNKNOWN}from"../../tools/obsidian/core.mjs";import{createDaily}from"../../tools/obsidian/sync.mjs";import{vaultFile}from"../../tools/obsidian/config.mjs";
test("managed block preserves Owner content",()=>{const x=replaceManagedBlock("Owner before\n<!-- KEVIRIO:AUTO:START -->\nold\n<!-- KEVIRIO:AUTO:END -->\nOwner after","new");assert.match(x,/Owner before/);assert.match(x,/Owner after/);assert.doesNotMatch(x,/old/)});
test("managed replacement is idempotent",()=>{const x=replaceManagedBlock("Owner","same");assert.equal(replaceManagedBlock(x,"same"),x)});
test("no change causes no write",async()=>{const d=await mkdtemp(path.join(tmpdir(),"obsidian-")),f=path.join(d,"x.md");await writeFile(f,"same");assert.equal(await atomicWriteIfChanged(f,"same"),false)});
test("missing fields are UNKNOWN and truth classes stay separate",()=>{const g=separateRevenue([{truth_class:"actual"},{truth_class:"forecast"},{}]);assert.deepEqual([g.actual.length,g.forecast.length,g.unknown.length],[1,1,1]);assert.equal(UNKNOWN,"UNKNOWN")});
test("secret detection blocks output",()=>assert.throws(()=>replaceManagedBlock("","password=forbidden-value"),/SECURITY_BLOCK/));
test("Vault traversal is rejected",()=>assert.throws(()=>vaultFile("C:\\Vault","../escape.md"),/TRAVERSAL/));
test("daily note is idempotent",async()=>{const v=await mkdtemp(path.join(tmpdir(),"vault-"));await mkdir(path.join(v,"12_DAILY"));const n=new Date("2026-08-10T00:00:00Z");await createDaily(v,n);const f=path.join(v,"12_DAILY","2026-08-10.md"),x=await readFile(f,"utf8");assert.equal(await createDaily(v,n),false);assert.equal(await readFile(f,"utf8"),x)});
test("release log is append-only",async()=>{const d=await mkdtemp(path.join(tmpdir(),"obsidian-")),f=path.join(d,"r.md");assert.equal(await appendUnique(f,"REL-1","Date: now"),true);assert.equal(await appendUnique(f,"REL-1","Date: later"),false);assert.doesNotMatch(await readFile(f,"utf8"),/later/)});
test("decision approval is not auto-created",()=>assert.doesNotMatch(replaceManagedBlock("Owner Approval:\n","technical"),/Owner Approval:\s*YES/));
test("Production adapter has GET only",async()=>{const methods=[],fetchImpl=async(_u,i)=>(methods.push(i.method),{ok:true,json:async()=>[]});await readProductionSnapshot({VITE_SUPABASE_URL:"https://example.supabase.co",VITE_SUPABASE_PUBLISHABLE_KEY:"public-key",KEVIRIO_OBSIDIAN_WORKSPACE_ID:"workspace"},fetchImpl);assert.deepEqual(methods,["GET","GET","GET","GET"])})
