const OPENAI_URL = "https://api.openai.com/v1/chat/completions";
const GEMINI_URL_BASE = "https://generativelanguage.googleapis.com/v1beta/models";
const ANTHROPIC_URL = "https://api.anthropic.com/v1/messages";
const PERPLEXITY_URL = "https://api.perplexity.ai/chat/completions";
function buildSystemPrompt(mode = "general") { return `あなたはKEVIRIOのAI Orchestratorです。\n- AIは分析・提案・下書き・予約準備まで。\n- 最終決裁は必ずオーナー。\n- 事実・推測・意見・要確認を分ける。\n- 法務・ブランド・コンプライアンス・長期価値を考慮する。\n- 外部投稿・契約・送信・決済は自動実行しない。\n- 機能は増やしても、操作は増やさない。\nmode: ${mode}`; }
function chooseProvider({ provider = "auto", mode = "general" }) { if (provider && provider !== "auto") return provider; if (["research","trend","competitor"].includes(mode)) return process.env.PERPLEXITY_API_KEY ? "perplexity" : "openai"; if (["legal","review","brand","long"].includes(mode)) return process.env.ANTHROPIC_API_KEY ? "anthropic" : process.env.GEMINI_API_KEY ? "gemini" : "openai"; return process.env.OPENAI_API_KEY ? "openai" : process.env.GEMINI_API_KEY ? "gemini" : "anthropic"; }
async function callOpenAI({ message, mode }) { if (!process.env.OPENAI_API_KEY) throw new Error("OPENAI_API_KEY is not configured"); const model = process.env.OPENAI_MODEL || "gpt-4.1-mini"; const response = await fetch(OPENAI_URL, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${process.env.OPENAI_API_KEY}` }, body: JSON.stringify({ model, messages: [{ role: "system", content: buildSystemPrompt(mode) }, { role: "user", content: message }], temperature: 0.4 }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error?.message || "OpenAI request failed"); return { provider: "openai", model, text: data.choices?.[0]?.message?.content || "" }; }
async function callGemini({ message, mode }) { if (!process.env.GEMINI_API_KEY) throw new Error("GEMINI_API_KEY is not configured"); const model = process.env.GEMINI_MODEL || "gemini-2.5-flash"; const url = `${GEMINI_URL_BASE}/${model}:generateContent?key=${process.env.GEMINI_API_KEY}`; const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ contents: [{ role: "user", parts: [{ text: `${buildSystemPrompt(mode)}\n\n${message}` }] }], generationConfig: { temperature: 0.4 } }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error?.message || "Gemini request failed"); return { provider: "gemini", model, text: data.candidates?.[0]?.content?.parts?.map((part) => part.text).join("\n") || "" }; }
async function callAnthropic({ message, mode }) { if (!process.env.ANTHROPIC_API_KEY) throw new Error("ANTHROPIC_API_KEY is not configured"); const model = process.env.ANTHROPIC_MODEL || "claude-3-5-sonnet-latest"; const response = await fetch(ANTHROPIC_URL, { method: "POST", headers: { "Content-Type": "application/json", "x-api-key": process.env.ANTHROPIC_API_KEY, "anthropic-version": "2023-06-01" }, body: JSON.stringify({ model, max_tokens: 1600, system: buildSystemPrompt(mode), messages: [{ role: "user", content: message }], temperature: 0.35 }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error?.message || "Anthropic request failed"); return { provider: "anthropic", model, text: data.content?.map((part) => part.text).join("\n") || "" }; }
async function callPerplexity({ message, mode }) { if (!process.env.PERPLEXITY_API_KEY) throw new Error("PERPLEXITY_API_KEY is not configured"); const model = process.env.PERPLEXITY_MODEL || "sonar"; const response = await fetch(PERPLEXITY_URL, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${process.env.PERPLEXITY_API_KEY}` }, body: JSON.stringify({ model, messages: [{ role: "system", content: buildSystemPrompt(mode) }, { role: "user", content: message }], temperature: 0.3 }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error?.message || "Perplexity request failed"); return { provider: "perplexity", model, text: data.choices?.[0]?.message?.content || "" }; }
const callers = { openai: callOpenAI, gemini: callGemini, anthropic: callAnthropic, perplexity: callPerplexity };
export default async function handler(req, res) { if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" }); const { message, mode = "general", provider = "auto" } = req.body || {}; if (!message || typeof message !== "string") return res.status(400).json({ error: "message is required" }); const selected = chooseProvider({ provider, mode }); const fallbackOrder = [selected, "openai", "gemini", "anthropic", "perplexity"].filter((item, index, arr) => item && arr.indexOf(item) === index); const tried = []; const errors = []; for (const candidate of fallbackOrder) { try { tried.push(candidate); const result = await callers[candidate]({ message, mode }); return res.status(200).json({ ok: true, mode, selected: candidate, fallbackUsed: candidate !== selected, tried, ...result, governance: { ownerFinalDecision: true, externalExecution: false, secretsExposed: false } }); } catch (error) { errors.push({ provider: candidate, error: error.message }); } } return res.status(500).json({ ok: false, error: "AI Orchestrator failed", tried, errors }); }
