import { useCallback, useEffect, useMemo, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { Badge, Button, Card, EmptyState, EnvironmentBadge, ErrorState, LoadingState, PageHeader, SectionHeader } from "../../design-system/index.js";
import AffiliateIntelligenceWorkspace from "../AffiliateIntelligenceWorkspace.jsx";
import { createAffiliateV2CommandCenterService } from "../../services/affiliateV2CommandCenterService.js";
import { resolvePersonalWorkspace } from "../../repositories/personalWorkspaceRepository.js";
import { commandCenterViewModel, paletteCommands, truthLabel } from "./viewModels/affiliateV2ViewModel.js";
import { CommandPalette, KpiCommandCenter, OwnerDailyBrief, OwnerDecisionRail, ProgramPanels } from "./AffiliateV2Panels.jsx";
import AffiliateProgramMaster from "./AffiliateProgramMaster.jsx";
import "./AffiliateV2.css";
import "./AffiliateV2ReleaseFix.css";
const views=new Set(["product","strategy","content","publication","evidence","revenue","learning","graph","ai-meeting","audit"]);
export default function AffiliateV2Experience(props){const location=useLocation();if(location.pathname.startsWith("/operations/offers/"))return <AffiliateIntelligenceWorkspace {...props}/>;return <AffiliateV2Router {...props}/>}
function AffiliateV2Router({ownerSupabaseClient,ownerSession}){const location=useLocation(),navigate=useNavigate(),service=useMemo(()=>createAffiliateV2CommandCenterService(ownerSupabaseClient),[ownerSupabaseClient]);const [state,setState]=useState({status:"loading",data:null,error:null});const [palette,setPalette]=useState(false);const match=location.pathname.match(/^\/affiliate-intelligence\/([^/]+)(?:\/([^/]+))?$/);const programId=match?.[1]||null,view=views.has(match?.[2])?match[2]:"strategy";const load=useCallback(async()=>{setState(s=>({...s,status:"loading"}));try{if(!ownerSession?.user?.id)throw new Error("OWNER_SESSION_REQUIRED");const workspaceId=await resolvePersonalWorkspace(ownerSupabaseClient,ownerSession.user.id);const data=programId?await service.getProgramWorkspaceSummary(workspaceId,programId):await service.getAffiliateCommandCenter(workspaceId);setState({status:"ready",data:{...data,workspaceId},error:null})}catch(error){setState({status:"conditional",data:null,error})}},[ownerSession?.user?.id,programId,service]);useEffect(()=>{load()},[load]);useEffect(()=>{const key=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setPalette(true)}};document.addEventListener("keydown",key);return()=>document.removeEventListener("keydown",key)},[]);
  if(state.status==="conditional")return <div className="av2-fallback"><Card><Badge label="利用制限"/><h2>アフィリエイト機能を現在利用できません</h2><p>Personal WorkspaceまたはAffiliate capabilityを確認できませんでした。技術詳細: AFFILIATE_CAPABILITY_UNAVAILABLE</p></Card><AffiliateIntelligenceWorkspace ownerSupabaseClient={ownerSupabaseClient} ownerSession={ownerSession}/></div>;
  if(state.status==="loading")return <main className="content av2"><LoadingState title="Affiliate Intelligenceを読み込み中" message="Owner Workspaceと正式データを確認しています。"/></main>;
  const saveLink=async(id,input)=>{await service.saveProgramMasterAffiliateLink(state.data.workspaceId,id,input);await load()};return programId?<ProgramWorkspace data={state.data} view={view} navigate={navigate} onPalette={()=>setPalette(true)} palette={palette} setPalette={setPalette}/>:<CommandCenter data={state.data} navigate={navigate} onSaveLink={saveLink} onPalette={()=>setPalette(true)} palette={palette} setPalette={setPalette}/>;
}
function CommandCenter({data,navigate,onSaveLink,onPalette,palette,setPalette}){const vm=commandCenterViewModel(data);return <main className="content av2"><PageHeader eyebrow="AFFILIATE INTELLIGENCE" title="アフィリエイト事業コマンドセンター" description="判断・手動実行・Evidence・学習までを一つのOwner Workspaceで管理します。" actions={<><EnvironmentBadge environment="locked"/><Button variant="secondary" onClick={onPalette}>⌘ コマンド</Button></>}/><p className="av2-boundary">External Execution: LOCKED · Feature maturity: Conditional</p><OwnerDailyBrief brief={vm.brief}/><KpiCommandCenter items={vm.kpis}/><section><SectionHeader title="Risk Radar" description="最大5件"/><div className="av2-card-grid">{vm.alerts.map(x=><Card key={x.id}><Badge label={x.severity}/><h3>{x.summary}</h3><p>{x.code}</p></Card>)}{!vm.alerts.length&&<EmptyState title="表示可能なRiskはありません" message="未取得をゼロとは扱いません。"/>}</div></section><AffiliateProgramMaster programs={data.programMaster||[]} onSaveLink={onSaveLink}/><section><SectionHeader title="Programs"/><div className="av2-programs">{vm.programs.map(x=><button key={x.id} onClick={()=>navigate(`/affiliate-intelligence/${x.id}`)}><span><small>{truthLabel(x.truthClass)}</small><strong>{x.name}</strong></span><span>{x.status} →</span></button>)}{!vm.programs.length&&<EmptyState title="Affiliate Programはありません" message="既存Offerがある場合はV1.1運用準備から関連付けできます。"/>}</div></section><CommandPalette open={palette} onClose={()=>setPalette(false)} commands={paletteCommands("")} onNavigate={navigate}/></main>}
function ProgramWorkspace({data,view,navigate,onPalette,palette,setPalette}){const program=data.program;const tabs=[['strategy','概要'],['product','商品'],['content','コンテンツ'],['publication','公開'],['evidence','Evidence'],['revenue','収益'],['learning','Learning'],['graph','Graph'],['ai-meeting','AI会議'],['audit','監査']];return <main className="content av2"><PageHeader eyebrow="PROGRAM WORKSPACE" title={program.name} description="案件の判断材料を段階的に確認します。" actions={<><Badge label={truthLabel(program.truthClass)}/><EnvironmentBadge environment="locked"/><Button variant="secondary" onClick={onPalette}>⌘</Button></>}/><p className="av2-boundary">External Execution: LOCKED · Save state: 読み取り専用</p><nav className="av2-tabs" aria-label="案件ナビゲーション">{tabs.map(([key,label])=><button key={key} aria-current={view===key?'page':undefined} onClick={()=>navigate(`/affiliate-intelligence/${program.id}/${key}`)}>{label}</button>)}</nav><div className="av2-workspace"><ProgramPanels view={view} summary={data}/><OwnerDecisionRail summary={data}/></div><CommandPalette open={palette} onClose={()=>setPalette(false)} commands={paletteCommands(program.id)} onNavigate={navigate}/></main>}
