import { Badge, Card, EmptyState, SectionHeader } from "../../design-system/index.js";
import { experimentViewModel, memoryViewModel, opportunityViewModel, promptViewModel, timelineViewModel, UNKNOWN } from "./viewModels/affiliateV2FinalViewModel.js";
import "./AffiliateV2Final.css";
const Field=({label,children})=><div><dt>{label}</dt><dd>{children??UNKNOWN}</dd></div>;

export function OpportunityRadar({snapshots}){const x=opportunityViewModel(snapshots);return <section><SectionHeader title="Opportunity Radar"/><Card><h3>Current opportunity</h3><dl className="av2-data-grid"><Field label="Opportunity score">{x.score}</Field><Field label="Expected impact">{x.expectedImpact}</Field><Field label="Difficulty">{x.difficulty}</Field><Field label="Confidence">{x.confidence}</Field><Field label="Why">{x.why}</Field><Field label="Required Owner Action">{x.ownerAction}</Field><Field label="Evidence">{x.evidence}</Field><Field label="Truth class">{x.truthClass}</Field></dl></Card></section>}
export function ExperimentEngine({experiments}){const items=experimentViewModel(experiments);return <section><SectionHeader title="Experiment Engine" description="Owner approval and manual execution are mandatory. Automatic execution is disabled."/><ol className="av2-lifecycle" aria-label="Experiment lifecycle">{["Hypothesis","Design","Approval","Manual Execution","Measurement","Learning"].map(x=><li key={x}>{x}</li>)}</ol><div className="av2-card-grid">{items.length?items.map(x=><Card key={x.id}><Badge label={x.truthClass}/><h3>{x.hypothesis}</h3><p>Status: {x.status}</p><p>Evidence: {x.evidence}</p></Card>):<EmptyState title="No experiments recorded" message="No experiment will run automatically."/>}</div></section>}
export function BusinessMemory({memories}){return <section><SectionHeader title="Business Memory"/><div className="av2-memory-grid">{memoryViewModel(memories).map(g=><Card key={g.category}><h3>{g.category}</h3>{g.items.length?g.items.map((x,i)=><dl className="av2-data-grid" key={x.id||i}><Field label="Summary">{x.summary}</Field><Field label="Evidence">{x.evidence}</Field><Field label="Confidence">{x.confidence}</Field><Field label="Reuse Count">{x.reuseCount}</Field><Field label="Related Programs">{x.relatedPrograms}</Field><Field label="Last Used">{x.lastUsed}</Field></dl>):<p>Unknown — no supported record.</p>}</Card>)}</div></section>}
export function Timeline({events}){return <section><SectionHeader title="Timeline" description="Canonical lifecycle; absent event data remains Unknown."/><ol className="av2-timeline">{timelineViewModel(events).map(x=><li key={x.stage}><h3>{x.stage}</h3><dl className="av2-data-grid"><Field label="Timestamp">{x.timestamp}</Field><Field label="Source">{x.source}</Field><Field label="Actor">{x.actor}</Field><Field label="Evidence">{x.evidence}</Field><Field label="Truth class">{x.truthClass}</Field></dl></li>)}</ol></section>}
export function PromptLibrary({prompts}){const items=promptViewModel(prompts);return <section><SectionHeader title="Prompt Library" description="Read-only metadata. Prompt bodies and secrets are not exposed."/><div className="av2-table-wrap" tabIndex="0"><table><caption>Read-only prompt versions</caption><thead><tr>{["Prompt","Version","Purpose","Hash","Model","Temperature","Schema","Latency","Cost","Diff"].map(x=><th scope="col" key={x}>{x}</th>)}</tr></thead><tbody>{items.map(x=><tr key={x.id}>{[x.prompt,x.version,x.purpose,x.hash,x.model,x.temperature,x.schema,x.latency,x.cost,x.diff].map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table>{!items.length&&<p>Unknown — no prompt metadata available.</p>}</div></section>}
export function MarketplaceFoundation({assets}){const types=["Prompt","Workflow","Checklist","Template","Strategy","AI Employee","Reusable Asset"];return <section><SectionHeader title="Marketplace Foundation" description="Internal Asset Library only. Public marketplace, checkout, and payment are disabled."/><div className="av2-card-grid">{types.map(type=>{const count=(assets||[]).filter(x=>x.type===type).length;return <Card key={type}><h3>{type}</h3><p>{count?`${count} internal asset${count===1?"":"s"}`:"Unknown — no supported asset record."}</p></Card>})}</div></section>}
