import { useEffect, useRef } from "react";
import { Badge, Button, Card, EmptyState, KpiCard, SectionHeader } from "../../design-system/index.js";
import { moneyLabel, ownerDecisionViewModel, truthLabel } from "./viewModels/affiliateV2ViewModel.js";
import { BusinessMemory, ExperimentEngine, MarketplaceFoundation, OpportunityRadar, PromptLibrary, Timeline } from "./AffiliateV2FinalPanels.jsx";
import { publicationWorkspaceViewModel, revenueWorkspaceViewModel } from "./viewModels/affiliateV3WorkspaceViewModel.js";

export function OwnerDailyBrief({brief}){return <Card className="av2-brief"><SectionHeader title="本日のOwner Brief" description="10分以内で判断できる項目だけを表示します。"/><p>{brief?.summary?.headline||"利用可能なDaily Briefはまだありません。"}</p><div className="av2-action-row">{(brief?.summary?.actions||[]).slice(0,3).map((x,i)=><Button key={x.id||i} variant="secondary">{x.title||"確認する"}</Button>)}</div></Card>}

export function KpiCommandCenter({items}){return <section aria-labelledby="av2-kpis"><SectionHeader title="会社の状態"/><div id="av2-kpis" className="av2-kpis">{items.map((x)=><KpiCard key={x.label} label={x.label} value={x.value} state={x.truth==="Actual"?"actual":"unknown"}/>)}</div></section>}

export function OwnerDecisionRail({summary}){const vm=ownerDecisionViewModel(summary);return <aside className="av2-decision" aria-label="Owner Decision Rail"><p className="eyebrow">NEXT OWNER ACTION</p><h2>{vm.title}</h2><p>{vm.reason}</p><dl><div><dt>Evidence</dt><dd>{vm.evidenceStatus}</dd></div><div><dt>Risk</dt><dd>{vm.risk}</dd></div><div><dt>所要時間</dt><dd>約{vm.minutes}分</dd></div></dl>{vm.blockingItem&&<p role="alert">Blocking: {vm.blockingItem}</p>}<div className="av2-action-row"><Button disabled={!vm.canApprove} title={vm.disabledReason}>承認</Button><Button variant="secondary">差し戻し</Button><Button variant="secondary">保留</Button></div>{!vm.canApprove&&<small>{vm.disabledReason}</small>}</aside>}

export function ProgramPanels({view,summary}){
  const products=summary?.products||[],research=summary?.research||[],snapshots=summary?.snapshots||[],risks=summary?.risks||[];
  const sections={
    product:<><SectionHeader title="商品インテリジェンス"/><div className="av2-card-grid">{products.length?products.map(x=><Card key={x.id}><Badge label={truthLabel(x.truthClass)} state={x.truthClass==="Actual"?"actual":"pending"}/><h3>{x.name}</h3><p>価格: {moneyLabel(x.priceMinor,x.currency||"JPY")}</p><p>Source: {x.sourceReference||"未登録"}</p></Card>):<EmptyState title="商品情報は未登録です" message="Migration 015適用後、正式なSource付き情報を登録できます。"/>}</div></>,
    strategy:<><SectionHeader title="機会・競合・戦略"/><div className="av2-card-grid">{snapshots.filter(x=>["opportunity_score","swot","strategy"].includes(x.snapshotType)).map(x=><Card key={x.id}><Badge label={truthLabel(x.truthClass)}/><h3>{x.snapshotType}</h3><p>Confidence: {x.confidence==null?"未取得":`${Math.round(x.confidence*100)}%`}</p></Card>)}{!snapshots.length&&<EmptyState title="推論結果はありません" message="架空のスコアは表示しません。"/>}</div><OpportunityRadar snapshots={snapshots}/><ExperimentEngine experiments={summary?.experiments||[]}/></>,
    content:<><SectionHeader title="コンテンツ・Compliance"/><p className="av2-boundary">AI Draftは公開物ではありません。Owner Approvalと手動公開が必要です。</p><div className="av2-card-grid">{risks.map(x=><Card key={x.id}><Badge label={x.classification}/><h3>{x.title}</h3><p>{x.rationale}</p></Card>)}{!risks.length&&<EmptyState title="Compliance結果は未取得です"/>}</div></>,
    publication:<PublicationWorkspace summary={summary}/>,
    evidence:<><SectionHeader title="Evidence Workspace"/><p>検証済みEvidenceのみを成果の根拠として扱います。未取得はUnknownです。</p></>,
    revenue:<RevenueWorkspace summary={summary}/>,
    learning:<><SectionHeader title="Learning・Business Memory"/><EmptyState title="表示可能なLearningはありません" message="既存のrevenue_learning_recordsを正本として利用します。"/><BusinessMemory memories={summary?.memories||[]}/></>,
    graph:<><SectionHeader title="Intelligence Graph" description="同じ内容をListでも確認できます。"/><ul className="av2-graph-list">{products.map(x=><li key={x.id}>Offer → Product: {x.name}</li>)}{research.map(x=><li key={x.id}>Offer → {x.entityType}: {x.name}</li>)}</ul>{!products.length&&!research.length&&<EmptyState title="関係データはありません"/>}</>,
    "ai-meeting":<><SectionHeader title="AI Meeting Summary"/><p className="av2-boundary">Provider: LOCKED · Meetingは最大1 Round · AI出力はInferenceです。</p><EmptyState title="AI Meetingは未実行です"/></>,
    audit:<><SectionHeader title="Decision・Event・Audit"/><EmptyState title="この画面で表示可能な監査記録はありません" message="システム管理情報はOwner画面に表示しません。"/><Timeline events={summary?.timeline||[]}/><PromptLibrary prompts={summary?.prompts||[]}/><MarketplaceFoundation assets={summary?.assets||[]}/></>
  };
  return <section className="av2-panel">{sections[view]||sections.strategy}</section>;
}

export function CommandPalette({open,onClose,commands,onNavigate}){const ref=useRef(null),dialogRef=useRef(null),restoreRef=useRef(null);useEffect(()=>{if(!open)return;restoreRef.current=document.activeElement;ref.current?.focus();const key=e=>{if(e.key==="Escape"){e.preventDefault();onClose();return}if(e.key!=="Tab")return;const nodes=[...dialogRef.current.querySelectorAll("input,button,[href],[tabindex]:not([tabindex=\"-1\"])")];if(!nodes.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}};document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);restoreRef.current?.focus?.()}},[open,onClose]);if(!open)return null;return <div className="av2-palette-backdrop" role="presentation" onMouseDown={onClose}><div ref={dialogRef} className="av2-palette" role="dialog" aria-modal="true" aria-label="コマンドパレット" onMouseDown={e=>e.stopPropagation()}><input ref={ref} aria-label="コマンドを検索" placeholder="移動先を選択"/>{commands.map(x=><button key={x.id} onClick={()=>onNavigate(x.path)}>{x.label}</button>)}</div></div>}

function PublicationWorkspace({summary}){const rows=publicationWorkspaceViewModel(summary);return <><SectionHeader title="Publication Workspace"/><p className="av2-boundary">Owner Approval後も公開は手動 · External Execution: LOCKED</p><div className="av2-card-grid">{rows.map(x=><Card key={x.id}><Badge label={x.manualPublicationReadiness}/><h3>{x.channel}</h3><p>Content: {x.contentStatus}</p><p>Affiliate Link: {x.affiliateLink}</p><p>Compliance: {x.complianceStatus}</p><p>Approval: {x.approvalState}</p><p>Publication URL: {x.publicationUrl}</p><p>Evidence: {x.evidenceStatus}</p><p>Performance: {x.performanceLinkage}</p></Card>)}{!rows.length&&<EmptyState title="Publication recordはありません" message="Unknownを維持し、自動公開は行いません。"/>}</div></>}

function RevenueWorkspace({summary}){const x=revenueWorkspaceViewModel(summary);const show=v=>typeof v==="number"?v:"Unknown";return <><SectionHeader title="Revenue Workspace"/><p className="av2-boundary">Actualはcanonical affiliate performance recordsのみ。Forecastは別セクションです。</p><p className="av2-boundary">ForecastとActualは合算しません</p><dl className="av2-data-grid"><div><dt>Actual approved revenue</dt><dd>{show(x.actualApprovedRevenue)}</dd></div><div><dt>Pending revenue</dt><dd>{show(x.pendingRevenue)}</dd></div><div><dt>Rejected revenue</dt><dd>{show(x.rejectedRevenue)}</dd></div><div><dt>Actual cost</dt><dd>{show(x.actualCost)}</dd></div><div><dt>Net profit</dt><dd>{show(x.netProfit)}</dd></div><div><dt>ROI</dt><dd>{show(x.roi)}</dd></div><div><dt>Clicks</dt><dd>{show(x.clicks)}</dd></div><div><dt>Conversions</dt><dd>{show(x.conversions)}</dd></div><div><dt>CVR</dt><dd>{show(x.cvr)}</dd></div><div><dt>EPC</dt><dd>{show(x.epc)}</dd></div></dl><SectionHeader title="Forecast"/><p>{x.forecast.length?"Forecast records available":"Unknown — no forecast promoted to Actual."}</p></>}
