import { useMemo, useState } from "react";
import { Badge, Button, Card, FormField, Input, SectionHeader, Select, Table } from "../../design-system/index.js";
import { listingComplianceLabel } from "../../domain/affiliateProgramMaster.js";

const value = (input, suffix = "") => input == null ? "Unknown" : `${input}${suffix}`;
export default function AffiliateProgramMaster({ programs = [], available = true, onSaveLink, onRegister, onUpdate }) {
  const [selectedId, setSelectedId] = useState(null), selected = useMemo(() => programs.find((item) => item.id === selectedId) || null, [programs, selectedId]);
  const columns = [{ key:"programName",label:"Program Name",render:(row)=><button type="button" className="av2-program-link" onClick={()=>setSelectedId(row.id)}>{row.programName}</button>},{key:"advertiserName",label:"Advertiser"},{key:"aspName",label:"ASP"},{key:"category",label:"Category",render:(row)=>row.category||"Unknown"},{key:"rewardSummary",label:"Reward",render:(row)=>row.rewardSummary||"Unknown"},{key:"epc",label:"EPC",render:(row)=>value(row.epc)},{key:"approvalRate",label:"Approval Rate",render:(row)=>value(row.approvalRate,"%")},{key:"programStatus",label:"Program Status"},{key:"affiliateLinkStatus",label:"Affiliate Link"},{key:"compliance",label:"Listing Compliance",render:(row)=><Badge label={listingComplianceLabel(row)} state={row.listingVerificationStatus==="CONFIRMED"?"actual":"pending"}/>}];
  return <section aria-labelledby="affiliate-program-master-title"><SectionHeader title="Affiliate Program Master" description={`${available?programs.length:"Unknown"} programs · Owner Personal Workspace`}/><Registration onRegister={onRegister}/><Table caption="Affiliate Program Master" columns={columns} rows={programs} emptyTitle={available?"Program Masterに登録はありません":"Program Masterを確認できません"} emptyMessage={available?"最初の案件を登録してください。":"未取得をゼロとは扱いません。"}/>{selected?<Detail program={selected} onClose={()=>setSelectedId(null)} onSaveLink={onSaveLink} onUpdate={onUpdate}/>:null}</section>;
}

function Registration({ onRegister }) {
  const initial={aspName:"",programId:"",advertiserName:"",programName:"",category:"",sourceNotes:""},[form,setForm]=useState(initial),[save,setSave]=useState({pending:false,error:null,done:false});
  const change=(field)=>(event)=>setForm((current)=>({...current,[field]:event.target.value}));
  const submit=async(event)=>{event.preventDefault();setSave({pending:true,error:null,done:false});try{await onRegister(form);setForm(initial);setSave({pending:false,error:null,done:true})}catch(error){setSave({pending:false,error:error?.code||"AFFILIATE_REGISTRATION_FAILED",done:false})}};
  return <Card><SectionHeader title="アフィリエイト案件を登録" description="Owner Personal Workspaceへ非公開で保存します。外部実行は行いません。"/><form onSubmit={submit}><div className="av2-data-grid"><FormField label="ASP名" required><Input value={form.aspName} onChange={change("aspName")} maxLength={120} required pending={save.pending}/></FormField><FormField label="Program ID" required><Input value={form.programId} onChange={change("programId")} maxLength={120} required pending={save.pending}/></FormField><FormField label="広告主名" required><Input value={form.advertiserName} onChange={change("advertiserName")} maxLength={200} required pending={save.pending}/></FormField><FormField label="Program名" required><Input value={form.programName} onChange={change("programName")} maxLength={500} required pending={save.pending}/></FormField><FormField label="カテゴリ"><Input value={form.category} onChange={change("category")} maxLength={200} pending={save.pending}/></FormField><FormField label="Sourceメモ" error={save.error}><Input value={form.sourceNotes} onChange={change("sourceNotes")} maxLength={1000} pending={save.pending}/></FormField></div><Button type="submit" pending={save.pending}>案件を登録</Button>{save.done?<p role="status">登録しました。</p>:null}</form></Card>;
}

function Detail({ program, onClose, onSaveLink, onUpdate }) {
  const [url,setUrl]=useState(program.affiliateUrl||""),[status,setStatus]=useState(program.affiliateLinkStatus==="NOT_REGISTERED"?"ACTIVE":program.affiliateLinkStatus),[linkSave,setLinkSave]=useState({pending:false,error:null,done:false});
  const [edit,setEdit]=useState({programName:program.programName,advertiserName:program.advertiserName,category:program.category||"",rewardSummary:program.rewardSummary||"",ownerNotes:program.ownerNotes||""}),[editSave,setEditSave]=useState({pending:false,error:null,done:false});
  const change=(field)=>(event)=>setEdit((current)=>({...current,[field]:event.target.value}));
  const update=async(changes)=>{setEditSave({pending:true,error:null,done:false});try{await onUpdate(program.id,{expectedUpdatedAt:program.updatedAt,changes});setEditSave({pending:false,error:null,done:true})}catch(error){setEditSave({pending:false,error:error?.code||"UPDATE_FAILED",done:false})}};
  const saveLink=async(event)=>{event.preventDefault();setLinkSave({pending:true,error:null,done:false});try{await onSaveLink(program.id,{affiliateUrl:url,linkStatus:status});setLinkSave({pending:false,error:null,done:true})}catch(error){setLinkSave({pending:false,error:error?.code||"SAVE_FAILED",done:false})}};
  return <Card className="av2-program-detail"><div className="av2-program-detail__header"><div><p className="eyebrow">PROGRAM DETAIL</p><h3>{program.programName}</h3><p>{program.advertiserName} · {program.aspName} · {program.programId}</p></div><Button variant="secondary" onClick={onClose}>閉じる</Button></div><dl className="av2-data-grid"><div><dt>Category</dt><dd>{program.category||"Unknown"}</dd></div><div><dt>Reward</dt><dd>{program.rewardSummary||"Unknown"}</dd></div><div><dt>EPC</dt><dd>{value(program.epc)}</dd></div><div><dt>Approval Rate</dt><dd>{value(program.approvalRate,"%")}</dd></div><div><dt>Program Status</dt><dd>{program.programStatus}</dd></div><div><dt>External Execution</dt><dd>LOCKED</dd></div></dl><SectionHeader title="Compliance"/><dl className="av2-data-grid"><div><dt>リスティング制限</dt><dd>{program.listingPolicy}</dd></div><div><dt>確認状態</dt><dd>{listingComplianceLabel(program)}</dd></div><div><dt>Source</dt><dd>{program.sourceType||"Unknown"}</dd></div><div><dt>確認日時</dt><dd>{program.sourceVerifiedAt||"Unknown"}</dd></div></dl><div><h4>リスティングNGワード</h4>{program.listingNgWords===null?<p role="status">未確認</p>:<ul>{program.listingNgWords.map((word,index)=><li key={`${index}-${word}`}>{word}</li>)}</ul>}<p className="av2-source-raw">原文: {program.listingNgWordsRaw||"未確認"}</p></div>
  <form onSubmit={(event)=>{event.preventDefault();update(edit)}}><SectionHeader title="案件を編集" description="保存時に更新競合を検出します。"/><div className="av2-data-grid"><FormField label="Program名"><Input value={edit.programName} onChange={change("programName")} maxLength={500} pending={editSave.pending}/></FormField><FormField label="広告主名"><Input value={edit.advertiserName} onChange={change("advertiserName")} maxLength={200} pending={editSave.pending}/></FormField><FormField label="カテゴリ"><Input value={edit.category} onChange={change("category")} maxLength={200} pending={editSave.pending}/></FormField><FormField label="報酬概要"><Input value={edit.rewardSummary} onChange={change("rewardSummary")} maxLength={4000} pending={editSave.pending}/></FormField><FormField label="Ownerメモ" error={editSave.error}><Input value={edit.ownerNotes} onChange={change("ownerNotes")} maxLength={10000} pending={editSave.pending}/></FormField></div><div className="av2-action-row"><Button type="submit" pending={editSave.pending}>変更を保存</Button><Button type="button" variant="secondary" pending={editSave.pending} onClick={()=>update({programStatus:"PAUSED"})}>一時停止</Button><Button type="button" variant="secondary" pending={editSave.pending} onClick={()=>update({programStatus:"ACTIVE"})}>再開</Button><Button type="button" variant="secondary" pending={editSave.pending} onClick={()=>window.confirm("この案件をArchiveしますか？")&&update({programStatus:"ARCHIVED"})}>Archive</Button></div>{editSave.done?<p role="status">保存しました。</p>:null}</form>
  <form onSubmit={saveLink}><SectionHeader title="Affiliate URL" description="Owner-only · http/https only"/><FormField label="Affiliate URL" error={linkSave.error}><Input type="url" value={url} onChange={(event)=>setUrl(event.target.value)} placeholder="https://" pending={linkSave.pending}/></FormField><FormField label="Link Status"><Select value={status} onChange={(event)=>setStatus(event.target.value)} pending={linkSave.pending}><option value="ACTIVE">ACTIVE</option><option value="PAUSED">PAUSED</option><option value="EXPIRED">EXPIRED</option></Select></FormField><div className="av2-action-row"><Button type="submit" pending={linkSave.pending}>広告リンクを保存</Button><Button type="button" variant="secondary" onClick={()=>{setUrl("");setStatus("ACTIVE")}}>登録解除</Button></div>{linkSave.done?<p role="status">保存しました。</p>:null}</form></Card>;
}
